"use strict";
const test = require("node:test"); const assert = require("node:assert/strict"); const { stableSerialize } = require("custodian");
const { startRun, status, look, act, saveRun, resumeRun } = require("../tools/run-bootstrap"); const { executeNatural, buildSafeContext } = require("../tools/ai-adapter"); const { createMockProvider } = require("../tools/ai-mock-provider");
function field(seed = "expedition") { return startRun({ profile: "field-researcher", seed }).run; }
function smooth(run) { act(run, "MOVE"); const alias = look(run).aliases[0].alias; act(run, "INSPECT", alias); act(run, "RECORD", alias); act(run, "COMMUNICATE", "standard"); act(run, "USE", "survey-instrument"); return act(run, "RETURN"); }
test("legacy procedural field tooling initializes team, order, and equipment without competing objective truth", () => { const run = field(); const current = status(run); assert.equal(current.scenario, "async-clear-q4-field-survey"); assert.equal(current.expedition.team.length, 3); assert.deepEqual(current.expedition.objectives, {}); assert.equal(current.expedition.mission_lifecycle, null); assert.ok(current.available_verbs.includes("COMMUNICATE")); assert.ok(current.available_verbs.includes("RECORD")); assert.ok(current.available_verbs.includes("WAIT")); });
test("legacy procedural terminal reports derive from retained conditions without an objective state machine", () => { const smoothRun = field("paths"); assert.equal(smooth(smoothRun).outcome, "succeeded"); assert.equal(smoothRun.expedition.result.outcome, "completed"); assert.equal(Object.values(smoothRun.expedition.result.conditions).every(Boolean), true); const degraded = field("paths"); act(degraded, "MOVE"); act(degraded, "WAIT"); act(degraded, "WAIT"); assert.equal(act(degraded, "ABORT").outcome, "succeeded"); assert.equal(degraded.expedition.result.outcome, "aborted"); assert.equal(degraded.expedition.result.conditions.standard_contact, false); });
test("communication, evidence custody, resource consumption, and hidden targets remain bounded", () => { const run = field(); assert.equal(act(run, "COMMUNICATE", "unknown").error.code, "RECIPIENT_UNAVAILABLE"); assert.equal(act(run, "RECORD", "hidden-target").error.code, "TARGET_UNAVAILABLE"); act(run, "MOVE"); const alias = look(run).aliases[0].alias; act(run, "RECORD", alias); assert.equal(run.expedition.evidence[0].custodian, run.session.startup.player.observer_id); assert.equal(act(run, "COMMUNICATE", "standard").outcome, "succeeded"); assert.equal(run.expedition.equipment["survey-radio"].charges, 7); assert.equal(act(run, "USE", "unknown-device").error.code, "EQUIPMENT_UNAVAILABLE"); });
test("expedition save/restore and accepted action history remain deterministic", () => { let saved = field("save"); act(saved, "MOVE"); const alias = look(saved).aliases[0].alias; act(saved, "INSPECT", alias); saved = resumeRun(saveRun(saved)).run; assert.equal(act(saved, "RECORD", alias).outcome, "succeeded"); act(saved, "COMMUNICATE", "standard"); act(saved, "USE", "survey-instrument"); act(saved, "RETURN"); const direct = field("save"); smooth(direct); assert.deepEqual(saved.expedition.result, direct.expedition.result); assert.equal(stableSerialize(saved.session.projection), stableSerialize(direct.session.projection)); });
test("offline interpreter receives no session and returns proposals without executing expedition verbs", async () => { const run = field("ai-expedition"); act(run, "MOVE"); const context = buildSafeContext(run); assert.equal("session" in context, false); const provider = createMockProvider(); for (const text of ["take a picture of the fixture", "radio Standard", "wait a minute"]) { const result = await executeNatural({ run, provider, player_text: text }); assert.equal(result.intent.status, "proposal"); assert.equal(result.steps.length, 0); } });
