"use strict";
const test = require("node:test"); const assert = require("node:assert/strict");
const { startRun, look, act, status, saveRun, resumeRun } = require("../tools/run-bootstrap"); const { initialize, visible, move, validate, VERSION } = require("../tools/procedural-complex"); const { buildSafeContext, executeNatural } = require("../tools/ai-adapter"); const { createMockProvider } = require("../tools/ai-mock-provider");
const proceduralRun = (seed = "yb17") => startRun({ profile: "field-researcher", seed, scenario: "procedural-survey" }).run;
test("same seed materializes authority-traceable bounded topology while different seeds vary", () => { const a = initialize({ seed: "same", observer: "a" }); const b = initialize({ seed: "same", observer: "a" }); assert.deepEqual(a, b); const c = initialize({ seed: "other", observer: "a" }); assert.notDeepEqual(a.region_seed, c.region_seed); const first = visible(a, "a").exits[0].alias; assert.equal(move(a, "a", first).ok, true); assert.equal(validate(a).length, 0); for (const node of Object.values(a.nodes)) assert.ok(node.authority && node.grammar_rule_id); });
test("procedural LOOK, MOVE, INSPECT, RECORD and discovery expose no hidden topology", () => { const run = proceduralRun(); const before = look(run); assert.ok(before.view.exits[0].alias); assert.equal(before.view.exits[0].destination_known, false); assert.equal("nodes" in before, false); assert.equal(act(run, "MOVE", before.view.exits[0].alias).outcome, "succeeded"); const after = look(run); const feature = after.view.features[0].alias; assert.equal(act(run, "INSPECT", feature).outcome, "succeeded"); assert.equal(act(run, "RECORD", feature).outcome, "succeeded"); assert.ok(status(run).discovered_topology.spaces.length >= 2); assert.equal(act(run, "MOVE", "space-secret").error.code, "TARGET_UNAVAILABLE"); });
test("generated aliases are stale outside the current view and materialized topology restores exactly", () => { const run = proceduralRun("save"); const passage = look(run).view.exits[0].alias; act(run, "MOVE", passage); const stale = passage; const saved = saveRun(run); const restored = resumeRun(saved); assert.equal(restored.ok, true); assert.deepEqual(restored.run.procedural, run.procedural); assert.equal(act(restored.run, "MOVE", stale).error.code, "TARGET_UNAVAILABLE"); const bad = structuredClone(saved); bad.procedural.version = "yellow-beast-complex-generator@unknown"; assert.equal(resumeRun(bad).ok, false); });
test("procedural survey has deterministic smooth completion and degraded abort paths", () => { const smooth = proceduralRun("paths"); act(smooth, "MOVE", look(smooth).view.exits[0].alias); const feature = look(smooth).view.features[0].alias; act(smooth, "INSPECT", feature); act(smooth, "RECORD", feature); act(smooth, "COMMUNICATE", "standard"); act(smooth, "USE", "survey-instrument"); assert.equal(act(smooth, "RETURN").run.expedition.result.outcome, "completed"); const degraded = proceduralRun("paths"); act(degraded, "WAIT"); act(degraded, "WAIT"); assert.equal(act(degraded, "ABORT").run.expedition.result.outcome, "aborted"); });
test("AI only receives visible generated aliases and cannot create rooms", async () => { const run = proceduralRun("ai"); const context = buildSafeContext(run); assert.equal("nodes" in context, false); const provider = createMockProvider(); const result = await executeNatural({ run, provider, player_text: "go through the hallway" }); assert.equal(result.steps[0].proposed.verb, "MOVE"); const rejected = await executeNatural({ run, provider, player_text: "build a secret room" }); assert.equal(rejected.intent.kind, "invalid"); assert.equal(run.procedural.version, VERSION); });
