"use strict";

const assert = require("node:assert/strict");
const test = require("node:test");
const history = require("../tools/world-history");
const gameplay = require("../tools/gameplay");
const nullzone = require("../tools/nullzone-exposure");
const lost = require("../tools/lost");
const { startRun, act, look } = require("../tools/run-bootstrap");

function completedFieldWorld() { const world = history.createWorld({ seed: "gameplay" }); const run = startRun({ profile: "field-researcher", scenario: "procedural-survey", seed: "field", world }).run; act(run, "MOVE", look(run).view.exits[0].alias); act(run, "INSPECT", look(run).view.features[0].alias); act(run, "RECORD", look(run).view.features[0].alias); act(run, "COMMUNICATE", "standard"); act(run, "RETURN"); return { world, run }; }
test("Clear-Q4 objectives are provenance-backed, optional, bounded, and persistent", () => { const { world, run } = completedFieldWorld(); const primary = gameplay.createObjective(world, { run_id: run.run_id, mode: "clear-q4", type: "complete-survey", origin: { kind: "run", id: run.run_id }, target: "approved survey", reward: { unlock: "better-preparation", summary: "Preparation option available." } }); assert.equal(primary.ok, true); const evidence = Object.keys(world.evidence)[0]; const optional = gameplay.createObjective(world, { run_id: run.run_id, mode: "clear-q4", type: "record-evidence", classification: "secondary", origin: { kind: "evidence", id: evidence }, target: "recorded observation" }); const deviation = gameplay.createObjective(world, { run_id: run.run_id, mode: "clear-q4", type: "document-deviation", classification: "deviation", origin: { kind: "run", id: run.run_id } }); assert.equal(optional.ok, true); assert.equal(deviation.objective.classification, "deviation"); assert.equal(gameplay.createObjective(world, { run_id: run.run_id, mode: "clear-q4", type: "record-evidence", classification: "secondary", origin: { kind: "evidence", id: evidence } }).idempotent, true); const resolved = gameplay.resolveObjective(world, { run_id: run.run_id, objective_id: primary.objective.id, outcome: "completed", follow_up: { type: "resurvey", target: "known survey region" } }); assert.equal(resolved.follow_up.depth, 1); assert.equal(gameplay.resolveObjective(world, { run_id: run.run_id, objective_id: optional.objective.id, outcome: "partial" }).objective.status, "partial"); assert.equal(gameplay.projection(world, { mode: "clear-q4" }).progression.length, 1); const summary = gameplay.sessionSummary(world, { run_id: run.run_id, mode: "clear-q4" }); const restored = structuredClone(world); assert.deepEqual(gameplay.projection(restored, { mode: "clear-q4", run_id: run.run_id }), gameplay.projection(world, { mode: "clear-q4", run_id: run.run_id })); assert.equal(summary.summary.objectives.length, 3); });
test("objectives reject hidden sources and cap follow-up depth", () => { const { world, run } = completedFieldWorld(); assert.equal(gameplay.createObjective(world, { run_id: run.run_id, mode: "clear-q4", type: "hidden", origin: { kind: "evidence", id: "missing" } }).code, "OBJECTIVE_SOURCE_UNKNOWN"); const parent = gameplay.createObjective(world, { run_id: run.run_id, mode: "clear-q4", type: "root", origin: { kind: "run", id: run.run_id } }).objective; const first = gameplay.resolveObjective(world, { run_id: run.run_id, objective_id: parent.id, outcome: "completed", follow_up: { type: "one" } }).follow_up; const second = gameplay.resolveObjective(world, { run_id: run.run_id, objective_id: first.id, outcome: "completed", follow_up: { type: "two" } }).follow_up; const result = gameplay.resolveObjective(world, { run_id: run.run_id, objective_id: second.id, outcome: "completed", follow_up: { type: "three" } }); assert.equal(result.follow_up, null); });
test("Nullzone artifact value is personal, persistent, and duplicate-aware", () => { const world = history.createWorld({ seed: "nullzone-value" }); const run_id = history.beginRun(world, { profile: "local-anomaly", scenario: "nullzone", seed: "n" }); nullzone.prepare(world, run_id, ["field-light", "evidence-container"]); nullzone.enter(world, run_id); const found = nullzone.discoverArtifact(world, run_id); nullzone.recover(world, run_id, found.artifact_id); nullzone.returnBase(world, run_id); nullzone.archive(world, run_id, found.artifact_id); const first = gameplay.assessArtifact(world, { run_id, mode: "nullzone", source_id: found.artifact_id }); assert.equal(first.value.novelty, "new"); const second = gameplay.assessArtifact(world, { run_id, mode: "nullzone", source_id: found.artifact_id }); assert.equal(second.idempotent, true); const duplicate = history.leaveRemnant(world, { run_id, region_id: world.civilian.base.access_region_id, space_id: "alternate-known-location", type: "unidentified-object", provenance: "fixture" }); world.artifacts[duplicate.artifact_id].state = "archived"; world.civilian.base.archive.push(duplicate.artifact_id); assert.equal(gameplay.assessArtifact(world, { run_id, mode: "nullzone", source_id: duplicate.artifact_id }).value.novelty, "duplicate"); assert.equal(JSON.stringify(gameplay.projection(world, { mode: "nullzone" })).includes("institutional"), false); });
test("Lost preserves a sparse run outcome summary without a guaranteed objective", () => { const world = history.createWorld({ seed: "lost-summary" }); const run = lost.start(world, "no-exit"); const primary = gameplay.createObjective(world, { run_id: run.run_id, mode: "lost", type: "reach-safe-route", origin: { kind: "run", id: run.run_id }, target: "known route" }); gameplay.resolveObjective(world, { run_id: run.run_id, objective_id: primary.objective.id, outcome: "stranded" }); lost.strand(world, run); const summary = gameplay.sessionSummary(world, { run_id: run.run_id, mode: "lost" }).summary; assert.equal(summary.objectives[0].outcome, "stranded"); assert.ok(summary.persistent_consequences.some((item) => item.includes("remnant"))); });
test("reviewed institutional evidence creates a bounded Beck follow-up only from admitted knowledge", () => { const { world, run } = completedFieldWorld(); const evidence = Object.keys(world.evidence)[0]; const record = `institutional-evidence-${evidence}`; assert.ok(world.knowledge.institutional.records[record]); const objective = gameplay.createObjective(world, { run_id: run.run_id, mode: "beck", type: "review-field-evidence", origin: { kind: "institutional-record", id: record }, target: "admitted evidence", reward: { unlock: "follow-up-review" } }); assert.equal(objective.ok, true); assert.equal(gameplay.assessEvidence(world, { run_id: run.run_id, mode: "beck", source_id: evidence }).ok, true); assert.equal(gameplay.createObjective(world, { run_id: run.run_id, mode: "beck", type: "hidden-evidence", origin: { kind: "evidence", id: "not-known" } }).code, "OBJECTIVE_SOURCE_UNKNOWN"); });
