"use strict";
const assert = require("node:assert/strict");
const test = require("node:test");
const convergence = require("../tools/canon-convergence");
const echoes = require("../tools/consequence-echoes");

test("unfinished business is derived, observer-specific, and mode-native", () => { const fixture = convergence.fixture("yb32-unfinished-test"); const field = echoes.unfinishedBusiness(fixture.world, "field-researcher"); const beck = echoes.unfinishedBusiness(fixture.world, "async-command"); const personal = structuredClone(fixture.world); personal.civilian = { unresolved: ["compare the recovered photograph"], hypotheses: { one: { state: "suspected" } } }; const nullzone = echoes.unfinishedBusiness(personal, "local-anomaly"); const lost = echoes.unfinishedBusiness(fixture.world, "lost"); assert.ok(field.items.some((item) => ["object", "observation", "personnel", "report"].includes(item.kind))); assert.ok(beck.items.some((item) => ["report", "disagreement"].includes(item.kind))); assert.ok(nullzone.items.some((item) => item.kind === "question")); assert.equal(lost.items.length, 0); assert.equal(lost.implicit_continuity, true); assert.notDeepEqual(field.items, beck.items); });
test("unfinished business never creates canonical work or exposes fate, taxonomy, or IDs", () => { const fixture = convergence.fixture("yb32-unfinished-safe"); const before = JSON.stringify(fixture.world); const output = JSON.stringify(["field-researcher", "async-command", "local-anomaly", "lost"].map((profile) => echoes.unfinishedBusiness(fixture.world, profile))); assert.equal(JSON.stringify(fixture.world), before); assert.doesNotMatch(output, /(?:history|artifact|phenomenon|character|region|run|mystery|quest|objective)-[a-f0-9]{8,}/i); assert.doesNotMatch(output, /dead|Still Life|culprit|motive|secretly|will happen/i); assert.equal(fixture.world.events.length, 18); });
test("repeated unfinished-business reads remain bounded and event-free", () => { const fixture = convergence.fixture("yb32-unfinished-long"); const before = fixture.world.events.length; for (let turn = 0; turn < 150; turn += 1) { const view = echoes.unfinishedBusiness(fixture.world, ["field-researcher", "async-command", "local-anomaly", "lost"][turn % 4]); assert.ok(view.items.length <= echoes.MAX_ECHOES); } assert.equal(fixture.world.events.length, before); assert.equal(fixture.world.characters["convergence-researcher"].status, "dead"); });
