"use strict";
const app = document.querySelector("#app"); let current = { world: null, mode: null, projection: null };
const escape = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;" })[char]);
function error(result) { return result?.error ? `<p class="error">${escape(result.error.message)}</p>` : ""; }
function button(label, action, disabled = false) { return `<button data-action="${action}" ${disabled ? "disabled" : ""}>${escape(label)}</button>`; }
async function home() { const [info, worlds] = await Promise.all([yellowBeast.getAppInfo(), yellowBeast.listWorlds()]); const list = worlds.worlds.map((world) => `<li><strong>${escape(world.name)}</strong><span>${escape(world.last_mode ?? "No recent role")}</span>${button("Continue", `world:${world.id}`)}</li>`).join("") || "<li>No worlds yet. Create one to begin.</li>"; app.innerHTML = `<section class="shell"><header><div><p class="eyebrow">YELLOW BEAST <span>ALPHA</span></p><h1>Persistent Backrooms simulation</h1><p>Choose a world, then choose a role. Every role shares the same world.</p></div><p class="version">v${escape(info.app.version)}</p></header><nav>${button("New World", "new")}${button("Settings", "settings")}${button("About", "about")}</nav><section><h2>Continue World</h2><ul class="worlds">${list}</ul></section></section>`; }
function newWorld() { app.innerHTML = `<section class="shell narrow"><p class="eyebrow">NEW WORLD</p><h1>Create a persistent world</h1><p>A world remembers what happens across every role. The optional seed is for repeatable testing.</p><form id="new-world"><label>World name <input name="name" required maxlength="80" autofocus></label><details><summary>Advanced</summary><label>Deterministic seed <input name="seed"></label></details><div>${button("Create World", "submit")}${button("Back", "home")}</div></form><div id="message"></div></section>`; document.querySelector("#new-world").addEventListener("submit", async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await yellowBeast.createWorld({ name: data.get("name"), seed: data.get("seed") || null }); if (!result.ok) document.querySelector("#message").innerHTML = error(result); else selectWorld(result.world.id); }); }
async function selectWorld(id) { const [world, modes] = await Promise.all([yellowBeast.loadWorld({ world_id:id }), yellowBeast.listModes()]); if (!world.ok) { app.innerHTML = `<section class="shell"><h1>World unavailable</h1>${error(world)}${button("Back", "home")}</section>`; return; } current.world = world.world; const cards = modes.modes.map((mode) => `<article><p class="eyebrow">${escape(mode.role)}</p><h2>${escape(mode.label)}</h2><p>${escape(mode.description)}</p>${button("Enter mode", `mode:${mode.id}`)}</article>`).join(""); app.innerHTML = `<section class="shell"><p class="eyebrow">${escape(world.world.name)}</p><h1>Choose a role</h1><p>All roles share this world. Physical consequences can persist for later sessions.</p><div class="cards">${cards}</div>${button("Back", "home")}</section>`; }
async function enterMode(mode) { current.mode = mode; const resumed = await yellowBeast.resumeSession({ world_id:current.world.id, mode }); const result = resumed.ok ? resumed : await yellowBeast.startSession({ world_id:current.world.id, mode }); if (!result.ok) { app.innerHTML = `<section class="shell"><h1>Unable to enter mode</h1>${error(result)}${button("Back", `world:${current.world.id}`)}</section>`; return; } current.projection = result.projection; play(); }
function play(message = "") { const projection = current.projection; const actionOptions = projection.available_actions.map((action) => `<option value="${escape(action.type)}">${escape(YBSurfaces.actionLabel(action.type))}</option>`).join(""); app.innerHTML = `<section class="shell play" data-testid="play-shell"><header><div><p class="eyebrow">${escape(projection.world.name)} · SHARED WORLD</p><h1>${escape(projection.mode.label)}</h1><p>${escape(projection.mode.description)}</p></div>${button("Leave session", "leave")}</header>${message ? `<p class="notice" role="status">${escape(message)}</p>` : ""}${YBSurfaces.render(projection)}<section class="action-dock" aria-label="Structured action input"><h2>Action</h2><form id="action-form"><label>Choose action <select name="action" data-testid="action-select">${actionOptions}</select></label><label id="target-label">Valid target <select name="target" data-testid="target-select"></select></label><button type="submit" data-testid="submit-action">Submit action</button></form><p>Yellow Beast accepts the action before this projection refreshes.</p></section></section>`;
  const form = document.querySelector("#action-form"); const actionSelect = form.action; const targetSelect = form.target;
  function targetsForAction() { const action = projection.available_actions.find((item) => item.type === actionSelect.value); const targets = action?.targets ?? []; targetSelect.innerHTML = targets.map((target) => `<option value="${escape(target.ref)}">${escape(target.label)}</option>`).join(""); targetSelect.disabled = targets.length === 0; document.querySelector("#target-label").hidden = !action?.target_required; }
  targetsForAction(); actionSelect.addEventListener("change", targetsForAction);
  app.querySelectorAll("[data-game-action]").forEach((item) => item.addEventListener("click", () => { actionSelect.value = item.dataset.gameAction; targetsForAction(); form.scrollIntoView({ behavior: "smooth", block: "center" }); actionSelect.focus(); }));
  form.addEventListener("submit", async (event) => { event.preventDefault(); const data = new FormData(form); const result = await yellowBeast.submitAction({ world_id:current.world.id, mode:current.mode, action:data.get("action"), target:data.get("target") || null }); if (!result.ok) { const refresh = await yellowBeast.getGameplayProjection({ world_id:current.world.id, mode:current.mode }); if (refresh.ok) current.projection = refresh.projection; return play(result.error.message); } current.projection = result.projection; play(result.result.public_reason || "Action accepted."); }); }
async function settings() { const result = await yellowBeast.getSettings(); app.innerHTML = `<section class="shell narrow"><p class="eyebrow">SETTINGS</p><h1>Play offline or configure later</h1><p>Offline structured play is always available. Provider setup is expanded in a later alpha pass.</p><form id="settings"><label>Input mode <select name="input_mode"><option value="structured">Structured</option><option value="natural">Natural language</option></select></label><label>Provider <select name="provider"><option value="offline">Offline</option><option value="openai">OpenAI (setup later)</option></select></label><div>${button("Save settings", "submit")}${button("Back", "home")}</div></form></section>`; const form = document.querySelector("#settings"); form.input_mode.value = result.settings.input_mode; form.provider.value = result.settings.provider; form.addEventListener("submit", async (event) => { event.preventDefault(); await yellowBeast.updateSettings({ settings:Object.fromEntries(new FormData(form)) }); home(); }); }
function about() { app.innerHTML = `<section class="shell narrow"><p class="eyebrow">ABOUT · ALPHA</p><h1>Yellow Beast</h1><p>A persistent, shared-world Backrooms simulation. It works in structured offline mode, with optional AI language interaction.</p><p>Worlds are saved in your application data folder; normal play never requires a terminal.</p>${button("Back", "home")}</section>`; }
document.addEventListener("click", (event) => { const action = event.target.dataset.action; if (!action) return; if (action === "home" || action === "leave") home(); else if (action === "new") newWorld(); else if (action === "settings") settings(); else if (action === "about") about(); else if (action.startsWith("world:")) selectWorld(action.slice(6)); else if (action.startsWith("mode:")) enterMode(action.slice(5)); }); home();
