"use strict";
const app = document.querySelector("#app");
const current = { world: null, mode: null, projection: null, developer: false };
const requestGate = new YBInteraction.RequestGate();
const presentation = new YBQol.PresentationMetadata();
const escape = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;" })[char]);
const button = (label, action, disabled = false) => `<button type="${action === "submit" ? "submit" : "button"}" data-action="${action}" ${disabled ? "disabled" : ""}>${escape(label)}</button>`;
const requestContext = () => ({ worldId: current.world?.id ?? "", mode: current.mode ?? "" });
const resultIsError = (result) => result?.ok === false || Boolean(result?.error);
const applicationError = (result) => /WORLD_|SAVE|REQUEST|INTERNAL/.test(result?.error?.code ?? "");
const applyPreferences = (settings) => YBAccessibility.apply(document, settings);

function setFeedback(text, state = "resolving") {
  const node = document.querySelector("#interaction-feedback");
  if (node) { node.textContent = text; node.dataset.state = state; }
}
function disableTurnForms() {
  app.querySelectorAll("#natural-form input, #natural-form button, #action-form select, #action-form button").forEach((item) => { item.disabled = true; });
}
function focusNaturalInput() { document.querySelector("#natural-form input")?.focus({ preventScroll: true }); }
function renderMessage(result, natural) {
  const detail = result?.result ?? {};
  if (detail.provider_unavailable) return "Offline narration is in use.";
  if (natural && detail.interpretation_error) return "That attempt could not be interpreted safely. No world state changed.";
  if (natural && detail.clarification_required) return `${detail.clarification_question || "That attempt needs clarification."} No world state changed.`;
  return detail.scene?.narration || detail.public_reason || detail.summary || (natural ? "That attempt could not be resolved." : "Action accepted.");
}

async function home() {
  requestGate.invalidate();
  const [info, worlds, preferences] = await Promise.all([yellowBeast.getAppInfo(), yellowBeast.listWorlds(), yellowBeast.getSettings()]);
  applyPreferences(preferences.settings); current.developer = info.app.developer_mode === true;
  const list = worlds.worlds.map((world) => `<li data-world-name="${escape(world.name)}"><strong>${escape(world.name)}</strong><span>${escape(world.last_mode ?? "Ready to choose an experience")}</span><span class="muted">Last played ${escape(world.last_played_at ? new Date(world.last_played_at).toLocaleDateString() : "not yet")}</span>${button("Open world", `world:${world.id}`)}${button("Rename", `rename:${world.id}`)}${button("Export", `export:${world.id}`)}${button("Delete", `delete:${world.id}`)}</li>`).join("") || `<li>${button("Create world", "new")}</li>`;
  app.innerHTML = `<section class="shell" data-testid="world-library"><header><div><p class="eyebrow">YELLOW BEAST <span>ALPHA</span></p><h1>World Library</h1><p>Choose a world. Each experience reveals a different legitimate part of the same history.</p></div><p class="version">v${escape(info.app.version)}</p></header><nav aria-label="Application">${button("Create world", "new")}${button("Import world", "import")}${button("Settings", "settings")}${button("About", "about")}</nav><section><h2>Your worlds</h2>${worlds.worlds.length ? `<label>Find a world <input id="world-filter" autocomplete="off" placeholder="Search names"></label>` : ""}<ul class="worlds">${list}</ul><details class="qol-help"><summary>Exporting a world</summary><p>Export creates a portable copy of this world. The world in your library remains unchanged; import that copy on another installation to continue it.</p></details></section></section>`;
  document.querySelector("#world-filter")?.addEventListener("input", (event) => { const query = event.target.value.toLowerCase(); app.querySelectorAll(".worlds li[data-world-name]").forEach((item) => { item.hidden = !item.dataset.worldName.toLowerCase().includes(query); }); });
}
function newWorld() {
  app.innerHTML = `<section class="shell narrow" data-testid="create-world"><p class="eyebrow">CREATE WORLD</p><h1>Start a shared world</h1><p>Choose a name and where you want to begin. The same world can be revisited through every experience.</p><form id="new-world"><label>World name <input name="name" required maxlength="80" autofocus></label><fieldset><legend>Where would you like to begin?</legend><label><input name="experience" type="radio" value="field-researcher" checked> Clear-Q4 <span class="muted">Field work with equipment and radio.</span></label><label><input name="experience" type="radio" value="async-command"> Beck's Desk <span class="muted">Institutional decisions and reports.</span></label><label><input name="experience" type="radio" value="local-anomaly"> Nullzone <span class="muted">Personal investigation and evidence.</span></label><label><input name="experience" type="radio" value="lost"> Lost <span class="muted">Sparse exploration and uncertain escape.</span></label></fieldset><label><input name="guided" type="checkbox" checked> Guided Introduction (recommended)</label><details><summary>Optional repeatable seed</summary><label>Seed <input name="seed"></label></details><div>${button("Create and begin", "submit")}${button("Back", "home")}</div></form><div id="message"></div></section>`;
  document.querySelector("#new-world").addEventListener("submit", async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const guided = data.get("guided") === "on"; const preference = await yellowBeast.updateSettings({ settings:{ guided_introductions:guided } }); if (resultIsError(preference)) { document.querySelector("#message").textContent = preference.error.message; return; } const result = await yellowBeast.createWorld({ name: data.get("name"), seed: data.get("seed") || null }); if (resultIsError(result)) document.querySelector("#message").textContent = result.error.message; else { current.world = result.world; await enterMode(data.get("experience") || "field-researcher"); } });
}
async function selectWorld(id) {
  requestGate.invalidate();
  const [world, modes] = await Promise.all([yellowBeast.loadWorld({ world_id:id }), yellowBeast.listModes()]);
  if (resultIsError(world)) { app.innerHTML = `<section class="shell"><h1>This world needs attention</h1><p class="error">${escape(world.error.message)}</p><p>Your world was not changed.</p>${button("Back", "home")}</section>`; return; }
  current.world = world.world;
  const style = { "async-command":"Institutional decisions, reports, and unresolved matters.", "field-researcher":"Operational field expedition with equipment and radio.", "local-anomaly":"Personal investigation through evidence and comparison.", lost:"Sparse exploration through immediate sensory detail." };
  const cards = modes.modes.map((mode) => `<article><h2>${escape(mode.label)}</h2><p>${escape(style[mode.id])}</p>${button("Enter experience", `mode:${mode.id}`)}</article>`).join("");
  app.innerHTML = `<section class="shell" data-testid="world-entry"><p class="eyebrow">${escape(world.world.name)}</p><h1>Choose an experience</h1><p>Physical consequences persist; private knowledge does not transfer automatically.</p><div class="cards">${cards}</div>${current.developer ? button("Developer console", "developer") : ""}${button("Back to library", "home")}</section>`;
}
const developerJson = (value) => escape(JSON.stringify(value, null, 2));
async function developerConsole() {
  requestGate.invalidate(); if (!current.world) return home();
  const result = await yellowBeast.getDeveloperSnapshot({ world_id:current.world.id, mode:current.mode });
  if (resultIsError(result)) { app.innerHTML = `<section class="shell"><h1>Developer console unavailable</h1><p class="error">${escape(result.error.message)}</p>${button("Back", `world:${current.world.id}`)}</section>`; return; }
  const data = result.snapshot, objective = data.objective, observer = current.devObserver ?? current.mode ?? "field-researcher", view = data.observer_views[observer] ?? {};
  const overview = { world:objective.world, active:result.active, counts:{ actors:objective.characters.length, artifacts:objective.objects.artifacts.length, evidence:objective.objects.evidence.length, regions:objective.regions.length, phenomena:objective.phenomena.length, threads:objective.threads.index.threads?.length ?? 0, recent_events:result.recent_history.length }, provider:result.provider };
  app.innerHTML = `<section class="shell developer-console" data-testid="developer-console"><header><div><p class="eyebrow">DEVELOPER TOOLING · READ ONLY</p><h1>Simulation Inspector</h1><p>Objective, observer-safe, and provider-safe material are separate derived inspections.</p></div>${button("Return to player", `world:${current.world.id}`)}</header><label>Inspect observer <select id="dev-observer">${Object.keys(data.observer_views).map((id) => `<option value="${escape(id)}" ${id === observer ? "selected" : ""}>${escape(id)}</option>`).join("")}</select></label><section class="panel"><h2>Overview · OBJECTIVE / DERIVED</h2><pre>${developerJson(overview)}</pre></section><section class="panel"><h2>Objective world</h2><details open><summary>Actors and continuity</summary><pre>${developerJson(objective.characters)}</pre></details><details><summary>Objects and evidence</summary><pre>${developerJson(objective.objects)}</pre></details><details><summary>Regions · initial seed and history modifications</summary><pre>${developerJson(objective.regions)}</pre></details><details><summary>Phenomena · capabilities and observer records</summary><pre>${developerJson(objective.phenomena)}</pre></details><details><summary>Story threads · DERIVED / NONCANONICAL</summary><pre>${developerJson(objective.threads)}</pre></details></section><section class="panel"><h2>Observer view · ${escape(observer)}</h2><pre>${developerJson(view)}</pre></section><section class="panel"><h2>Provider-safe context</h2><pre>${developerJson(result.provider_safe_context ?? { status:"No Clear-Q4 session selected." })}</pre></section><section class="panel"><h2>Recent canonical history · bounded</h2><pre>${developerJson(result.recent_history)}</pre></section><section class="panel"><h2>Intent trace · NON-EXECUTING</h2><form id="developer-trace"><label>Test phrase <input name="text" value="look around"></label><button type="submit">Trace only</button></form><pre id="developer-trace-result">No trace run.</pre></section></section>`;
  document.querySelector("#dev-observer").addEventListener("change", (event) => { current.devObserver = event.target.value; developerConsole(); });
  document.querySelector("#developer-trace").addEventListener("submit", async (event) => { event.preventDefault(); const response = await yellowBeast.traceDeveloperIntent({ world_id:current.world.id, mode:current.mode, text:new FormData(event.currentTarget).get("text") }); document.querySelector("#developer-trace-result").textContent = resultIsError(response) ? response.error.message : JSON.stringify(response.trace, null, 2); });
}
async function enterMode(mode) {
  requestGate.invalidate(); current.mode = mode; current.guidanceDismissed = false;
  const resumed = await yellowBeast.resumeSession({ world_id:current.world.id, mode });
  const result = resultIsError(resumed) ? await yellowBeast.startSession({ world_id:current.world.id, mode }) : resumed;
  if (resultIsError(result)) { app.innerHTML = `<section class="shell"><h1>Unable to enter experience</h1><p class="error">${escape(result.error.message)}</p>${button("Back", `world:${current.world.id}`)}</section>`; return; }
  current.projection = result.projection; applyPreferences(current.projection.settings); play(resumed.ok ? YBQol.history(current.projection, 1).length ? `Last time: ${YBQol.history(current.projection, 1)[0]}` : "Last time: return to what you can observe now." : "");
}
function recapMarkup(projection) {
  const recap = YBQol.recap(projection); const context = requestContext(); const history = YBQol.history(projection);
  const sections = recap.sections.map((part, sectionIndex) => `<section class="qol-recap-section" data-searchable="${part.search}"><h3>${escape(part.heading)}</h3><ul>${part.items.length ? part.items.map((item, itemIndex) => { const pin = `${sectionIndex}:${itemIndex}:${item}`; const pinned = presentation.pinned(context, pin); return `<li data-qol-item="${escape(String(item).toLowerCase())}"><span>${escape(item)}</span>${part.search ? `<button type="button" class="qol-pin" data-qol-pin="${escape(pin)}" aria-pressed="${pinned}" aria-label="${pinned ? "Unpin" : "Pin"} ${escape(item)}">${pinned ? "Pinned" : "Pin"}</button>` : ""}</li>`; }).join("") : "<li class=\"empty\">Nothing more is known here.</li>"}</ul></section>`).join("");
  const historyItems = history.length ? history.map((item) => `<li data-qol-item="${escape(item.toLowerCase())}">${escape(item)}</li>`).join("") : "<li class=\"empty\">No recent record is available.</li>";
  return `<details id="recap-panel" class="qol-recap" data-testid="qol-recap"><summary>What do I know?</summary><div class="qol-recap-body"><p>${escape(recap.title)} · only what this experience has legitimately revealed.</p>${recap.sections.some((part) => part.search) ? `<label>Find in this record <input id="recap-filter" autocomplete="off" placeholder="Search known notes"></label>` : ""}${sections}<section class="qol-recap-section"><h3>Recent record</h3><ul>${historyItems}</ul></section><button type="button" data-copy="scene">Copy current scene</button><p class="muted">Shortcut: ? opens this record; Escape closes it.</p></div></details>`;
}
function guidedIntroduction(projection) {
  if (projection.phase?.tutorial_context?.enabled !== true || current.guidanceDismissed) return "";
  const guidance = { "field-researcher":["You are entering Clear-Q4.","Describe an attempt in your own words, then use the scene and field brief to understand what happened."], "async-command":["You are at Beck's Desk.","Review the reports and choose what needs attention. Your decisions advance the institution's recorded work."], "local-anomaly":["You are beginning a Nullzone investigation.","Keep observations separate from conclusions; your notebook and evidence are personal to this experience."], lost:["You are in Lost.","Start with what you can see, hear, carry, or remember. Choose only from what this place gives you."] }[projection.mode.id] ?? ["You are beginning.","Describe what you are trying to do; the result will appear in the scene above."];
  return `<aside class="guided-introduction" data-testid="guided-introduction" aria-labelledby="guided-introduction-heading"><h2 id="guided-introduction-heading">Guided Introduction</h2><p><strong>${escape(guidance[0])}</strong> ${escape(guidance[1])}</p><p class="muted">Your accepted actions save automatically. Open <strong>What do I know?</strong> any time to review your current context.</p><button type="button" data-guidance-dismiss>Hide introduction</button></aside>`;
}
function play(message = "", state = "") {
  const projection = current.projection;
  const context = requestContext(); const draft = presentation.draft(context);
  const actionOptions = projection.available_actions.map((action) => `<option value="${escape(action.type)}">${escape(YBSurfaces.actionLabel(action.type))}</option>`).join("");
  applyPreferences(projection.settings); const scene = projection.scene ? `<section class="scene ${state === "result" ? "scene-result" : ""}" aria-labelledby="current-scene-heading"><h2 id="current-scene-heading" class="sr-only">Current scene</h2><p class="eyebrow">${escape(projection.scene.significance)}</p><p>${escape(projection.scene.narration)}</p>${projection.scene.inventory?.length ? `<p class="muted">Carrying: ${escape(projection.scene.inventory.map((item) => item.text).join(", "))}</p>` : ""}</section>` : "";
  const natural = `<section class="action-dock natural-action" data-testid="natural-primary"><h2>${escape(YBSurfaces.inputPrompt(projection.mode.id))}</h2><form id="natural-form"><label>Describe what you are trying to do <input name="text" autocomplete="off" value="${escape(draft)}" placeholder="${escape(YBSurfaces.inputExample(projection.mode.id))}"></label><button type="submit">Act</button></form><p>Describe an attempt in your own words. Structured controls remain available when useful.</p></section>`;
  const retry = state === "application-error" ? `<button type="button" data-action="refresh-view">Refresh view</button>` : "";
  app.innerHTML = `<section class="shell play mode-${escape(projection.mode.id)}" data-testid="play-shell"><header><div><p class="eyebrow">${escape(projection.world.name)}</p><h1>${escape(projection.mode.label)}</h1><p>${escape(projection.mode.description)}</p></div>${button("Leave session", "leave")}</header><p id="interaction-feedback" class="interaction-feedback" data-state="${escape(state)}" role="status" aria-live="polite" aria-atomic="true">${escape(message)}${retry}</p>${guidedIntroduction(projection)}${scene}${natural}${recapMarkup(projection)}${YBSurfaces.render(projection)}<details class="action-dock structured-action"><summary>Structured controls</summary><form id="action-form" aria-label="Structured action input"><label>Choose action <select name="action" data-testid="action-select">${actionOptions}</select></label><label id="target-label">Valid target <select name="target" data-testid="target-select"></select></label><button type="submit" data-testid="submit-action">Submit action</button></form></details><p class="muted">Accepted actions save automatically.</p></section>`;
  if (current.developer) document.querySelector(".play header").insertAdjacentHTML("beforeend", button("Developer console", "developer"));
  const form = document.querySelector("#action-form"); const actionSelect = form.action; const targetSelect = form.target;
  const targetsForAction = () => { const action = projection.available_actions.find((item) => item.type === actionSelect.value); const targets = action?.targets ?? []; targetSelect.innerHTML = targets.map((target) => `<option value="${escape(target.ref)}">${escape(target.label)}</option>`).join(""); targetSelect.disabled = targets.length === 0; document.querySelector("#target-label").hidden = !action?.target_required; };
  targetsForAction(); actionSelect.addEventListener("change", targetsForAction);
  app.querySelectorAll("[data-game-action]").forEach((item) => item.addEventListener("click", () => { form.closest("details").open = true; actionSelect.value = item.dataset.gameAction; targetsForAction(); actionSelect.focus({ preventScroll: true }); }));
  form.addEventListener("submit", (event) => { event.preventDefault(); const data = new FormData(form); submitTurn("structured", () => yellowBeast.submitAction({ world_id:current.world.id, mode:current.mode, action:data.get("action"), target:data.get("target") || null })); });
  const naturalForm = document.querySelector("#natural-form"); naturalForm.text.addEventListener("input", () => presentation.setDraft(context, naturalForm.text.value));
  naturalForm.addEventListener("submit", (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); submitTurn("natural", () => yellowBeast.submitNatural({ world_id:current.world.id, mode:current.mode, text:data.get("text") })); });
  const recap = document.querySelector("#recap-panel"); recap.open = presentation.panel(context) === "recap"; recap.addEventListener("toggle", () => presentation.setPanel(context, recap.open ? "recap" : ""));
  document.querySelector("[data-guidance-dismiss]")?.addEventListener("click", () => { current.guidanceDismissed = true; play(message, state); });
  document.querySelector("#recap-filter")?.addEventListener("input", (event) => { const query = event.target.value; app.querySelectorAll("[data-qol-item]").forEach((item) => { item.hidden = !YBQol.filter([item.dataset.qolItem], query).length; }); });
  app.querySelectorAll("[data-qol-pin]").forEach((item) => item.addEventListener("click", () => { const pinned = presentation.togglePin(context, item.dataset.qolPin); item.textContent = pinned ? "Pinned" : "Pin"; item.setAttribute("aria-pressed", String(pinned)); item.setAttribute("aria-label", `${pinned ? "Unpin" : "Pin"} ${item.closest("li")?.querySelector("span")?.textContent ?? "item"}`); }));
  app.querySelector("[data-copy=scene]")?.addEventListener("click", async () => { const text = projection.scene?.narration ?? ""; await navigator.clipboard?.writeText(text); setFeedback("Scene copied.", "result"); });
  if (state === "result") focusNaturalInput();
}
async function submitTurn(kind, request) {
  const context = requestContext(); const token = requestGate.begin(context);
  if (!token) return;
  disableTurnForms(); setFeedback(kind === "natural" ? "Submitted." : "Saving…", "submitted");
  Promise.resolve().then(() => { if (requestGate.isCurrent(token, context)) setFeedback(kind === "natural" ? "Resolving…" : "Saving…", "resolving"); });
  let result;
  try { result = await request(); } catch (_) {
    if (requestGate.settle(token, context)) play(YBInteraction.applicationMessage(), "application-error");
    return;
  }
  if (!requestGate.settle(token, context)) return;
  if (resultIsError(result)) {
    play(applicationError(result) ? YBInteraction.applicationMessage() : YBInteraction.simulationMessage(), applicationError(result) ? "application-error" : "simulation-result");
    return;
  }
  current.projection = result.projection;
  if (result.result?.scene) current.projection.scene = result.result.scene;
  const message = renderMessage(result, kind === "natural");
  const saved = kind === "structured" || result.result?.scene ? " Saved." : "";
  if (kind === "structured" || result.result?.executed) presentation.clearDraft(context);
  play(`${message}${saved}`, "result");
}
async function settings() {
  requestGate.invalidate(); const result = await yellowBeast.getSettings(); const configured = result.provider.openai.configured; applyPreferences(result.settings);
  app.innerHTML = `<section class="shell narrow" data-testid="settings"><p class="eyebrow">SETTINGS</p><h1>Settings</h1><p>Presentation preferences are saved for this player. They do not change what happens in a world.</p><form id="settings"><section class="settings-group"><h2>Appearance</h2><label>Appearance <select name="theme"><option value="system">System</option><option value="dark">Dark</option><option value="light">Light</option><option value="high-contrast">High contrast</option></select></label><label>Text size <select name="text_scale"><option value="small">Small</option><option value="default">Default</option><option value="large">Large</option><option value="extra-large">Extra large</option></select></label></section><section class="settings-group"><h2>Motion</h2><label><input type="checkbox" name="reduced_motion"> Reduce motion</label><p>State changes remain clear without animation.</p></section><section class="settings-group"><h2>Guidance</h2><label><input type="checkbox" name="guided_introductions"> Guided Introductions</label><p>Guidance is a player preference and never changes world history.</p></section><section class="settings-group"><h2>Language assistance</h2><p>Status: <strong>${configured ? "Ready" : "Not set up"}</strong></p><label>Input mode <select name="input_mode"><option value="structured">Structured controls</option><option value="natural">Natural language</option></select></label><label>Interpretation <select name="provider"><option value="offline">Offline / Structured</option><option value="openai">Language assistance</option></select></label></section><div class="settings-actions">${button("Save preferences", "submit")}<button type="button" data-action="reset-preferences">Reset presentation preferences</button></div></form><form id="openai" class="settings-group"><h2>Language assistance key</h2><label>Access key <input name="api_key" type="password" autocomplete="new-password" placeholder="Stored securely by the desktop app"></label><label>Response model (optional) <input name="model" maxlength="120"></label><div class="settings-actions">${button("Save access key", "submit")}${configured ? button("Remove key", "remove-key") : ""}</div></form><p id="settings-message" role="status" aria-live="polite" aria-atomic="true"></p><section class="panel"><h2>Saves</h2><p>Accepted actions save automatically and retain one previous-good backup.</p></section>${button("Back", "home")}</section>`;
  const form = document.querySelector("#settings"); form.input_mode.value = result.settings.input_mode; form.provider.value = result.settings.provider; form.theme.value = result.settings.theme; form.text_scale.value = result.settings.text_scale; form.reduced_motion.checked = Boolean(result.settings.reduced_motion); form.guided_introductions.checked = result.settings.guided_introductions !== false;
  const message = document.querySelector("#settings-message"); const preview = () => applyPreferences({ ...result.settings, theme:form.theme.value, text_scale:form.text_scale.value, reduced_motion:form.reduced_motion.checked, guided_introductions:form.guided_introductions.checked }); [form.theme, form.text_scale, form.reduced_motion].forEach((control) => control.addEventListener("change", preview)); form.addEventListener("submit", async (event) => { event.preventDefault(); const data = new FormData(form); const saved = await yellowBeast.updateSettings({ settings:{ input_mode:data.get("input_mode"), provider:data.get("provider"), theme:data.get("theme"), text_scale:data.get("text_scale"), reduced_motion:data.get("reduced_motion") === "on", guided_introductions:data.get("guided_introductions") === "on" } }); if (!resultIsError(saved)) { applyPreferences(saved.settings); message.textContent = "Preferences saved."; } else message.textContent = saved.error.message; });
  document.querySelector("#openai").addEventListener("submit", async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const saved = await yellowBeast.configureOpenAI({ api_key:data.get("api_key"), model:data.get("model") || null }); message.textContent = saved.ok ? "Access key stored. It is never shown here again." : saved.error.message; if (saved.ok) settings(); });
}
function about() { requestGate.invalidate(); app.innerHTML = `<section class="shell narrow"><p class="eyebrow">ABOUT · ALPHA</p><h1>Yellow Beast</h1><p>A persistent, shared-world Backrooms experience. It works offline, with optional language assistance.</p><p>Worlds are saved in your application data folder; normal play never requires a terminal.</p>${button("Back", "home")}</section>`; }
document.addEventListener("click", async (event) => { const action = event.target.dataset.action; if (!action) return; if (action === "developer") { developerConsole(); return; } if (action === "home" || action === "leave") home(); else if (action === "new") newWorld(); else if (action === "import") { const imported = await yellowBeast.chooseImportWorld(); if (resultIsError(imported) && imported.error.code !== "IMPORT_CANCELLED") alert(imported.error.message); home(); } else if (action === "settings") settings(); else if (action === "about") about(); else if (action === "reset-preferences") { const saved = await yellowBeast.updateSettings({ settings:{ theme:"system", text_scale:"default", reduced_motion:false, guided_introductions:true } }); if (!resultIsError(saved)) applyPreferences(saved.settings); settings(); } else if (action === "refresh-view") { const context = requestContext(); const refreshed = await yellowBeast.getGameplayProjection({ world_id:context.worldId, mode:context.mode }); if (!resultIsError(refreshed) && requestContext().worldId === context.worldId && requestContext().mode === context.mode) { current.projection = refreshed.projection; play("Current view refreshed.", "result"); } } else if (action === "remove-key") { await yellowBeast.removeOpenAIKey(); settings(); } else if (action.startsWith("rename:")) { const worldId = action.slice(7); const prior = event.target.closest("li")?.dataset.worldName ?? ""; const name = prompt("Rename this world. This changes only its library name.", prior); if (name !== null) { const renamed = await yellowBeast.renameWorld({ world_id:worldId, name }); if (resultIsError(renamed)) alert(renamed.error.message); home(); } } else if (action.startsWith("restore:")) { const restored = await yellowBeast.restoreBackup({ world_id:action.slice(8), confirmed:confirm("Restore the previous save? Recent changes may be lost.") }); if (!resultIsError(restored)) selectWorld(action.slice(8)); else alert(restored.error.message); } else if (action.startsWith("export:")) { const result = await yellowBeast.chooseExportWorld({ world_id: action.slice(7) }); if (resultIsError(result) && result.error.code !== "EXPORT_CANCELLED") alert(result.error.message); } else if (action.startsWith("delete:")) { const worldId = action.slice(7); const name = event.target.closest("li")?.dataset.worldName ?? "this world"; if (confirm(`Delete “${name}” and its saved sessions? This cannot be undone.`)) { const deleted = await yellowBeast.deleteWorld({ world_id:worldId, confirmed:true }); if (resultIsError(deleted)) alert(deleted.error.message); home(); } } else if (action.startsWith("world:")) selectWorld(action.slice(6)); else if (action.startsWith("mode:")) enterMode(action.slice(5)); });
document.addEventListener("keydown", (event) => { if (!current.projection || event.target.matches("input, textarea, select, button")) return; const recap = document.querySelector("#recap-panel"); if (event.key === "?") { event.preventDefault(); recap.open = true; recap.querySelector("summary")?.focus({ preventScroll:true }); } else if (event.key === "Escape" && recap?.open) { event.preventDefault(); recap.open = false; focusNaturalInput(); } });
home();
