"use strict";
// Pure renderer helpers: input is already a safe desktop projection. No host
// APIs, world-history access, or inferred historical connections live here.
(function (global) {
  const escape = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;" })[char]);
  const title = (value) => String(value ?? "").replace(/[-_]/g, " ").replace(/\b\w/g, (x) => x.toUpperCase());
  const empty = (message) => `<p class="empty">${escape(message)}</p>`;
  const list = (items, render, message) => items?.length ? `<ul class="data-list">${items.map(render).join("")}</ul>` : empty(message);
  const panel = (heading, content, extra = "") => `<section class="panel" ${extra}><h2>${escape(heading)}</h2>${content}</section>`;
  const badge = (value) => `<span class="badge badge-${escape(String(value).toLowerCase())}">${escape(title(value))}</span>`;
  const callbacks = (projection) => projection.gameplay.callbacks?.length ? panel("Recognized callbacks", list(projection.gameplay.callbacks, (item) => `<li><strong>${escape(item.description)}</strong>${badge(item.recognition)}</li>`, "")) : "";
  const timeline = (projection, label = "Timeline") => projection.gameplay.timeline?.length ? panel(label, list(projection.gameplay.timeline, (item) => `<li>${escape(title(item.type))}${item.description ? ` — ${escape(item.description)}` : ""}</li>`, "")) : "";
  const objectives = (projection) => {
    const field = projection.surface.expedition?.objectives;
    const gameplay = projection.gameplay.objectives ?? [];
    const items = gameplay.map((item) => ({ label:item.type, state:item.status, kind:item.classification, detail:item.target }));
    if (field) items.push(...Object.entries(field).map(([name, item]) => ({ label:name, state:item.state, kind:item.required ? "primary" : "secondary", detail:"Field objective" })));
    return panel("Objectives", list(items, (item) => `<li><div><strong>${escape(title(item.label))}</strong><span>${escape(item.detail)}</span></div>${badge(item.kind)}${badge(item.state)}</li>`, "No objectives are currently known."), 'data-testid="objectives"');
  };
  const actionLabel = (type) => ({ LOOK:"Observe", MOVE:"Move", INSPECT:"Inspect", USE:"Use equipment", RECORD:"Record evidence", COMMUNICATE:"Communicate", WAIT:"Wait", RETURN:"Return", ABORT:"Abort mission", DROP:"Leave item", STRAND:"Stop and leave a remnant", EXPAND:"Explore route", DISCOVER:"Record object", REVIEW_REPORT:"Review reports", ADVANCE:"Advance institutional time" })[type] ?? title(type);
  const CAPABILITIES = Object.freeze({ "async-command": ["institution", "reports", "personnel", "research", "infrastructure", "tasks", "known-complex"], "field-researcher": ["objectives", "surroundings", "team", "communications", "evidence", "equipment", "risk", "known-route"], "local-anomaly": ["base", "archive", "artifacts", "questions", "routes", "preparation", "excursion"], lost: ["surroundings", "route-fragments", "landmarks", "resources", "notes"] });
  const actions = (projection) => panel("Available actions", projection.available_actions.length ? `<div class="action-grid">${projection.available_actions.map((item) => `<button type="button" class="action-button" data-game-action="${escape(item.type)}" data-testid="action-${escape(item.type)}">${escape(actionLabel(item.type))}</button>`).join("")}</div>` : empty("No action is available right now."), 'data-testid="actions"');
  function field(projection) { const state = projection.surface; const expedition = state.expedition ?? {}; const route = state.discovered_topology ?? {}; const risk = projection.gameplay.known_risk ?? [];
    return `<div class="mode-surface field-surface" data-testid="surface-clear-q4"><section class="hero"><p class="eyebrow">CLEAR-Q4 FIELD TERMINAL</p><h2>${escape(state.view?.location?.alias ?? "Current location unknown")}</h2><p>${escape(state.view?.location?.lighting ?? "Observe the surroundings before proceeding.")}</p></section><div class="surface-grid">${objectives(projection)}${panel("Surroundings", `<dl><dt>Visible targets</dt><dd>${escape((state.view?.targets ?? []).map((x) => x.alias).join(", ") || "Nothing notable")}</dd><dt>Unknown frontier</dt><dd>${escape((route.unknown_exits ?? []).join(", ") || "No unknown route visible")}</dd></dl>`, 'data-testid="field-surroundings"')}${panel("Known route", list([...(route.spaces ?? []), ...(route.connections ?? [])], (item) => `<li>${escape(item.alias ?? item.from ?? "known route")}</li>`, "Only the current position is known."), 'data-testid="field-route"')}${panel("Known risk", list(risk, (item) => `<li>${badge(item.level)}<span>${escape(item.factors?.join("; ") || "No additional known concerns.")}</span></li>`, "No elevated known risk is recorded."), 'data-testid="field-risk"')}${panel("Team", list(expedition.team, (member) => `<li><strong>${escape(title(member.role))}</strong>${badge(member.status)}</li>`, "No team status is available."), 'data-testid="field-team"')}${panel("Equipment", list(Object.entries(expedition.equipment ?? {}), ([name, item]) => `<li><strong>${escape(title(name))}</strong><span>${escape(`${item.charges} charges`)}</span>${badge(item.state)}</li>`, "No equipment data is available."), 'data-testid="field-equipment"')}${panel("Communications & evidence", `<p>Messages sent: ${escape(expedition.message_count ?? 0)} · Evidence recorded: ${escape(expedition.evidence_count ?? 0)}</p><p>Check-in interval: ${escape(expedition.clock?.interval ?? 0)}</p>`, 'data-testid="field-comms"')}${callbacks(projection)}${timeline(projection, "Mission history")}${actions(projection)}</div></div>`; }
  function beck(projection) { const inst = projection.institution ?? projection.surface; const overview = `<dl class="metrics"><div><dt>Institutional time</dt><dd>${escape(inst.logical_time ?? 0)}</dd></div><div><dt>Available budget</dt><dd>${escape(inst.budget?.available ?? 0)}</dd></div><div><dt>Pending tasks</dt><dd>${escape(inst.tasks?.length ?? 0)}</dd></div><div><dt>Active operations</dt><dd>${escape((inst.operations ?? []).filter((x) => x.status === "active").length)}</dd></div></dl>`;
    return `<div class="mode-surface beck-surface" data-testid="surface-beck"><section class="hero"><p class="eyebrow">ASYNC · BECK'S DESK</p><h2>Operations overview</h2>${overview}</section><div class="surface-grid desk-grid">${panel("Task tray", list(inst.tasks, (task) => `<li><div><strong>${escape(title(task.type ?? "institutional task"))}</strong><span>${escape(task.summary ?? task.context ?? "Action is available.")}</span></div>${badge(task.status ?? "pending")}</li>`, "No tasks are waiting."), 'data-testid="beck-tasks"')}${panel("Reports & communications", list([...(inst.inbox ?? []), ...(inst.communications ?? [])], (item) => `<li><strong>${escape(title(item.type ?? "report"))}</strong>${badge(item.lifecycle ?? item.status ?? "queued")}</li>`, "No reports are waiting."), 'data-testid="beck-reports"')}${panel("Personnel & teams", `${list(inst.personnel, (person) => `<li><strong>${escape(title(person.role))}</strong>${badge(person.status)}</li>`, "No personnel data.")}${list(inst.teams, (team) => `<li><strong>${escape(team.name ?? "Field team")}</strong><span>${escape(team.status ?? "known status pending")}</span></li>`, "No teams are currently assigned.")}`, 'data-testid="beck-personnel"')}${panel("Research", `<h3>Eligible</h3>${list(inst.research?.eligible, (item) => `<li>${escape(item.topic ?? item.id ?? "Research opportunity")}</li>`, "No research is eligible.")}<h3>Active</h3>${list(inst.research?.active, (item) => `<li>${escape(item.topic ?? item.id ?? "Research project")}</li>`, "No active research.")}<h3>Unlocks</h3>${list(inst.research?.unlocks, (item) => `<li>${escape(item.summary ?? item.type ?? "Operational capability")}</li>`, "No operational unlocks.")}`, 'data-testid="beck-research"')}${panel("Infrastructure", `${list(inst.infrastructure?.candidates, (item) => `<li>${escape(item.type ?? "Project candidate")}</li>`, "No proposed infrastructure.")}${list(inst.infrastructure?.projects, (item) => `<li><strong>${escape(item.type ?? "Project")}</strong>${badge(item.status)}</li>`, "No active or completed projects.")}`, 'data-testid="beck-infrastructure"')}${panel("Known Complex", `<p>Known regions: ${escape(inst.archive?.known_regions?.length ?? 0)}</p><p>Region summaries: ${escape(inst.archive?.region_summaries?.length ?? 0)}</p><p>Archived expeditions: ${escape(inst.archive?.expedition_count ?? 0)}</p>`, 'data-testid="beck-complex"')}${callbacks(projection)}${timeline(projection, "Institutional timeline")}${actions(projection)}</div></div>`; }
  function nullzone(projection) { const state = projection.surface; const base = state.base ?? {}; const excursion = state.current_excursion; return `<div class="mode-surface nullzone-surface" data-testid="surface-nullzone"><section class="hero"><p class="eyebrow">NULLZONE EXPOSURE</p><h2>${excursion ? "Excursion in progress" : "Personal base"}</h2><p>${excursion ? "Return with what you can justify carrying." : "A personal archive, not an institutional record."}</p></section><div class="surface-grid">${panel("Base & preparation", `<p>Access point: ${escape(base.known_access_point ?? "not established")}</p>${list(Object.entries(base.stored_equipment ?? {}), ([name, quantity]) => `<li><strong>${escape(title(name))}</strong><span>${escape(quantity)}</span></li>`, "No stored equipment.")}`, 'data-testid="nullzone-base"')}${panel("Personal archive", list(base.archived_artifacts, (item) => `<li><strong>${escape(title(item.type))}</strong><span>Archived observation</span></li>`, "No archived artifacts yet."), 'data-testid="nullzone-archive"')}${panel("Questions", list(state.investigation?.unresolved, (question) => `<li>${escape(title(question))}</li>`, "No unresolved questions."), 'data-testid="nullzone-questions"')}${panel("Route memory", list(excursion?.known_routes, (route) => `<li>${escape(route.alias ?? "known route")}</li>`, "No personal route is currently known."), 'data-testid="nullzone-routes"')}${panel("Current excursion", excursion ? `<p>Carried: ${escape(excursion.carried?.map(title).join(", ") || "nothing")}</p><p>Return remains a deliberate choice.</p>` : empty("Prepare an excursion to leave the base."), 'data-testid="nullzone-excursion"')}${panel("Known observation", state.local_observation ? `<p>${escape(state.local_observation.landmark?.description ?? "A local observation is available.")}</p>` : empty("No new local observation.") )}${callbacks(projection)}${timeline(projection, "Personal history")}${actions(projection)}</div></div>`; }
  function lost(projection) { const state = projection.surface; const around = state.surroundings ?? {}; return `<div class="mode-surface lost-surface" data-testid="surface-lost"><section class="lost-hero"><p class="eyebrow">LOST</p><h2>${escape(around.location?.alias ?? "Unknown place")}</h2><p>${escape(around.environment ? Object.values(around.environment).join(" · ") : "There is no wider map.")}</p></section><div class="lost-grid">${panel("Immediate surroundings", `<p>${escape(around.landmark?.description ?? "No landmark you can name.")}</p><p>Visible: ${escape([...(around.exits ?? []), ...(around.features ?? []), ...(around.objects ?? [])].map((item) => item.alias ?? item.kind).join(", ") || "nothing certain")}</p>`, 'data-testid="lost-surroundings"')}${panel("Route fragments", list([...(state.known_routes?.spaces ?? []), ...(state.known_routes?.connections ?? [])], (route) => `<li>${escape(route.alias ?? route.from ?? "remembered path")}</li>`, "No route beyond this place is known."), 'data-testid="lost-routes"')}${panel("What remains", `<p>Light charge: ${escape(state.status?.light_charge ?? 0)}</p>${list(state.status?.carried, (item) => `<li>${escape(title(item))}</li>`, "You are carrying nothing useful.")}`, 'data-testid="lost-resources"')}${state.run_notes?.length ? panel("Notes", list(state.run_notes, (note) => `<li>${escape(note)}</li>`, "")) : ""}${callbacks(projection)}${actions(projection)}</div></div>`; }
  const render = (projection) => ({ "async-command": beck, "field-researcher": field, "local-anomaly": nullzone, lost })[projection.mode.id]?.(projection) ?? empty("This role is not available.");
  const api = { render, actionLabel, title, CAPABILITIES };
  global.YBSurfaces = api;
  if (typeof module !== "undefined") module.exports = api;
})(typeof window === "undefined" ? globalThis : window);
