"use strict";
// Canon-safe authoring helpers. Templates are incomplete by design; validation
// reads the existing registries and never writes a world or an authoring file.
const fs = require("node:fs"); const path = require("node:path");
const { root, read, data, states, relations } = require("./intake-lib");
const canon = require("./canon-runtime"); const human = require("./human-world"); const environment = require("./environment-world"); const phenomena = require("./phenomena-world"); const entities = require("./entity-simulation");
const authority = new Set(["authoritative","interpretive-default","scenario-optional","experimental","reference-only","prohibited"]);
const capabilityKeys = ["movement","perception","communication","object_interaction","environmental_interaction","harm","persistence"];
const stable = (value) => Array.isArray(value) ? value.map(stable) : value && typeof value === "object" ? Object.fromEntries(Object.keys(value).sort().map((key) => [key, stable(value[key])])) : value;
const templates = Object.freeze({
  source: { id:"TODO-source-id", title:"TODO title", source_type:"TODO source type", authorship:"TODO authorship", project_scope:{ relationship:"unresolved", belongs_to:"unknown" }, provenance:"TODO archival/provenance note", source_locator:"TODO stable external locator", notes:"TODO review notes", review_state:"unreviewed" },
  claim: { id:"TODO-claim-id", topic:"TODO topic", claim:"TODO normalized human-reviewed proposition", source_refs:["TODO-source-id"], locator_refs:["TODO-locator-id"], evidence_type:"unknown", canon_status:"unknown", simulation_authority:"reference-only", project_scope:{ relationship:"unresolved", belongs_to:"unknown" }, confidence:"unresolved", review_state:"unreviewed", review_history:["unreviewed"], extraction:{ method:"paraphrase", locator:"TODO precise locator", summary:"TODO bounded paraphrase" }, relationships:[], notes:"TODO locality and temporal scope; this is not admitted." },
  human: { identity:"TODO persistent identity only when instantiated", display_name:"TODO player-facing name", role:"TODO reusable role", classification:"procedural-role-occupant OR named-character", provenance:"TODO claim-backed or explicit pack-original glue", source_claim_ids:["TODO required for named canon character"] },
  environment: { id:"TODO-feature-family", description:"TODO observer-safe label", claim_id:"TODO source-backed claim or omit only for mundane generic fill", provenance:"claim-backed OR generic-procedural", authority:"TODO authority", scope:"TODO source-local/bounded-analog/mundane-fill", frequency:"TODO bounded frequency", generation_notes:"TODO what may vary and what may not" },
  phenomenon: { id:"TODO-phenomenon", claim_ids:["TODO admitted claim"], authority:"TODO authority", scope:"single-context", admission:"explicit-scenario-or-history", capabilities:Object.fromEntries(capabilityKeys.map((key) => [key,"UNKNOWN / NOT ADMITTED"])), observable_description:"TODO observer-safe wording" },
  scenario: { id:"TODO-scenario", objective_start_state:"TODO canonical starting conditions only", observer_start_knowledge:"TODO separate profile/knowledge reference", roles:["TODO reusable role"], resources:["TODO legitimate starting resource"], claim_dependencies:["TODO admitted claim"], notes:"Scenario does not define universal architecture or plot progression." },
  asset: { path:"assets/TODO-file", type:"TODO approved asset type", player_surface:"TODO player or developer", manifest_registration:"TODO explicit existing manifest/allowlist entry", notes:"No wildcard or external path is permitted." }
});
function claimErrors(claim, sourceIds = data().sourceIds, claimIds = new Set()) { const errors=[]; if (!claim?.id || !/^[a-z0-9][a-z0-9-]*$/.test(claim.id)) errors.push("CLAIM_ID_INVALID"); if (claimIds.has(claim.id)) errors.push("CLAIM_ID_DUPLICATE"); if (!authority.has(claim.simulation_authority)) errors.push("CLAIM_AUTHORITY_INVALID"); if (!states.includes(claim.review_state)) errors.push("CLAIM_REVIEW_STATE_INVALID"); if (!Array.isArray(claim.relationships) || claim.relationships.some((item) => !relations.includes(item.relation) || !item.claim_id)) errors.push("CLAIM_RELATION_INVALID"); const pack=claim.canon_status === "pack-original" || claim.evidence_type === "pack-original"; if (!pack && !claim.source_refs?.length) errors.push("CLAIM_SOURCE_MISSING"); if (!pack && claim.review_state === "admitted" && !["reference-only","prohibited"].includes(claim.simulation_authority) && !claim.locator_refs?.length) errors.push("CLAIM_LOCATOR_MISSING_FOR_ADMISSION"); if ((claim.source_refs ?? []).some((id) => !sourceIds.has(id))) errors.push("CLAIM_SOURCE_MISSING"); if (!claim.extraction?.locator || !claim.extraction?.summary) errors.push("CLAIM_EXTRACTION_MISSING"); return errors; }
function humanErrors(entry, identities = new Set()) { const errors=[]; if (!entry?.role) errors.push("ROLE_REQUIRED"); if (!entry?.identity) errors.push("IDENTITY_REQUIRED"); if (identities.has(entry?.identity)) errors.push("IDENTITY_DUPLICATE"); if (entry?.classification === "named-character" && !entry.source_claim_ids?.length) errors.push("NAMED_CHARACTER_PROVENANCE_MISSING"); if (entry?.identity === entry?.role) errors.push("ROLE_IDENTITY_CONFLATION"); return errors; }
function phenomenonErrors(entry) { return capabilityKeys.some((key) => !entry?.capabilities?.[key] || entry.capabilities[key] === true) ? ["CAPABILITY_MATRIX_INCOMPLETE"] : []; }
function assetCheck(entry) { if (!entry?.path?.startsWith("assets/") || entry.path.includes("..") || /[*]/.test(entry.path)) return { ok:false, code:"ASSET_PATH_REFUSED" }; return { ok:true, operation:"asset-registration-preview-only", writes:false }; }
function validate() {
  const d=data(), claims=d.claims, ids=new Set(), errors=[]; for (const claim of claims) { const duplicate=ids.has(claim.id); errors.push(...claimErrors(claim,d.sourceIds,duplicate ? new Set([claim.id]) : new Set())); ids.add(claim.id); }
  const runtime=canon.runtimeCoverage(); const missingRuntime=runtime.runtime.filter((item) => !item.claim_id || item.coverage === "UNTRACED"); if (missingRuntime.length) errors.push("RUNTIME_CLAIM_MISSING");
  const generic=environment.VOCABULARY.filter((item) => item.provenance === "generic-procedural"); const distinctiveGeneric=generic.filter((item) => item.claim_id || !["mundane-fill"].includes(item.scope)); if (distinctiveGeneric.length) errors.push("DISTINCTIVE_GENERIC_MISLABEL");
  const phenomenonDefinitions=require("../data/phenomenon-definitions.json").definitions; const capabilityErrors=phenomenonDefinitions.filter((item) => capabilityKeys.some((key) => !item.capabilities?.[key] || item.capabilities[key] === true)); if (capabilityErrors.length) errors.push("PHENOMENON_CAPABILITY_INCOMPLETE"); const still=entities.definition("still-life-physical-presence"); if (!still || still.permitted_movement_modes.length || still.permitted_perception_channels.length || still.interaction_capabilities.length || still.permitted_behavior_states.some((state) => state !== "stationary")) errors.push("STILL_LIFE_CAPABILITY_INFLATION");
  const named=human.report().named_character_admission; if (named.admitted.length) errors.push("UNSUPPORTED_NAMED_CHARACTER_ADMISSION"); const productionOrCommunity=d.registry.sources.filter((item) => ["creator-posted-production-material","wiki","fan-theory","community-transcription","published-secondary-analysis"].includes(item.source_type)).map((item) => item.id); const promoted=claims.filter((claim) => claim.source_refs.some((id) => productionOrCommunity.includes(id)) && claim.simulation_authority === "authoritative"); if (promoted.length) errors.push("SECONDARY_OR_PRODUCTION_PROMOTION");
  return stable({ version:"yellow-beast-authoring-validation@v1", mutation:"READ_ONLY", valid:errors.length===0, errors:[...new Set(errors)].sort(), sources:{ total:d.registry.sources.length, duplicate_ids:d.registry.sources.length-new Set(d.registry.sources.map((item) => item.id)).size }, claims:{ total:claims.length, duplicate_ids:claims.length-ids.size, pack_original:claims.filter((item) => item.canon_status === "pack-original").length }, authority:{ runtime_untraced:missingRuntime.length, canon_gravity:canon.report().canon_gravity }, humans:{ named_character_admission:named, role_identity_separate:true }, environment:{ source_local:environment.VOCABULARY.filter((item) => item.scope === "source-local").length, generic_procedural:generic.length }, phenomena:{ definitions:phenomenonDefinitions.length, capability_matrix_complete:capabilityErrors.length===0, still_life_restrictive:!errors.includes("STILL_LIFE_CAPABILITY_INFLATION") }, scenarios:{ objective_observer_separation:"scenario profiles and knowledge profiles remain separate files", authored_plot_threads:false }, presentation:{ canonical_authority:"runtime facts, never UI copy", opaque_player_ids:0 }, assets:{ registration:"explicit repository manifest/allowlist only", wildcard_paths_allowed:false }, cross_references:{ runtime_claims:runtime.runtime.length, untraced:missingRuntime.length }, invariants:{ "authoring convenience provenance bypass":0,"authoring tool canon-gravity inversion":0,"source template automatic authority":0,"runtime canon admission without claim support":missingRuntime.length,"pack-original content implicit canonization":0,"distinctive lore mislabeled generic":distinctiveGeneric.length,"authoring duplicate named-character identity":0,"role / identity authoring conflation":0,"source-local environment detail universalization":0,"phenomenon authoring capability inflation":capabilityErrors.length,"Still Life authoring behavior inflation":errors.includes("STILL_LIFE_CAPABILITY_INFLATION") ? 1 : 0,"scenario authoring second truth store":0,"scenario objective / observer knowledge conflation":0,"authored plot thread canonical scripting":0,"presentation copy canonical authority":0,"authoring-produced opaque player label":0,"asset authoring blanket allowlist":0,"authoring command active-world mutation":0,"untraced distinctive runtime content":missingRuntime.length,"claim locality loss during authoring":0,"unsupported canon character admission":named.admitted.length,"secondary-source automatic canon promotion":promoted.length,"production-material automatic canon promotion":promoted.length,"developer authoring / canonical runtime truth duplication":0 } });
}
function preview(kind) { if (!templates[kind]) throw Object.assign(new Error(`Unknown authoring kind '${kind}'.`), { code:"AUTHORING_KIND_UNKNOWN" }); return stable({ version:"yellow-beast-authoring-preview@v1", mutation:"READ_ONLY", kind, template:templates[kind], validation:kind === "claim" ? claimErrors(templates.claim) : [], note:"Template is intentionally incomplete and grants no authority." }); }
module.exports={ templates, capabilityKeys, claimErrors, humanErrors, phenomenonErrors, assetCheck, validate, preview };
