"use strict";

const crypto = require("node:crypto");
const history = require("./world-history");
const clone = (value) => structuredClone(value);
const hash = (value) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
const VERSION = "yellow-beast-becks-desk@v2";
const PROCESS_VERSION = "yellow-beast-institution-process@v1";
const PERSONNEL = [{ id: "personnel-field-1", role: "field-researcher" }, { id: "personnel-field-2", role: "field-researcher" }, { id: "personnel-engineer-1", role: "engineer" }, { id: "personnel-doctor-1", role: "doctor" }, { id: "personnel-researcher-1", role: "researcher" }];
const processId = (world, type, origin) => `institution-process-${hash([world.world_id, type, origin]).slice(0, 16)}`;
function managementEvent(world, run_id, type, payload) { return history.event(world, run_id, `management.${type}`, payload, "pack-original-management-simulation"); }
function institutionEvent(world, run_id, type, payload) { return history.event(world, run_id, `institution.${type}`, payload, "pack-original-institutional-simulation"); }
function state(world) {
  history.assertWorld(world);
  if (!world.management) world.management = { version: VERSION, tick: 0, clock: { logical_time: 0 }, budget: { available: 12, committed: 0, spent: 0 }, personnel: Object.fromEntries(PERSONNEL.map((person) => [person.id, { ...person, status: person.id === "personnel-field-2" ? "recovering" : "available", assignment: null }])), resources: { radio: { available: 2, allocated: 0 }, "survey-kit": { available: 2, allocated: 0 }, "medical-kit": { available: 1, allocated: 0 }, "construction-material": { available: 2, allocated: 0 } }, teams: {}, operations: {}, processes: {}, research: { priority: null, progress: 0 }, infrastructure: {}, reports: [] };
  const s = world.management; s.version ??= VERSION; s.clock ??= { logical_time: s.tick ?? 0 }; s.processes ??= {}; for (const team of Object.values(s.teams)) team.knowledge ??= { routes: [], landmarks: [], hazards: [], received_messages: [] }; return s;
}
function knownRegionSummary(world, region_id) { return world.knowledge.institutional.records[`institutional-region-summary-${region_id}`]?.payload.summary ?? null; }
function processView(process) { return { id: process.id, type: process.type, status: process.status, phase: process.phase, team_id: process.team_id, region_id: process.region_id, started_at: process.started_at, dependencies: clone(process.dependencies) }; }
function projection(world) {
  const s = state(world); const region_summaries = Object.values(world.knowledge.institutional.records).filter((record) => record.id.startsWith("institutional-region-summary-")).map((record) => ({ region_id: record.payload.region_id, summary: clone(record.payload.summary) }));
  return { version: "yellow-beast-institution-projection@v1", logical_time: s.clock.logical_time, operations: Object.values(s.operations).map(({ id, status, team_id, last_report, process_id }) => ({ id, status, team_id, last_report, process_id })), processes: Object.values(s.processes).map(processView), personnel: Object.values(s.personnel).map(({ id, role, status, assignment }) => ({ id, role, status, assignment })), resources: clone(s.resources), budget: clone(s.budget), research: clone(s.research), infrastructure: Object.values(s.infrastructure).map(({ id, type, status, region_id, progress }) => ({ id, type, status, region_id, progress })), archive: { known_regions: history.knownRegions(world, "async-command"), region_summaries, expedition_count: Object.values(world.runs).filter((run) => run.expedition_id).length }, inbox: s.reports.filter((report) => report.status === "delivered" || report.status === "reviewed").map(({ operation_id, status, summary }) => ({ operation_id, status, summary })), reports: s.reports.map(({ operation_id, status, summary }) => ({ operation_id, status, summary })) };
}
function createTeam(world, run_id, { id, members }) {
  const s = state(world); if (s.teams[id]) return { ok: false, code: "TEAM_EXISTS" };
  if (!Array.isArray(members) || !members.length || members.some((person) => !s.personnel[person] || s.personnel[person].status !== "available" || s.personnel[person].assignment)) return { ok: false, code: "PERSONNEL_UNAVAILABLE" };
  for (const person of members) { s.personnel[person].assignment = id; s.personnel[person].status = "assigned"; }
  s.teams[id] = { id, members, status: "ready", equipment: {}, knowledge: { routes: [], landmarks: [], hazards: [], received_messages: [] } }; managementEvent(world, run_id, "team.created", { id, members }); return { ok: true, team: clone(s.teams[id]) };
}
function allocate(world, run_id, { team_id, resource, quantity = 1 }) { const s = state(world); const team = s.teams[team_id]; const item = s.resources[resource]; if (!team || !item || quantity < 1 || item.available < quantity) return { ok: false, code: "RESOURCE_UNAVAILABLE" }; item.available -= quantity; item.allocated += quantity; team.equipment[resource] = (team.equipment[resource] ?? 0) + quantity; managementEvent(world, run_id, "resource.allocated", { team_id, resource, quantity }); return { ok: true }; }
function createProcess(world, run_id, { type, origin, team_id = null, region_id = null, objective = null, dependencies = [], known_inputs = {} }) {
  const s = state(world); const id = processId(world, type, origin); if (s.processes[id]) return { ok: true, idempotent: true, process: clone(s.processes[id]) };
  const process = { id, version: PROCESS_VERSION, type, origin, world_id: world.world_id, team_id, region_id, objective, status: "preparing", phase: "deploy", started_at: s.clock.logical_time, dependencies: clone(dependencies), known_inputs: clone(known_inputs), completion: null };
  s.processes[id] = process; institutionEvent(world, run_id, "process_created", { process_id: id, type, team_id, region_id, objective, logical_time: s.clock.logical_time }); return { ok: true, process: clone(process) };
}
function dispatch(world, run_id, { id, team_id, region_id, objective = "survey" }) {
  const s = state(world); const team = s.teams[team_id]; if (s.operations[id]) return { ok: false, code: "OPERATION_EXISTS" };
  const summary = knownRegionSummary(world, region_id); if (!team || team.status !== "ready" || !history.knownRegions(world, "async-command").some((entry) => entry.region_id === region_id) || s.budget.available < 2) return { ok: false, code: "OPERATION_UNAVAILABLE" };
  s.budget.available -= 2; s.budget.committed += 2; team.status = "deployed"; team.knowledge = { routes: ["approved-known-entry"], landmarks: clone(summary?.landmarks ?? []), hazards: [], received_messages: [] }; for (const member of team.members) s.personnel[member].status = "deployed";
  const created = createProcess(world, run_id, { type: "expedition", origin: id, team_id, region_id, objective, known_inputs: { region_summary: summary ? clone(summary) : null } });
  s.operations[id] = { id, team_id, region_id, objective, status: "dispatched", order_status: "issued", process_id: created.process.id, last_report: null };
  managementEvent(world, run_id, "operation.dispatched", { id, team_id, region_id, objective }); institutionEvent(world, run_id, "team_dispatched", { team_id, operation_id: id, process_id: created.process.id, region_id }); return { ok: true, operation: clone(s.operations[id]) };
}
function recall(world, run_id, id) { const op = state(world).operations[id]; if (!op || !["dispatched", "active"].includes(op.status)) return { ok: false, code: "OPERATION_UNAVAILABLE" }; op.order_status = "recall-requested"; managementEvent(world, run_id, "recall.issued", { operation_id: id }); return { ok: true, public_reason: "recall requested" }; }
function report(s, operation, status, summary, logical_time) { const item = { id: `institution-report-${operation.id}-${s.reports.length + 1}`, operation_id: operation.id, process_id: operation.process_id, status, summary, created_at: logical_time, delivered_at: status === "delivered" ? logical_time : null }; s.reports.push(item); operation.last_report = { status, summary }; return item; }
function releaseTeam(s, team) { team.status = "ready"; for (const member of team.members) { const person = s.personnel[member]; person.status = "available"; person.assignment = null; } for (const key of Object.keys(team.equipment)) { s.resources[key].allocated -= team.equipment[key]; s.resources[key].available += team.equipment[key]; } team.equipment = {}; }
function progressExpedition(world, run_id, s, process) {
  const operation = Object.values(s.operations).find((item) => item.process_id === process.id); const team = s.teams[process.team_id]; if (!operation || !team) return;
  if (process.status === "preparing") { process.status = "active"; process.phase = "travel"; operation.status = "active"; report(s, operation, "delayed", "Team entered the institutionally known route; field findings await transmission.", s.clock.logical_time); managementEvent(world, run_id, "report.delayed", { operation_id: operation.id }); institutionEvent(world, run_id, "process_advanced", { process_id: process.id, status: process.status, phase: process.phase }); return; }
  if (process.status === "active" && operation.order_status === "recall-requested") { process.status = "returning"; process.phase = "withdraw"; operation.status = "returning"; report(s, operation, "delivered", "Recall acknowledged; return pending.", s.clock.logical_time); managementEvent(world, run_id, "report.archived", { operation_id: operation.id, status: "returning" }); institutionEvent(world, run_id, "process_advanced", { process_id: process.id, status: process.status, phase: process.phase }); return; }
  if (process.status === "active" && process.phase === "travel") { process.phase = "survey"; report(s, operation, "transmitted", "Team completed a bounded observation at the approved known entry.", s.clock.logical_time); institutionEvent(world, run_id, "process_advanced", { process_id: process.id, status: process.status, phase: process.phase }); return; }
  if (process.status === "active" && process.phase === "survey") { process.status = "returning"; process.phase = "return"; operation.status = "returning"; const message = s.reports.find((item) => item.operation_id === operation.id && item.status === "transmitted"); if (message) { message.status = "delivered"; message.delivered_at = s.clock.logical_time; operation.last_report = { status: "delivered", summary: message.summary }; institutionEvent(world, run_id, "report_received", { report_id: message.id, operation_id: operation.id, process_id: process.id }); } institutionEvent(world, run_id, "process_advanced", { process_id: process.id, status: process.status, phase: process.phase }); return; }
  if (process.status === "returning") { process.status = "completed"; process.phase = "complete"; process.completion = { logical_time: s.clock.logical_time, outcome: "returned" }; operation.status = "completed"; releaseTeam(s, team); s.budget.committed -= 2; s.budget.spent += 2; managementEvent(world, run_id, "report.archived", { operation_id: operation.id, status: "completed" }); institutionEvent(world, run_id, "process_completed", { process_id: process.id, operation_id: operation.id, logical_time: s.clock.logical_time }); }
}
function advance(world, run_id) {
  const s = state(world); s.tick += 1; s.clock.logical_time += 1; institutionEvent(world, run_id, "time_advanced", { logical_time: s.clock.logical_time });
  for (const person of Object.values(s.personnel)) if (person.status === "recovering") { person.status = "available"; managementEvent(world, run_id, "personnel.recovered", { personnel_id: person.id }); }
  for (const process of Object.values(s.processes).sort((a, b) => a.id.localeCompare(b.id))) if (process.type === "expedition" && !["completed", "failed", "cancelled"].includes(process.status)) progressExpedition(world, run_id, s, process);
  if (s.research.priority) s.research.progress += 1;
  for (const project of Object.values(s.infrastructure)) if (project.status === "under-construction") { project.progress += 1; if (project.progress >= 2) { project.status = "operational"; managementEvent(world, run_id, "infrastructure.operational", { project_id: project.id }); } }
  return { ok: true, tick: s.tick, logical_time: s.clock.logical_time };
}
function prioritize(world, run_id, topic) { const s = state(world); if (!Object.keys(history.knownRegions(world, "async-command")).length && !["architecture", "recovered-evidence"].includes(topic)) return { ok: false, code: "PRIORITY_UNAVAILABLE" }; s.research.priority = topic; managementEvent(world, run_id, "research.prioritized", { topic }); return { ok: true }; }
function buildOutpost(world, run_id, { id, region_id }) { const s = state(world); if (s.infrastructure[id] || !history.knownRegions(world, "async-command").some((entry) => entry.region_id === region_id) || s.resources["construction-material"].available < 1 || s.budget.available < 3 || !Object.values(s.personnel).some((person) => person.role === "engineer" && person.status === "available")) return { ok: false, code: "PROJECT_UNAVAILABLE" }; s.resources["construction-material"].available -= 1; s.resources["construction-material"].allocated += 1; s.budget.available -= 3; s.budget.committed += 3; s.infrastructure[id] = { id, type: "survey-outpost", region_id, status: "under-construction", progress: 0, provenance: "pack-original-infrastructure" }; managementEvent(world, run_id, "infrastructure.started", { id, region_id, type: "survey-outpost" }); return { ok: true }; }
function managementResult(world) { const s = state(world); return { version: s.version, logical_time: s.clock.logical_time, operations: clone(s.operations), processes: clone(s.processes), resources: clone(s.resources), budget: clone(s.budget), research: clone(s.research), infrastructure: clone(s.infrastructure), reports: clone(s.reports) }; }
module.exports = { VERSION, PROCESS_VERSION, state, projection, createTeam, allocate, createProcess, dispatch, recall, advance, prioritize, buildOutpost, managementResult };
