"use strict";

const crypto = require("node:crypto");
const history = require("./world-history");
const clone = (value) => structuredClone(value);
const hash = (value) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
const VERSION = "yellow-beast-becks-desk@v2";
const PROCESS_VERSION = "yellow-beast-institution-process@v1";
const PERSONNEL = [{ id: "personnel-field-1", role: "field-researcher" }, { id: "personnel-field-2", role: "field-researcher" }, { id: "personnel-engineer-1", role: "engineer" }, { id: "personnel-doctor-1", role: "doctor" }, { id: "personnel-researcher-1", role: "researcher" }];
const processId = (world, type, origin) => `institution-process-${hash([world.world_id, type, origin]).slice(0, 16)}`;
function managementEvent(world, run_id, type, payload) { return history.event(world, run_id, `management.${type}`, payload, "pack-original-management-simulation"); }
function institutionEvent(world, run_id, type, payload) { return history.event(world, run_id, `institution.${type}`, payload, "pack-original-institutional-simulation"); }
function state(world) {
  history.assertWorld(world);
  if (!world.management) world.management = { version: VERSION, tick: 0, clock: { logical_time: 0 }, budget: { available: 12, committed: 0, spent: 0 }, personnel: Object.fromEntries(PERSONNEL.map((person) => [person.id, { ...person, status: person.id === "personnel-field-2" ? "recovering" : "available", known_status: person.id === "personnel-field-2" ? "recovering" : "available", assignment: null, recovery_process_id: null }])), resources: { radio: { available: 2, allocated: 0, deployed: 0, lost: 0, recoverable: 0, recovered: 0 }, "survey-kit": { available: 2, allocated: 0, deployed: 0, lost: 0, recoverable: 0, recovered: 0 }, "medical-kit": { available: 1, allocated: 0, deployed: 0, lost: 0, recoverable: 0, recovered: 0 }, "construction-material": { available: 2, allocated: 0, deployed: 0, lost: 0, recoverable: 0, recovered: 0 } }, teams: {}, operations: {}, processes: {}, research: { priority: null, progress: 0 }, infrastructure: {}, reports: [], incidents: {} };
  const s = world.management; s.version ??= VERSION; s.clock ??= { logical_time: s.tick ?? 0 }; s.processes ??= {}; s.incidents ??= {}; for (const person of Object.values(s.personnel)) { person.known_status ??= person.status; person.recovery_process_id ??= null; } for (const resource of Object.values(s.resources)) { resource.deployed ??= 0; resource.lost ??= 0; resource.recoverable ??= 0; resource.recovered ??= 0; } for (const team of Object.values(s.teams)) team.knowledge ??= { routes: [], landmarks: [], hazards: [], received_messages: [] }; return s;
}
function knownRegionSummary(world, region_id) { return world.knowledge.institutional.records[`institutional-region-summary-${region_id}`]?.payload.summary ?? null; }
function processView(process) { return { id: process.id, type: process.type, status: process.known_status ?? process.status, phase: process.phase, team_id: process.team_id, region_id: process.region_id, started_at: process.started_at, dependencies: clone(process.dependencies) }; }
function projection(world) {
  const s = state(world); const region_summaries = Object.values(world.knowledge.institutional.records).filter((record) => record.id.startsWith("institutional-region-summary-")).map((record) => ({ region_id: record.payload.region_id, summary: clone(record.payload.summary) }));
  return { version: "yellow-beast-institution-projection@v1", logical_time: s.clock.logical_time, operations: Object.values(s.operations).map(({ id, status, known_status, team_id, last_report, process_id }) => ({ id, status: known_status ?? status, team_id, last_report, process_id })), processes: Object.values(s.processes).map(processView), personnel: Object.values(s.personnel).map(({ id, role, known_status, assignment }) => ({ id, role, status: known_status, assignment })), resources: Object.fromEntries(Object.entries(s.resources).map(([key, value]) => [key, { available: value.available, allocated: value.allocated, deployed: value.deployed, lost: value.lost, recoverable: value.recoverable, recovered: value.recovered }])), budget: clone(s.budget), research: clone(s.research), infrastructure: Object.values(s.infrastructure).map(({ id, type, status, region_id, progress }) => ({ id, type, status, region_id, progress })), archive: { known_regions: history.knownRegions(world, "async-command"), region_summaries, expedition_count: Object.values(world.runs).filter((run) => run.expedition_id).length }, inbox: s.reports.filter((report) => report.lifecycle === "delivered" || report.lifecycle === "reviewed").map(({ operation_id, status, summary, lifecycle }) => ({ operation_id, status, lifecycle, summary })), communications: s.reports.map(({ operation_id, status, lifecycle, summary }) => ({ operation_id, status, lifecycle, summary })), incidents: Object.values(s.incidents).map(({ id, category, summary, status, logical_time }) => ({ id, category, summary, status, logical_time })), recovery: Object.values(s.processes).filter((process) => process.type === "recovery").map(processView) };
}
function createTeam(world, run_id, { id, members }) {
  const s = state(world); if (s.teams[id]) return { ok: false, code: "TEAM_EXISTS" };
  if (!Array.isArray(members) || !members.length || members.some((person) => !s.personnel[person] || s.personnel[person].status !== "available" || s.personnel[person].assignment)) return { ok: false, code: "PERSONNEL_UNAVAILABLE" };
  for (const person of members) { s.personnel[person].assignment = id; s.personnel[person].status = "assigned"; s.personnel[person].known_status = "assigned"; }
  s.teams[id] = { id, members, status: "ready", equipment: {}, knowledge: { routes: [], landmarks: [], hazards: [], received_messages: [] } }; managementEvent(world, run_id, "team.created", { id, members }); return { ok: true, team: clone(s.teams[id]) };
}
function allocate(world, run_id, { team_id, resource, quantity = 1 }) { const s = state(world); const team = s.teams[team_id]; const item = s.resources[resource]; if (!team || !item || quantity < 1 || item.available < quantity) return { ok: false, code: "RESOURCE_UNAVAILABLE" }; item.available -= quantity; item.allocated += quantity; team.equipment[resource] = (team.equipment[resource] ?? 0) + quantity; managementEvent(world, run_id, "resource.allocated", { team_id, resource, quantity }); return { ok: true }; }
function createProcess(world, run_id, { type, origin, team_id = null, region_id = null, objective = null, dependencies = [], known_inputs = {} }) {
  const s = state(world); const id = processId(world, type, origin); if (s.processes[id]) return { ok: true, idempotent: true, process: clone(s.processes[id]) };
  const process = { id, version: PROCESS_VERSION, type, origin, world_id: world.world_id, team_id, region_id, objective, status: "preparing", known_status: "preparing", phase: "deploy", started_at: s.clock.logical_time, dependencies: clone(dependencies), known_inputs: clone(known_inputs), completion: null };
  s.processes[id] = process; institutionEvent(world, run_id, "process_created", { process_id: id, type, team_id, region_id, objective, logical_time: s.clock.logical_time }); return { ok: true, process: clone(process) };
}
function dispatch(world, run_id, { id, team_id, region_id, objective = "survey" }) {
  const s = state(world); const team = s.teams[team_id]; if (s.operations[id]) return { ok: false, code: "OPERATION_EXISTS" };
  const summary = knownRegionSummary(world, region_id); if (!team || team.status !== "ready" || !history.knownRegions(world, "async-command").some((entry) => entry.region_id === region_id) || s.budget.available < 2) return { ok: false, code: "OPERATION_UNAVAILABLE" };
  s.budget.available -= 2; s.budget.committed += 2; team.status = "deployed"; team.knowledge = { routes: ["approved-known-entry"], landmarks: clone(summary?.landmarks ?? []), hazards: [], received_messages: [] }; for (const [resource, quantity] of Object.entries(team.equipment)) { s.resources[resource].allocated -= quantity; s.resources[resource].deployed += quantity; } for (const member of team.members) { s.personnel[member].status = "deployed"; s.personnel[member].known_status = "deployed"; }
  const created = createProcess(world, run_id, { type: "expedition", origin: id, team_id, region_id, objective, known_inputs: { region_summary: summary ? clone(summary) : null } });
  s.operations[id] = { id, team_id, region_id, objective, status: "dispatched", known_status: "dispatched", order_status: "issued", process_id: created.process.id, last_report: null };
  managementEvent(world, run_id, "operation.dispatched", { id, team_id, region_id, objective }); institutionEvent(world, run_id, "team_dispatched", { team_id, operation_id: id, process_id: created.process.id, region_id }); return { ok: true, operation: clone(s.operations[id]) };
}
function recall(world, run_id, id) { const op = state(world).operations[id]; if (!op || !["dispatched", "active"].includes(op.status)) return { ok: false, code: "OPERATION_UNAVAILABLE" }; op.order_status = "recall-requested"; managementEvent(world, run_id, "recall.issued", { operation_id: id }); return { ok: true, public_reason: "recall requested" }; }
function report(s, operation, status, summary, logical_time, facts = {}) { const item = { id: `institution-report-${operation.id}-${s.reports.length + 1}`, operation_id: operation.id, process_id: operation.process_id, team_id: operation.team_id, origin_run: null, intended_recipient: "institution", status, lifecycle: status === "delivered" ? "delivered" : status === "transmitted" ? "queued" : "created", summary, facts: clone(facts), created_at: logical_time, transmission_at: null, delivered_at: status === "delivered" ? logical_time : null, reviewed_at: null, provenance: "pack-original-institutional-simulation", authority: "scenario-optional" }; s.reports.push(item); operation.last_report = { status, summary }; return item; }
function releaseTeam(s, team) { team.status = "ready"; for (const member of team.members) { const person = s.personnel[member]; if (person.status !== "unavailable") { person.status = "available"; person.known_status = "available"; person.assignment = null; } } for (const [key, quantity] of Object.entries(team.equipment)) { const resource = s.resources[key]; resource.deployed -= quantity; resource.available += quantity; } team.equipment = {}; }
function progressExpedition(world, run_id, s, process) {
  const operation = Object.values(s.operations).find((item) => item.process_id === process.id); const team = s.teams[process.team_id]; if (!operation || !team) return;
  if (process.status === "preparing") { process.status = "active"; process.known_status = "active"; process.phase = "travel"; operation.status = "active"; operation.known_status = "active"; report(s, operation, "delayed", "Team entered the institutionally known route; field findings await transmission.", s.clock.logical_time); managementEvent(world, run_id, "report.delayed", { operation_id: operation.id }); institutionEvent(world, run_id, "process_advanced", { process_id: process.id, status: process.status, phase: process.phase }); return; }
  if (process.status === "active" && operation.order_status === "recall-requested") { process.status = "returning"; process.known_status = "returning"; process.phase = "withdraw"; operation.status = "returning"; operation.known_status = "returning"; report(s, operation, "delivered", "Recall acknowledged; return pending.", s.clock.logical_time); managementEvent(world, run_id, "report.archived", { operation_id: operation.id, status: "returning" }); institutionEvent(world, run_id, "process_advanced", { process_id: process.id, status: process.status, phase: process.phase }); return; }
  if (process.status === "active" && process.phase === "travel") { process.phase = "survey"; report(s, operation, "transmitted", "Team completed a bounded observation at the approved known entry.", s.clock.logical_time); institutionEvent(world, run_id, "process_advanced", { process_id: process.id, status: process.status, phase: process.phase }); return; }
  if (process.status === "active" && process.phase === "survey") { process.status = "returning"; process.known_status = "returning"; process.phase = "return"; operation.status = "returning"; operation.known_status = "returning"; institutionEvent(world, run_id, "process_advanced", { process_id: process.id, status: process.status, phase: process.phase }); return; }
  if (process.status === "returning") { process.status = "completed"; process.known_status = "completed"; process.phase = "complete"; process.completion = { logical_time: s.clock.logical_time, outcome: "returned" }; operation.status = "completed"; operation.known_status = "completed"; releaseTeam(s, team); s.budget.committed -= 2; s.budget.spent += 2; managementEvent(world, run_id, "report.archived", { operation_id: operation.id, status: "completed" }); institutionEvent(world, run_id, "process_completed", { process_id: process.id, operation_id: operation.id, logical_time: s.clock.logical_time }); }
}
function admitReport(world, run_id, s, report) { if (report.lifecycle === "reviewed") return; report.lifecycle = "reviewed"; report.reviewed_at = s.clock.logical_time; institutionEvent(world, run_id, "report_reviewed", { report_id: report.id, process_id: report.process_id, logical_time: s.clock.logical_time }); if (report.facts?.incident) { const id = `institution-incident-${hash([world.world_id, report.id]).slice(0, 16)}`; if (!s.incidents[id]) { s.incidents[id] = { id, source_report_id: report.id, category: report.facts.incident, summary: report.summary, status: "open", logical_time: s.clock.logical_time, known_facts: clone(report.facts.known_facts ?? {}), recovery_eligible: Boolean(report.facts.recovery) }; institutionEvent(world, run_id, "incident_created", { incident_id: id, report_id: report.id, category: report.facts.incident, logical_time: s.clock.logical_time }); } const process = s.processes[report.process_id]; if (process) { process.known_status = process.status; const operation = Object.values(s.operations).find((item) => item.process_id === process.id); if (operation) operation.known_status = operation.status; } for (const personId of report.facts.personnel ?? []) if (s.personnel[personId]) s.personnel[personId].known_status = s.personnel[personId].status; }
}
function advanceCommunications(world, run_id, s) { for (const item of s.reports.sort((a, b) => a.id.localeCompare(b.id))) { if (item.lifecycle === "created") { item.lifecycle = "queued"; institutionEvent(world, run_id, "report_queued", { report_id: item.id, logical_time: s.clock.logical_time }); } else if (item.lifecycle === "queued") { item.lifecycle = "transmitting"; item.transmission_at = s.clock.logical_time; institutionEvent(world, run_id, "report_transmitting", { report_id: item.id, logical_time: s.clock.logical_time }); } else if (item.lifecycle === "transmitting") { item.lifecycle = "delivered"; item.status = "delivered"; item.delivered_at = s.clock.logical_time; institutionEvent(world, run_id, "report_received", { report_id: item.id, process_id: item.process_id, logical_time: s.clock.logical_time }); } else if (item.lifecycle === "delivered") admitReport(world, run_id, s, item); } }
function applyFieldConsequence(world, run_id, { operation_id, personnel_id = null, resource = null, consequence = "incapacitated", summary = "Field team reported a mission disruption." }) {
  const s = state(world); const operation = s.operations[operation_id]; const process = operation && s.processes[operation.process_id]; if (!operation || !process || !["active", "returning"].includes(process.status)) return { ok: false, code: "PROCESS_UNAVAILABLE" };
  const known_facts = { consequence }; if (personnel_id) { const person = s.personnel[personnel_id]; if (!person || !s.teams[operation.team_id].members.includes(personnel_id)) return { ok: false, code: "PERSONNEL_UNAVAILABLE" }; person.status = "unavailable"; person.recovery_process_id = null; known_facts.personnel_status = "unavailable"; }
  if (resource) { const item = s.resources[resource]; const quantity = s.teams[operation.team_id].equipment[resource] ?? 0; if (!item || quantity < 1) return { ok: false, code: "RESOURCE_UNAVAILABLE" }; item.deployed -= quantity; item.lost += quantity; item.recoverable += quantity; delete s.teams[operation.team_id].equipment[resource]; known_facts.equipment = "recoverable-loss"; }
  process.status = "failed"; process.phase = "failed"; process.completion = { logical_time: s.clock.logical_time, outcome: consequence }; operation.status = "failed"; const created = report(s, operation, "delayed", summary, s.clock.logical_time, { incident: consequence, personnel: personnel_id ? [personnel_id] : [], recovery: Boolean(personnel_id || resource), known_facts, resource }); institutionEvent(world, run_id, "process_failed", { process_id: process.id, operation_id, consequence, logical_time: s.clock.logical_time }); return { ok: true, report_id: created.id };
}
function approveRecovery(world, run_id, { incident_id, team_id }) { const s = state(world); const incident = s.incidents[incident_id]; const team = s.teams[team_id]; if (!incident?.recovery_eligible || !team || team.status !== "ready" || s.budget.available < 1) return { ok: false, code: "RECOVERY_UNAVAILABLE" }; const report = s.reports.find((item) => item.id === incident.source_report_id); const source = report && s.processes[report.process_id]; if (!source) return { ok: false, code: "RECOVERY_UNAVAILABLE" }; s.budget.available -= 1; s.budget.committed += 1; team.status = "deployed"; for (const member of team.members) { s.personnel[member].status = "deployed"; s.personnel[member].known_status = "deployed"; } const created = createProcess(world, run_id, { type: "recovery", origin: incident_id, team_id, region_id: source.region_id, objective: "recovery", dependencies: [incident_id], known_inputs: { last_known_region: source.region_id, known_facts: clone(incident.known_facts) } }); incident.status = "recovery-approved"; institutionEvent(world, run_id, "recovery_requested", { process_id: created.process.id, incident_id, team_id, logical_time: s.clock.logical_time }); return { ok: true, process: created.process };
}
function progressRecovery(world, run_id, s, process) { const incident = s.incidents[process.dependencies[0]]; const team = s.teams[process.team_id]; if (!incident || !team) return; if (process.status === "preparing") { process.status = "active"; process.known_status = "active"; process.phase = "travel"; institutionEvent(world, run_id, "process_advanced", { process_id: process.id, status: "active", phase: "travel" }); return; } if (process.status === "active") { const sourceReport = s.reports.find((item) => item.id === incident.source_report_id); for (const personId of sourceReport?.facts.personnel ?? []) if (s.personnel[personId]?.status === "unavailable") { s.personnel[personId].status = "recovering"; s.personnel[personId].known_status = "recovering"; s.personnel[personId].recovery_process_id = process.id; } const resource = sourceReport?.facts.resource; if (resource && s.resources[resource].recoverable > 0) { const item = s.resources[resource]; item.recoverable -= 1; item.lost -= 1; item.recovered += 1; item.available += 1; } process.status = "completed"; process.known_status = "completed"; process.phase = "complete"; process.completion = { logical_time: s.clock.logical_time, outcome: "recovered" }; incident.status = "resolved"; releaseTeam(s, team); s.budget.committed -= 1; s.budget.spent += 1; institutionEvent(world, run_id, "recovery_completed", { process_id: process.id, incident_id: incident.id, logical_time: s.clock.logical_time }); }
}
function advance(world, run_id) {
  const s = state(world); s.tick += 1; s.clock.logical_time += 1; institutionEvent(world, run_id, "time_advanced", { logical_time: s.clock.logical_time });
  for (const person of Object.values(s.personnel)) if (person.status === "recovering" && (!person.recovery_process_id || s.clock.logical_time > s.processes[person.recovery_process_id]?.completion?.logical_time)) { person.status = "available"; person.known_status = "available"; person.recovery_process_id = null; managementEvent(world, run_id, "personnel.recovered", { personnel_id: person.id }); }
  for (const process of Object.values(s.processes).sort((a, b) => a.id.localeCompare(b.id))) { if (process.type === "expedition" && !["completed", "failed", "cancelled"].includes(process.status)) progressExpedition(world, run_id, s, process); if (process.type === "recovery" && !["completed", "failed", "cancelled"].includes(process.status)) progressRecovery(world, run_id, s, process); }
  advanceCommunications(world, run_id, s);
  if (s.research.priority) s.research.progress += 1;
  for (const project of Object.values(s.infrastructure)) if (project.status === "under-construction") { project.progress += 1; if (project.progress >= 2) { project.status = "operational"; managementEvent(world, run_id, "infrastructure.operational", { project_id: project.id }); } }
  return { ok: true, tick: s.tick, logical_time: s.clock.logical_time };
}
function prioritize(world, run_id, topic) { const s = state(world); if (!Object.keys(history.knownRegions(world, "async-command")).length && !["architecture", "recovered-evidence"].includes(topic)) return { ok: false, code: "PRIORITY_UNAVAILABLE" }; s.research.priority = topic; managementEvent(world, run_id, "research.prioritized", { topic }); return { ok: true }; }
function buildOutpost(world, run_id, { id, region_id }) { const s = state(world); if (s.infrastructure[id] || !history.knownRegions(world, "async-command").some((entry) => entry.region_id === region_id) || s.resources["construction-material"].available < 1 || s.budget.available < 3 || !Object.values(s.personnel).some((person) => person.role === "engineer" && person.status === "available")) return { ok: false, code: "PROJECT_UNAVAILABLE" }; s.resources["construction-material"].available -= 1; s.resources["construction-material"].allocated += 1; s.budget.available -= 3; s.budget.committed += 3; s.infrastructure[id] = { id, type: "survey-outpost", region_id, status: "under-construction", progress: 0, provenance: "pack-original-infrastructure" }; managementEvent(world, run_id, "infrastructure.started", { id, region_id, type: "survey-outpost" }); return { ok: true }; }
function managementResult(world) { const s = state(world); return { version: s.version, logical_time: s.clock.logical_time, operations: clone(s.operations), processes: clone(s.processes), resources: clone(s.resources), budget: clone(s.budget), research: clone(s.research), infrastructure: clone(s.infrastructure), reports: clone(s.reports) }; }
module.exports = { VERSION, PROCESS_VERSION, state, projection, createTeam, allocate, createProcess, dispatch, recall, advance, applyFieldConsequence, approveRecovery, prioritize, buildOutpost, managementResult };
