"use strict";
const history = require("./world-history"); const clone = (value) => structuredClone(value);
const PERSONNEL = [{ id: "personnel-field-1", role: "field-researcher" }, { id: "personnel-field-2", role: "field-researcher" }, { id: "personnel-engineer-1", role: "engineer" }, { id: "personnel-doctor-1", role: "doctor" }, { id: "personnel-researcher-1", role: "researcher" }];
function state(world) { history.assertWorld(world); if (!world.management) world.management = { version: "yellow-beast-becks-desk@v1", tick: 0, budget: { available: 12, committed: 0, spent: 0 }, personnel: Object.fromEntries(PERSONNEL.map((p) => [p.id, { ...p, status: p.id === "personnel-field-2" ? "recovering" : "available", assignment: null }])), resources: { radio: { available: 2, allocated: 0 }, "survey-kit": { available: 2, allocated: 0 }, "medical-kit": { available: 1, allocated: 0 }, "construction-material": { available: 2, allocated: 0 } }, teams: {}, operations: {}, research: { priority: null, progress: 0 }, infrastructure: {}, reports: [] }; return world.management; }
function managementEvent(world, run_id, type, payload) { return history.event(world, run_id, `management.${type}`, payload, "pack-original-management-simulation"); }
function projection(world) { const s = state(world); const region_summaries = Object.values(world.knowledge.institutional.records).filter((record) => record.id.startsWith("institutional-region-summary-")).map((record) => ({ region_id: record.payload.region_id, summary: clone(record.payload.summary) })); return { operations: Object.values(s.operations).map(({ id, status, team_id, last_report }) => ({ id, status, team_id, last_report })), personnel: Object.values(s.personnel).map(({ id, role, status, assignment }) => ({ id, role, status, assignment })), resources: clone(s.resources), budget: clone(s.budget), research: clone(s.research), infrastructure: Object.values(s.infrastructure).map(({ id, type, status, region_id, progress }) => ({ id, type, status, region_id, progress })), archive: { known_regions: history.knownRegions(world, "async-command"), region_summaries, expedition_count: Object.values(world.runs).filter((run) => run.expedition_id).length }, reports: s.reports.map(({ operation_id, status, summary }) => ({ operation_id, status, summary })) }; }
function createTeam(world, run_id, { id, members }) { const s = state(world); if (s.teams[id]) return { ok: false, code: "TEAM_EXISTS" }; if (!Array.isArray(members) || !members.length || members.some((person) => !s.personnel[person] || s.personnel[person].status !== "available" || s.personnel[person].assignment)) return { ok: false, code: "PERSONNEL_UNAVAILABLE" }; for (const person of members) { s.personnel[person].assignment = id; s.personnel[person].status = "assigned"; } s.teams[id] = { id, members, status: "ready", equipment: {} }; managementEvent(world, run_id, "team.created", { id, members }); return { ok: true, team: s.teams[id] }; }
function allocate(world, run_id, { team_id, resource, quantity = 1 }) { const s = state(world); const team = s.teams[team_id]; const item = s.resources[resource]; if (!team || !item || quantity < 1 || item.available < quantity) return { ok: false, code: "RESOURCE_UNAVAILABLE" }; item.available -= quantity; item.allocated += quantity; team.equipment[resource] = (team.equipment[resource] ?? 0) + quantity; managementEvent(world, run_id, "resource.allocated", { team_id, resource, quantity }); return { ok: true }; }
function dispatch(world, run_id, { id, team_id, region_id, objective = "survey" }) { const s = state(world); const team = s.teams[team_id]; if (s.operations[id]) return { ok: false, code: "OPERATION_EXISTS" }; if (!team || team.status !== "ready" || !history.knownRegions(world, "async-command").some((entry) => entry.region_id === region_id)) return { ok: false, code: "OPERATION_UNAVAILABLE" }; if (s.budget.available < 2) return { ok: false, code: "BUDGET_UNAVAILABLE" }; s.budget.available -= 2; s.budget.committed += 2; team.status = "deployed"; s.operations[id] = { id, team_id, region_id, objective, status: "dispatched", order_status: "issued", last_report: null }; managementEvent(world, run_id, "operation.dispatched", { id, team_id, region_id, objective }); return { ok: true, operation: s.operations[id] }; }
function recall(world, run_id, id) { const op = state(world).operations[id]; if (!op || !["dispatched", "active"].includes(op.status)) return { ok: false, code: "OPERATION_UNAVAILABLE" }; op.order_status = "recall-requested"; managementEvent(world, run_id, "recall.issued", { operation_id: id }); return { ok: true, public_reason: "recall requested" }; }
function advance(world, run_id) { const s = state(world); s.tick += 1; for (const person of Object.values(s.personnel)) if (person.status === "recovering") { person.status = "available"; managementEvent(world, run_id, "personnel.recovered", { personnel_id: person.id }); }
  for (const op of Object.values(s.operations)) { if (op.status === "dispatched") { op.status = "active"; op.last_report = { status: "delayed", summary: "Team entered the assigned region; no verified survey result received." }; s.reports.push({ operation_id: op.id, ...op.last_report }); managementEvent(world, run_id, "report.delayed", { operation_id: op.id }); } else if (op.status === "active") { const team = s.teams[op.team_id]; const complete = op.order_status === "recall-requested" ? "returning" : "completed"; op.status = complete; op.last_report = { status: "delivered", summary: complete === "completed" ? "Bounded field report archived." : "Recall acknowledged; return pending." }; s.reports.push({ operation_id: op.id, ...op.last_report }); if (complete === "completed") { team.status = "ready"; for (const key of Object.keys(team.equipment)) { s.resources[key].allocated -= team.equipment[key]; s.resources[key].available += team.equipment[key]; } s.budget.committed -= 2; s.budget.spent += 2; } managementEvent(world, run_id, "report.archived", { operation_id: op.id, status: complete }); } }
  if (s.research.priority) s.research.progress += 1; for (const project of Object.values(s.infrastructure)) if (project.status === "under-construction") { project.progress += 1; if (project.progress >= 2) { project.status = "operational"; managementEvent(world, run_id, "infrastructure.operational", { project_id: project.id }); } } return { ok: true, tick: s.tick }; }
function prioritize(world, run_id, topic) { const s = state(world); if (!Object.keys(history.knownRegions(world, "async-command")).length && !["architecture", "recovered-evidence"].includes(topic)) return { ok: false, code: "PRIORITY_UNAVAILABLE" }; s.research.priority = topic; managementEvent(world, run_id, "research.prioritized", { topic }); return { ok: true }; }
function buildOutpost(world, run_id, { id, region_id }) { const s = state(world); if (s.infrastructure[id] || !history.knownRegions(world, "async-command").some((entry) => entry.region_id === region_id) || s.resources["construction-material"].available < 1 || s.budget.available < 3 || !Object.values(s.personnel).some((person) => person.role === "engineer" && person.status === "available")) return { ok: false, code: "PROJECT_UNAVAILABLE" }; s.resources["construction-material"].available -= 1; s.resources["construction-material"].allocated += 1; s.budget.available -= 3; s.budget.committed += 3; s.infrastructure[id] = { id, type: "survey-outpost", region_id, status: "under-construction", progress: 0, provenance: "pack-original-infrastructure" }; managementEvent(world, run_id, "infrastructure.started", { id, region_id, type: "survey-outpost" }); return { ok: true }; }
function managementResult(world) { const s = state(world); return { version: s.version, operations: clone(s.operations), resources: clone(s.resources), budget: clone(s.budget), research: clone(s.research), infrastructure: clone(s.infrastructure), reports: clone(s.reports) }; }
module.exports = { state, projection, createTeam, allocate, dispatch, recall, advance, prioritize, buildOutpost, managementResult };
