"use strict";

// Pass 1 desktop build is a deterministic staging check, not an installer.
// Native distribution is deliberately deferred to YB-26 Pass 4.
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const required = ["desktop/main.js", "desktop/preload.js", "desktop/service.js", "desktop/credentials.js", "desktop/package-smoke.js", "desktop/renderer/index.html", "desktop/renderer/renderer.js", "desktop/renderer/surfaces.js", "desktop/renderer/styles.css", "desktop/renderer/interaction.js", "desktop/renderer/interaction.css", "desktop/renderer/qol.js", "desktop/renderer/qol.css", "desktop/renderer/accessibility.js", "desktop/renderer/accessibility.css", "tools/spatial-runtime.js", "tools/object-runtime.js", "tools/mission-runtime.js", "tools/operational-cycle.js", "tools/logistics-runtime.js", "tools/institutional-runtime.js", "tools/worldpack-authoring.js", "tools/q4-radio.js", "tools/q4-time.js", "data/worldpacks/registry.json", "data/worldpacks/clear-q4/spatial.json", "data/worldpacks/clear-q4/interactions.json", "data/worldpacks/clear-q4/mission.json", "data/worldpacks/clear-q4/dynamics.json", "data/worldpacks/clear-q4/logistics.json", "data/worldpacks/clear-q4/institution.json", "data/worldpacks/clear-q4/operation.json", "data/worldpacks/minimal-mission/spatial.json", "data/worldpacks/minimal-mission/interactions.json", "data/worldpacks/minimal-mission/mission.json", "data/worldpacks/authoring-fixture/worldpack.json", "canon/operational-spatial-schema.json", "canon/operational-interaction-schema.json", "canon/operational-mission-schema.json", "canon/operational-dynamics-schema.json", "canon/operational-logistics-schema.json", "canon/institutional-response-schema.json", "canon/complete-operation-schema.json", "tools/verify-desktop-artifact.js"];
for (const relative of required) if (!fs.existsSync(path.join(root, relative))) throw new Error(`desktop build input missing: ${relative}`);
const output = path.join(root, "dist", "desktop-shell-manifest.json"); fs.mkdirSync(path.dirname(output), { recursive: true }); fs.writeFileSync(output, `${JSON.stringify({ version: require("../package.json").version, framework: "electron", inputs: required }, null, 2)}\n`);
console.log(JSON.stringify({ desktop_build: "staged", framework: "electron", output }, null, 2));
