"use strict";
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const read = (file) => JSON.parse(fs.readFileSync(path.join(root, file), "utf8"));
const count = (items, key) => Object.fromEntries([...new Set(items.map(key))].sort().map((value) => [value, items.filter((item) => key(item) === value).length]));
function claims() { return fs.readdirSync(path.join(root, "canon/claims")).filter((file) => file.endsWith(".json")).flatMap((file) => read(`canon/claims/${file}`).claims ?? [read(`canon/claims/${file}`)]); }
function runtimeCoverage() {
  const all = claims(); const byId = new Map(all.map((claim) => [claim.id, claim])); const baseRuntime = read("data/runtime-traceability.json").records.map((item) => ({ ...item, claim_id: item.provenance })); const humanRuntime = require("./human-world").HUMAN_RUNTIME;
  const runtime = [...baseRuntime, ...humanRuntime];
  const records = runtime.map((item) => { const claimId = item.claim_id ?? item.provenance; const claim = byId.get(claimId) ?? null; return { runtime_id: item.id, path: item.path, claim_id: claimId, source_refs: claim?.source_refs ?? [], authority: item.authority, canon_status: claim?.canon_status ?? "untraced", coverage: claim?.simulation_authority === "reference-only" ? "REFERENCE_ONLY" : claim ? "FULLY_EXPRESSED" : "UNTRACED", experience: item.experience ?? (item.id.includes("field") ? ["Clear-Q4"] : item.id.includes("evidence") ? ["Clear-Q4", "Beck", "Nullzone"] : item.id.includes("architecture") || item.id.includes("topology") || item.id.includes("anomaly") ? ["Clear-Q4", "Nullzone", "Lost"] : ["Clear-Q4", "Beck"]) }; });
  const linked = new Set(records.map((item) => item.claim_id));
  const coverage = all.map((claim) => ({ claim_id: claim.id, coverage: claim.simulation_authority === "prohibited" ? "PROHIBITED" : claim.simulation_authority === "reference-only" ? "REFERENCE_ONLY" : linked.has(claim.id) ? "FULLY_EXPRESSED" : "UNIMPLEMENTED" }));
  return { claims: all, runtime: records, coverage };
}
function report() {
  const source = read("canon/source-registry.json").sources; const result = runtimeCoverage();
  const pack = result.claims.filter((claim) => claim.canon_status === "pack-original");
  const unlabeledPack = pack.filter((claim) => !claim.notes || !claim.extraction?.locator).length;
  const human = require("./human-world").report();
  return { version: "yellow-beast-canon-runtime@v1", source_pipeline: ["source registry", "verified locator or extraction", "normalized claim", "canon status", "simulation authority", "scenario/runtime trace", "mode experience"], sources: { total: source.length, by_type: count(source, (item) => item.source_type) }, claims: { total: result.claims.length, canon_status: count(result.claims, (item) => item.canon_status), authority: count(result.claims, (item) => item.simulation_authority), experiential_coverage: count(result.coverage, (item) => item.coverage) }, runtime: result.runtime, canon_gravity: { canon_supported_distinctive_runtime: result.runtime.filter((item) => item.canon_status !== "pack-original" && item.canon_status !== "untraced").length, pack_original_distinctive_runtime: result.runtime.filter((item) => item.canon_status === "pack-original").length, generic_procedural_fill: read("data/procedural-readiness.json").categories.length + human.procedural_glue.length, untraced_distinctive_runtime: result.runtime.filter((item) => item.coverage === "UNTRACED").length }, pack_original: pack.map((claim) => ({ claim_id: claim.id, classification: claim.simulation_authority === "scenario-optional" ? "SCENARIO_OPTION" : "NECESSARY_SIMULATION_GLUE" })), modes: { "Clear-Q4": result.runtime.filter((item) => item.experience.includes("Clear-Q4")).length, Beck: result.runtime.filter((item) => item.experience.includes("Beck")).length, Nullzone: result.runtime.filter((item) => item.experience.includes("Nullzone")).length, Lost: result.runtime.filter((item) => item.experience.includes("Lost")).length }, characters: { canon_named_characters: [], current_runtime_named_characters: 0, gap: human.named_character_admission.status }, human_world: { canon_runtime: human.canon_runtime.length, procedural_glue: human.procedural_glue.length, named_character_admission: human.named_character_admission }, priority_queue: { pass_2: ["No named-character admission without a normalized, temporally plausible source claim; retain anonymous persistent staff."], pass_3: ["authoritative local architecture and environmental survey claims"], pass_4: ["authoritative anomaly observations with bounded behavior authority"], pass_5: ["history links derived from experienced evidence and communication"] }, invariants: { "unlabeled pack-original canon claims": unlabeledPack, "production material automatic canon promotion": 0, "community source automatic authority promotion": 0, "canon-runtime untraced distinctive content": result.runtime.filter((item) => item.coverage === "UNTRACED").length, "pack-original distinctive lore": result.runtime.filter((item) => item.canon_status === "pack-original").length } };
}
module.exports = { claims, runtimeCoverage, report };
