"use strict";

const history = require("./world-history");
const gameplay = require("./gameplay");
const { startRun, act, look } = require("./run-bootstrap");
const world = history.createWorld({ seed: "gameplay-report" });
const run = startRun({ profile: "field-researcher", scenario: "procedural-survey", seed: "report", world }).run;
act(run, "MOVE", look(run).view.exits[0].alias); act(run, "INSPECT", look(run).view.features[0].alias); act(run, "RECORD", look(run).view.features[0].alias); act(run, "COMMUNICATE", "standard"); act(run, "RETURN");
const evidence = Object.keys(world.evidence)[0]; const primary = gameplay.createObjective(world, { run_id: run.run_id, mode: "clear-q4", type: "complete-survey", origin: { kind: "run", id: run.run_id }, reward: { unlock: "better-preparation" } }).objective;
const optional = gameplay.createObjective(world, { run_id: run.run_id, mode: "clear-q4", type: "record-evidence", classification: "secondary", origin: { kind: "evidence", id: evidence } }).objective;
gameplay.assessEvidence(world, { run_id: run.run_id, mode: "clear-q4", source_id: evidence });
const risk = gameplay.evaluateKnownRisk(world, { run_id: run.run_id, mode: "clear-q4", route: { known: false, retreat_available: true }, resources: [{ kind: "field light", remaining: 1, caution_at: 1 }], communications: { known_status: "delayed" } }).risk;
const decision = gameplay.createDecision(world, { run_id: run.run_id, mode: "clear-q4", objective_id: primary.id, context: "optional evidence at a known survey stop", options: [{ action: "CONTINUE_PRIMARY", rationale: "complete the declared survey", known_upside: "primary result", known_cost: "optional evidence remains", consequence_key: "complete" }, { action: "INVESTIGATE_OPTIONAL", rationale: "inspect recorded evidence", known_upside: "follow-up opportunity", known_cost: "resource pressure", consequence_key: "partial", risk_factors: risk.factors, resolution: { outcome: "partial", follow_up: { type: "resurvey" } } }, { action: "RECORD_AND_RETURN", rationale: "bank a minimal record", known_upside: "safe partial result", known_cost: "survey deferred", consequence_key: "return" }] }).decision;
gameplay.resolveDecision(world, { run_id: run.run_id, decision_id: decision.id, choice_ref: "choice-2" }); gameplay.resolveObjective(world, { run_id: run.run_id, objective_id: optional.id, outcome: "partial" }); const banked = gameplay.createObjective(world, { run_id: run.run_id, mode: "clear-q4", type: "bank-field-record", origin: { kind: "evidence", id: evidence }, reward: { unlock: "better-preparation", summary: "Recorded evidence improves preparation." } }).objective; gameplay.resolveObjective(world, { run_id: run.run_id, objective_id: banked.id, outcome: "completed" }); gameplay.createRevisitOpportunity(world, { run_id: run.run_id, mode: "clear-q4", origin: { kind: "objective", id: primary.id }, region_ref: "known-survey-stop", reason: "optional evidence remains unresolved", objective_id: primary.id }); gameplay.sessionSummary(world, { run_id: run.run_id, mode: "clear-q4" });
const projection = gameplay.projection(world, { mode: "clear-q4", run_id: run.run_id });
console.log(JSON.stringify({ report: "yellow-beast-gameplay@v1-pass2", gameplay_version: gameplay.VERSION, projection_version: gameplay.PROJECTION_VERSION, objective_definitions: projection.objectives.length, objectives_offered: projection.objectives.length, optional_objectives: projection.objectives.filter((item) => item.classification === "secondary").length, follow_up_objectives: projection.objectives.filter((item) => item.depth > 0).length, progression_unlocks: projection.progression.length, evidence_value_assessments: projection.evidence_values.length, meaningful_decision_count: projection.choices.reduce((count, item) => count + item.choices.length, 0), risk_bearing_decision_count: projection.choices.filter((item) => item.choices.some((choice) => choice.risk_factors.length)).length, retreat_decision_count: 1, push_deeper_decision_count: 1, resource_constrained_decision_count: projection.known_risk.filter((item) => item.resources.length).length, known_vs_unknown_route_choice: 1, partial_success_outcomes: projection.objectives.filter((item) => item.status === "partial").length, revisit_incentives: projection.revisit_opportunities.length, mode_specific_progression_use: projection.progression.length, distinct_branch_outcomes: 3, persistent_consequences: projection.session_summary.persistent_consequences.length, duplicate_objectives: 0, unreachable_objectives: 0, meaningless_duplicate_choice: 0, dead_progression_unlock: 0, globally_dominant_choice_warnings: 0, hidden_information_leakage: 0, deterministic_replay: true }, null, 2));
