"use strict";

// Generic, worldpack-driven logistics authority. Compatibility projections may
// expose item dictionaries, but every custody mutation commits through here.
const crypto = require("node:crypto");

const DEFINITION_VERSION = "yellow-beast-logistics-worldpack@v1";
const STATE_VERSION = "yellow-beast-logistics-state@v1";
const ACTIONS = Object.freeze(["INSPECT", "CARRY", "EQUIP", "UNEQUIP", "USE", "ACTIVATE", "DEACTIVATE", "CONSUME", "REPLENISH", "HAND_OVER", "RECEIVE", "ASSIGN", "PLACE", "DROP", "STORE", "RETRIEVE", "LOSE", "ABANDON", "RECOVER", "VERIFY", "RECONCILE"]);
const CONTAINER_ACTIONS = Object.freeze(["INSPECT_CONTAINER", "OPEN_CONTAINER", "CLOSE_CONTAINER", "DROP_CONTAINER", "LOSE_CONTAINER", "RECOVER_CONTAINER", "VERIFY_CONTAINER", "RECONCILE_CONTAINER"]);
const CONDITIONS = new Set(["operational", "serviceable", "damaged", "disabled", "depleted", "dropped", "lost", "abandoned", "destroyed"]);
const clone = (value) => structuredClone(value);
const digest = (value) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex").slice(0, 18);
const memberId = (member) => member?.personnel_id ?? member?.id;
const idPattern = /^[a-z0-9][a-z0-9-]*$/;

function unique(values, label) { if (new Set(values).size !== values.length) throw new Error(`${label} contains duplicate IDs`); }
function validateDefinition(definition, catalogs = {}) {
  if (!definition || definition.version !== DEFINITION_VERSION || !idPattern.test(definition.worldpack_id ?? "")) throw new Error("unsupported logistics worldpack");
  if (!Array.isArray(definition.item_definitions) || !Array.isArray(definition.item_instances) || !Array.isArray(definition.containers) || !definition.loadout) throw new Error("logistics worldpack is incomplete");
  const definitionIds = definition.item_definitions.map((item) => item.id); const instanceIds = definition.item_instances.map((item) => item.id); const containerIds = definition.containers.map((item) => item.id);
  unique(definitionIds, "item definitions"); unique(instanceIds, "item instances"); unique(containerIds, "containers");
  const definitionSet = new Set(definitionIds); const instanceSet = new Set(instanceIds); const containerSet = new Set(containerIds); const roles = new Set(catalogs.personnel_roles ?? []);
  for (const item of definition.item_definitions) {
    if (!idPattern.test(item.id ?? "") || typeof item.display_name !== "string" || !item.display_name.trim() || typeof item.category !== "string" || !item.category.trim()) throw new Error(`invalid item definition at item_definitions.${item.id ?? "unknown"}`);
    if (!Array.isArray(item.capabilities) || item.capabilities.some((value) => typeof value !== "string") || !Number.isFinite(item.capacity_contribution) || item.capacity_contribution < 0) throw new Error(`invalid item capabilities at item_definitions.${item.id}`);
    if (item.maximum_charges !== undefined && (!Number.isInteger(item.maximum_charges) || item.maximum_charges < 0)) throw new Error(`invalid charges at item_definitions.${item.id}`);
    if (item.replenishes_definitions !== undefined && (!Array.isArray(item.replenishes_definitions) || new Set(item.replenishes_definitions).size !== item.replenishes_definitions.length)) throw new Error(`invalid replenishment targets at item_definitions.${item.id}.replenishes_definitions`);
    for (const target of item.replenishes_definitions ?? []) if (!definitionIds.includes(target)) throw new Error(`unresolved replenishment target at item_definitions.${item.id}.replenishes_definitions`);
  }
  for (const item of definition.item_instances) {
    if (!idPattern.test(item.id ?? "") || !definitionSet.has(item.definition_id)) throw new Error(`unresolved item definition at item_instances.${item.id ?? "unknown"}.definition_id`);
    if (item.initial_container && !containerSet.has(item.initial_container)) throw new Error(`unresolved container at item_instances.${item.id}.initial_container`);
    if (item.assignment?.role && roles.size && !roles.has(item.assignment.role)) throw new Error(`unresolved personnel role at item_instances.${item.id}.assignment.role`);
  }
  for (const container of definition.containers) {
    if (!idPattern.test(container.id ?? "") || typeof container.display_name !== "string" || !Number.isFinite(container.capacity) || container.capacity < 0) throw new Error(`invalid container at containers.${container.id ?? "unknown"}`);
    if (!Array.isArray(container.allowed_categories) || !container.allowed_categories.length) throw new Error(`container has no allowed categories at containers.${container.id}`);
    if (container.parent_container && !containerSet.has(container.parent_container)) throw new Error(`unresolved parent container at containers.${container.id}.parent_container`);
    if (container.parent_container && definition.containers.find((entry) => entry.id === container.parent_container)?.parent_container) throw new Error(`container nesting exceeds one level at containers.${container.id}`);
  }
  const required = definition.loadout.required ?? []; const optional = definition.loadout.optional ?? [];
  if (required.some((id) => !instanceSet.has(id)) || optional.some((id) => !instanceSet.has(id))) throw new Error("loadout references an unknown item instance");
  if (required.some((id) => optional.includes(id))) throw new Error("loadout item cannot be both required and optional");
  const capacityByContainer = Object.fromEntries(definition.containers.map((item) => [item.id, item.capacity])); const categoryByDefinition = Object.fromEntries(definition.item_definitions.map((item) => [item.id, item.category]));
  for (const container of definition.containers) {
    const assigned = definition.item_instances.filter((item) => item.initial_container === container.id);
    const used = assigned.reduce((sum, item) => sum + definition.item_definitions.find((entry) => entry.id === item.definition_id).capacity_contribution, 0);
    if (used > capacityByContainer[container.id]) throw new Error(`container capacity contradiction at containers.${container.id}`);
    if (assigned.some((item) => !container.allowed_categories.includes(categoryByDefinition[item.definition_id]) && !container.allowed_categories.includes("*"))) throw new Error(`container category contradiction at containers.${container.id}`);
  }
  return true;
}

function assignmentHolder(spec, context) {
  if (spec?.assignment?.holder === "player") return context.player;
  if (spec?.assignment?.holder === "institution") return "institutional-stores";
  if (spec?.assignment?.role) return (context.team ?? []).find((member) => String(member.role).toLowerCase() === String(spec.assignment.role).toLowerCase())?.personnel_id ?? context.player;
  return context.player;
}
function normalizeItem(key, legacy, definition = {}) {
  const maximum = definition.maximum_charges ?? (Number.isInteger(legacy?.charges) ? legacy.charges : null);
  return {
    id: key,
    instance_id: legacy?.id ?? `item-${digest([key, definition.id])}`,
    definition_id: definition.id ?? legacy?.type ?? key,
    display_name: definition.display_name ?? legacy?.label ?? key,
    category: definition.category ?? legacy?.type ?? "equipment",
    capabilities: clone(definition.capabilities ?? [legacy?.capability].filter(Boolean)),
    condition: CONDITIONS.has(legacy?.state) ? legacy.state : "operational",
    charges: Number.isInteger(legacy?.charges) ? legacy.charges : maximum,
    maximum_charges: maximum,
    quantity: Number.isInteger(legacy?.quantity) ? legacy.quantity : 1,
    consumable: definition.consumable === true || Boolean(legacy?.consumable),
    current_holder: legacy?.holder ?? null,
    current_container: legacy?.container_id ?? null,
    current_location: legacy?.location ?? null,
    equipped: legacy?.equipped === true,
    active: legacy?.active === true,
    assigned_owner: legacy?.assigned_to ?? null,
    institutional_owner: legacy?.institutional_owner ?? "Standard",
    capacity_contribution: definition.capacity_contribution ?? 1,
    known_condition: legacy?.known_condition ?? "Operational",
    last_confirmed_custody: clone(legacy?.last_confirmed_custody ?? null),
    history: clone(legacy?.history ?? []),
    recoverability: legacy?.recoverable === false ? "irrecoverable" : "recoverable",
    replenishes_definitions: clone(definition.replenishes_definitions ?? []),
    reconciliation: clone(legacy?.reconciliation ?? null),
    legacy: { key, type: legacy?.type ?? definition.id ?? key, consumable: clone(legacy?.consumable ?? null), model: legacy?.model ?? definition.model ?? null, capability: legacy?.capability ?? definition.capabilities?.[0] ?? null }
  };
}
function createState(definition, context = {}) {
  validateDefinition(definition, { personnel_roles: (context.team ?? []).map((member) => member.role) });
  const definitions = Object.fromEntries(definition.item_definitions.map((item) => [item.id, item]));
  const state = { version: STATE_VERSION, worldpack_id: definition.worldpack_id, revision: 0, items: {}, containers: {}, required: clone(definition.loadout.required ?? []), optional: clone(definition.loadout.optional ?? []), selected_optional: [], transaction_history: [], reconciliation_history: [], migrated_from: null };
  for (const spec of definition.containers) state.containers[spec.id] = { id: spec.id, display_name: spec.display_name, kind: spec.kind, capacity: spec.capacity, allowed_categories: clone(spec.allowed_categories), open: spec.initial_open !== false, accessible: spec.initial_accessible !== false, current_holder: spec.holder === "player" ? context.player : spec.holder === "institution" ? "institutional-stores" : null, current_location: spec.location ?? null, parent_container: spec.parent_container ?? null, contents: [], lost: false, history: [] };
  for (const member of context.team ?? []) { const id = memberId(member); if (!id || id === context.player || Object.values(state.containers).some((entry) => entry.current_holder === id && entry.kind === "personal")) continue; const containerId = `personal-${digest([state.worldpack_id, id])}`; state.containers[containerId] = { id: containerId, display_name: `${member.display_name ?? "Coworker"} field harness`, kind: "personal", capacity: definition.personal_capacity ?? 6, allowed_categories: ["*"], open: true, accessible: true, current_holder: id, current_location: context.location ?? null, parent_container: null, contents: [], lost: false, history: [] }; }
  for (const spec of definition.item_instances) {
    const legacy = context.legacy_items?.[spec.id] ?? {}; const item = normalizeItem(spec.id, legacy, definitions[spec.definition_id]); const holder = legacy.holder ?? assignmentHolder(spec, context);
    let containerId = legacy.container_id ?? spec.initial_container ?? null; const initialContainer = state.containers[containerId]; if (!legacy.container_id && holder && holder !== "institutional-stores" && initialContainer?.current_holder !== holder) containerId = Object.values(state.containers).find((entry) => entry.current_holder === holder && entry.kind === "personal")?.id ?? containerId; const container = state.containers[containerId];
    item.current_holder = container ? container.current_holder : holder; item.assigned_owner = legacy.assigned_to ?? holder; item.current_container = containerId; item.current_location = legacy.location ?? spec.initial_location ?? container?.current_location ?? null; item.charges = Number.isInteger(legacy.charges) ? legacy.charges : spec.initial_charges ?? item.maximum_charges; item.quantity = Number.isInteger(legacy.quantity) ? legacy.quantity : spec.initial_quantity ?? 1;
    item.history.push({ sequence: item.history.length + 1, action: "issued", holder, container: item.current_container, location: item.current_location, at: context.at ?? 0 }); state.items[spec.id] = item;
  }
  rebuildContents(state); validateState(state); return state;
}
function rebuildContents(state) { for (const container of Object.values(state.containers)) container.contents = []; for (const item of Object.values(state.items)) if (item.current_container && state.containers[item.current_container]) state.containers[item.current_container].contents.push(item.id); for (const container of Object.values(state.containers)) container.contents.sort(); }
function legacyItem(item) { return { id: item.instance_id, type: item.legacy.type ?? item.category, label: item.display_name, model: item.legacy.model, assigned_to: item.assigned_owner, holder: item.current_holder, container: item.current_container ? item.current_container : item.equipped ? "equipped" : item.current_location, container_id: item.current_container, location: item.current_location, state: item.condition, known_condition: item.known_condition, capability: item.legacy.capability ?? item.capabilities[0] ?? null, consumable: item.legacy.consumable ? { ...clone(item.legacy.consumable), remaining: item.charges ?? item.quantity } : null, charges: item.charges, quantity: item.quantity, used: item.history.filter((entry) => ["USE", "CONSUME"].includes(entry.action)).length, equipped: item.equipped, active: item.active, recoverable: item.recoverability !== "irrecoverable", history: item.history.map((entry) => ({ event: String(entry.action ?? "updated").toLowerCase().replace(/_/g, "-"), ...clone(entry) })), reconciliation: clone(item.reconciliation) } }
function attach(expedition) {
  const state = expedition.logistics; if (!state) return null; rebuildContents(state);
  const equipmentNext = Object.fromEntries(Object.entries(state.items).filter(([id]) => !state.optional.includes(id) || state.selected_optional.includes(id)).map(([id, item]) => [id, legacyItem(item)])); const equipment = expedition.equipment ?? {}; for (const id of Object.keys(equipment)) if (!equipmentNext[id]) delete equipment[id]; for (const [id, item] of Object.entries(equipmentNext)) equipment[id] ? Object.assign(equipment[id], item) : equipment[id] = item; expedition.equipment = equipment;
  const storesNext = Object.fromEntries(state.optional.filter((id) => !state.selected_optional.includes(id)).map((id) => [id, legacyItem(state.items[id])])); const stores = expedition.optional_stores ?? {}; for (const id of Object.keys(stores)) if (!storesNext[id]) delete stores[id]; for (const [id, item] of Object.entries(storesNext)) stores[id] ? Object.assign(stores[id], item) : stores[id] = item; expedition.optional_stores = stores;
  return state;
}
function syncSpatial(expedition, spatial) {
  const state = expedition?.logistics; if (!state || !spatial) return state ?? null;
  for (const container of Object.values(state.containers)) if (container.current_holder && container.current_holder !== "institutional-stores") container.current_location = spatial.personnel_locations?.[container.current_holder] ?? container.current_location;
  for (const item of Object.values(state.items)) {
    if (item.current_container) item.current_location = state.containers[item.current_container]?.current_location ?? item.current_location;
    else if (item.current_holder) item.current_location = spatial.personnel_locations?.[item.current_holder] ?? item.current_location;
  }
  attach(expedition); return state;
}
function migrate(expedition, definition, context = {}) {
  if (expedition.logistics?.version === STATE_VERSION && expedition.logistics.worldpack_id === definition.worldpack_id) { rebuildContents(expedition.logistics); return expedition.logistics; }
  const priorVersion = expedition.logistics?.version ?? "legacy-flat-equipment";
  const legacy = { ...(expedition.optional_stores ?? {}), ...(expedition.equipment ?? {}) };
  expedition.logistics = createState(definition, { ...context, legacy_items: legacy }); expedition.logistics.migrated_from = priorVersion; attach(expedition); return expedition.logistics;
}
function resolveItem(state, ref) { return state.items[ref] ?? Object.values(state.items).find((item) => item.instance_id === ref) ?? null; }
function actorLocation(context, actor) { return context.spatial?.personnel_locations?.[actor] ?? context.location ?? null; }
function sameLocation(context, one, two) { const a = actorLocation(context, one); const b = actorLocation(context, two); return Boolean(a && b && a === b); }
function containerAccess(state, container, actor, context) {
  if (!container || container.lost || !container.open || !container.accessible) return false;
  if (container.current_holder) return container.current_holder === actor || (container.current_holder === "institutional-stores" && container.current_location === actorLocation(context, actor)) || sameLocation(context, container.current_holder, actor);
  return Boolean(container.current_location && container.current_location === actorLocation(context, actor));
}
function capacityUsed(state, containerId, excluding = null) { const container = state.containers[containerId]; return (container?.contents ?? []).filter((id) => id !== excluding).reduce((sum, id) => sum + (state.items[id]?.capacity_contribution ?? 0) * (state.items[id]?.quantity ?? 1), 0); }
function validateState(state) {
  if (!state || state.version !== STATE_VERSION) throw new Error("unsupported logistics state");
  const seen = new Set();
  for (const [id, item] of Object.entries(state.items)) { if (seen.has(item.instance_id)) throw new Error(`duplicate item instance: ${item.instance_id}`); seen.add(item.instance_id); if (item.id !== id || !CONDITIONS.has(item.condition)) throw new Error(`invalid logistics item: ${id}`); if (item.current_container && !state.containers[item.current_container]) throw new Error(`orphaned item container: ${id}`); }
  for (const container of Object.values(state.containers)) { if (capacityUsed(state, container.id) > container.capacity) throw new Error(`container capacity exceeded: ${container.id}`); for (const id of container.contents) { const item = state.items[id]; if (!item || item.current_container !== container.id) throw new Error(`container content mismatch: ${container.id}`); if (!container.allowed_categories.includes("*") && !container.allowed_categories.includes(item.category)) throw new Error(`container category mismatch: ${container.id}`); } }
  return true;
}
function unavailable(code, reason) { return { ok: false, code, public_reason: reason }; }
function transact(expedition, definition, request, context = {}) {
  const current = migrate(expedition, definition, context); const action = String(request.action ?? "").toUpperCase(); if (!ACTIONS.includes(action)) return unavailable("LOGISTICS_ACTION_INVALID", "That logistics action is not supported.");
  const draft = clone(current); const item = resolveItem(draft, request.item_id); if (!item) return unavailable("ITEM_UNKNOWN", "That item is not part of this operation."); const actor = request.actor; const at = context.at ?? expedition.clock?.interval ?? 0; const location = actorLocation(context, actor);
  if (draft.optional.includes(item.id) && !draft.selected_optional.includes(item.id) && (context.restrictions ?? []).includes("optional-stores") && !["INSPECT", "VERIFY"].includes(action)) return unavailable("INSTITUTIONAL_RESTRICTION", "Standard has restricted optional stores pending review.");
  const holderPresent = item.current_holder === actor || (item.current_holder && sameLocation(context, item.current_holder, actor)); const possessed = item.current_holder === actor; const usable = ["operational", "serviceable"].includes(item.condition) && (item.charges === null || item.charges > 0) && item.quantity > 0;
  let summary = `${item.display_name} inspected.`;
  if (action === "INSPECT") { item.known_condition = item.condition; item.last_confirmed_custody = { holder: item.current_holder, container: item.current_container, location: item.current_location, at }; }
  else if (["EQUIP", "UNEQUIP", "ACTIVATE", "DEACTIVATE", "USE", "CONSUME", "VERIFY"].includes(action) && !possessed) return unavailable("ITEM_NOT_IN_CUSTODY", "The item must be in your custody first.");
  else if (["EQUIP", "ACTIVATE", "USE", "CONSUME"].includes(action) && !usable) return unavailable("ITEM_UNAVAILABLE", "The item is not operational or has no usable supply remaining.");
  if (action === "EQUIP") { item.equipped = true; item.current_container = null; item.current_location = location; summary = `${item.display_name} equipped.`; }
  if (action === "UNEQUIP") { item.equipped = false; const personal = Object.values(draft.containers).find((entry) => entry.current_holder === actor && entry.kind === "personal"); if (personal && capacityUsed(draft, personal.id, item.id) + item.capacity_contribution * item.quantity <= personal.capacity) item.current_container = personal.id; summary = `${item.display_name} unequipped.`; }
  if (action === "ACTIVATE") { item.active = true; summary = `${item.display_name} activated.`; }
  if (action === "DEACTIVATE") { item.active = false; summary = `${item.display_name} deactivated.`; }
  if (["USE", "CONSUME"].includes(action)) { const amount = Math.max(1, Number(request.quantity ?? 1)); if (Number.isInteger(item.charges)) { if (item.charges < amount) return unavailable("ITEM_DEPLETED", "The item does not have enough remaining charge."); item.charges -= amount; } else if (item.quantity >= amount && item.consumable) item.quantity -= amount; if ((item.charges === 0 || item.quantity === 0) && item.consumable) item.condition = "depleted"; summary = `${item.display_name} ${action === "USE" ? "used" : "consumed"}.`; }
  if (action === "REPLENISH") { const source = resolveItem(draft, request.source_item_id); if (!source || source.current_holder !== actor || !source.consumable || source.quantity < 1 || !["operational", "serviceable"].includes(source.condition) || (Number.isInteger(source.charges) && source.charges < 1) || item.maximum_charges === null || !source.replenishes_definitions.includes(item.definition_id)) return unavailable("REPLENISHMENT_UNAVAILABLE", "A compatible carried supply is required."); item.charges = item.maximum_charges; if (item.condition === "depleted") item.condition = "operational"; source.quantity -= 1; if (Number.isInteger(source.charges)) source.charges = 0; if (source.quantity === 0 || source.charges === 0) source.condition = "depleted"; summary = `${item.display_name} replenished.`; }
  if (["HAND_OVER", "RECEIVE", "ASSIGN"].includes(action)) { const target = request.target_holder; if (!target || !holderPresent || !sameLocation(context, actor, target)) return unavailable("TRANSFER_OUT_OF_RANGE", "Both people must share confirmed speaking range for a physical transfer."); if (action !== "RECEIVE" && item.current_holder !== actor) return unavailable("ITEM_NOT_IN_CUSTODY", "The current holder must participate in the transfer."); if (action === "RECEIVE" && item.current_holder !== target) return unavailable("TRANSFER_HOLDER_MISMATCH", "The declared holder does not possess that item."); const from = item.current_holder; const to = action === "RECEIVE" ? actor : target; item.current_holder = to; item.assigned_owner = action === "ASSIGN" ? to : item.assigned_owner; item.current_container = Object.values(draft.containers).find((entry) => entry.current_holder === to && entry.kind === "personal")?.id ?? null; item.current_location = actorLocation(context, to); item.equipped = false; summary = `${item.display_name} transferred from ${from} to ${to}.`; }
  if (["STORE", "PLACE"].includes(action)) { const container = draft.containers[request.target_container]; if (!containerAccess(draft, container, actor, context)) return unavailable("CONTAINER_INACCESSIBLE", "Open and reach the container before storing the item."); if (!possessed) return unavailable("ITEM_NOT_IN_CUSTODY", "The item must be in your custody first."); if (!container.allowed_categories.includes("*") && !container.allowed_categories.includes(item.category)) return unavailable("CONTAINER_CATEGORY_REJECTED", "That container is not rated for this item."); if (capacityUsed(draft, container.id, item.id) + item.capacity_contribution * item.quantity > container.capacity) return unavailable("CONTAINER_CAPACITY_EXCEEDED", "The container does not have enough remaining capacity."); item.current_holder = container.current_holder ?? actor; item.current_container = container.id; item.current_location = container.current_location ?? location; item.equipped = false; summary = `${item.display_name} stored in ${container.display_name}.`; }
  if (["RETRIEVE", "CARRY"].includes(action)) { const source = item.current_container ? draft.containers[item.current_container] : null; if (source && !containerAccess(draft, source, actor, context)) return unavailable("CONTAINER_INACCESSIBLE", "Open and reach the container before retrieving the item."); if (!source && item.current_location !== location) return unavailable("ITEM_OUT_OF_RANGE", "Reach the item's confirmed location before carrying it."); item.current_holder = actor; item.current_container = Object.values(draft.containers).find((entry) => entry.current_holder === actor && entry.kind === "personal")?.id ?? null; item.current_location = location; item.condition = item.condition === "dropped" ? "operational" : item.condition; summary = `${item.display_name} is now carried.`; }
  if (action === "DROP") { if (!possessed) return unavailable("ITEM_NOT_IN_CUSTODY", "Only the current holder can drop the item."); item.current_holder = null; item.current_container = null; item.current_location = location; item.equipped = false; item.active = false; item.condition = "dropped"; summary = `${item.display_name} dropped at the current location.`; }
  if (["LOSE", "ABANDON"].includes(action)) { if (!possessed && item.current_location !== location) return unavailable("ITEM_OUT_OF_RANGE", "The item cannot be abandoned from another location."); item.last_confirmed_custody = { holder: item.current_holder, location: item.current_location ?? location, at }; item.current_holder = null; item.current_container = null; item.current_location = action === "ABANDON" ? location : null; item.equipped = false; item.condition = action === "ABANDON" ? "abandoned" : "lost"; summary = `${item.display_name} ${action === "ABANDON" ? "left behind" : "recorded lost"}.`; }
  if (action === "RECOVER") { if (!["dropped", "lost", "abandoned"].includes(item.condition) || item.recoverability === "irrecoverable") return unavailable("ITEM_NOT_RECOVERABLE", "That item is not recoverable."); const confirmed = item.current_location ?? item.last_confirmed_custody?.location; if (!confirmed || confirmed !== location) return unavailable("ITEM_OUT_OF_RANGE", "Reach the item's confirmed location before recovering it."); item.current_holder = actor; item.current_container = Object.values(draft.containers).find((entry) => entry.current_holder === actor && entry.kind === "personal")?.id ?? null; item.current_location = location; item.condition = "operational"; summary = `${item.display_name} recovered.`; }
  if (action === "RECONCILE") { item.reconciliation = { status: ["lost", "abandoned", "destroyed"].includes(item.condition) ? item.condition : item.condition === "damaged" ? "returned-damaged" : item.condition === "depleted" ? "returned-depleted" : "returned", holder: item.current_holder, container: item.current_container, at }; draft.reconciliation_history.push({ item_id: item.id, ...clone(item.reconciliation) }); summary = `${item.display_name} reconciled as ${item.reconciliation.status}.`; }
  if (draft.optional.includes(item.id) && !draft.selected_optional.includes(item.id) && !["INSPECT", "VERIFY"].includes(action)) draft.selected_optional.push(item.id);
  item.known_condition = item.condition; item.last_confirmed_custody = { holder: item.current_holder, container: item.current_container, location: item.current_location, at }; item.history.push({ sequence: item.history.length + 1, action, actor, target_holder: request.target_holder ?? null, target_container: request.target_container ?? null, location: item.current_location, at });
  rebuildContents(draft); try { validateState(draft); } catch (error) { return unavailable("LOGISTICS_TRANSACTION_INVALID", error.message); }
  draft.revision += 1; const transaction = { id: `logistics-${digest([draft.worldpack_id, draft.revision, action, item.id, at])}`, sequence: draft.transaction_history.length + 1, action, item_id: item.id, actor, at, summary }; draft.transaction_history.push(transaction); expedition.logistics = draft; attach(expedition); return { ok: true, transaction: clone(transaction), item: clone(draft.items[item.id]), public_reason: summary };
}
function containerReachable(state, container, actor, context) {
  if (!container || container.lost) return false;
  if (container.current_holder) return container.current_holder === actor || (container.current_holder === "institutional-stores" && container.current_location === actorLocation(context, actor)) || sameLocation(context, container.current_holder, actor);
  return Boolean(container.current_location && container.current_location === actorLocation(context, actor));
}
function transactContainer(expedition, definition, request, context = {}) {
  const current = migrate(expedition, definition, context); const action = String(request.action ?? "").toUpperCase(); if (!CONTAINER_ACTIONS.includes(action)) return unavailable("CONTAINER_ACTION_INVALID", "That container action is not supported.");
  const draft = clone(current); const container = draft.containers[request.container_id]; if (!container) return unavailable("CONTAINER_UNKNOWN", "That container is not part of this operation."); const actor = request.actor; const at = context.at ?? expedition.clock?.interval ?? 0; const location = actorLocation(context, actor); let summary = `${container.display_name} inspected.`;
  if (action !== "RECOVER_CONTAINER" && !containerReachable(draft, container, actor, context)) return unavailable("CONTAINER_OUT_OF_RANGE", "Reach the container's confirmed location before handling it.");
  if (action === "OPEN_CONTAINER") { if (container.open) return unavailable("CONTAINER_ALREADY_OPEN", "The container is already open."); container.open = true; summary = `${container.display_name} opened.`; }
  if (action === "CLOSE_CONTAINER") { if (!container.open) return unavailable("CONTAINER_ALREADY_CLOSED", "The container is already closed."); container.open = false; summary = `${container.display_name} closed.`; }
  if (action === "DROP_CONTAINER") { if (container.current_holder !== actor) return unavailable("CONTAINER_NOT_IN_CUSTODY", "Only the current holder can place that container down."); container.current_holder = null; container.current_location = location; summary = `${container.display_name} placed at the current location.`; }
  if (action === "LOSE_CONTAINER") { if (container.current_holder !== actor && container.current_location !== location) return unavailable("CONTAINER_OUT_OF_RANGE", "That container cannot be lost from another location."); container.last_confirmed_location = container.current_location ?? location; container.current_holder = null; container.current_location = null; container.lost = true; summary = `${container.display_name} recorded lost with its contents.`; }
  if (action === "RECOVER_CONTAINER") { if (!container.lost || !container.last_confirmed_location || container.last_confirmed_location !== location) return unavailable("CONTAINER_NOT_RECOVERABLE", "The lost container is not confirmed at this location."); container.lost = false; container.current_holder = actor; container.current_location = location; summary = `${container.display_name} and its contents recovered.`; }
  if (action === "VERIFY_CONTAINER") summary = `${container.display_name} custody and contents verified.`;
  if (action === "RECONCILE_CONTAINER") { container.reconciliation = { status: container.lost ? "lost" : "returned", holder: container.current_holder, location: container.current_location, contents: clone(container.contents), at }; summary = `${container.display_name} reconciled as ${container.reconciliation.status}.`; }
  for (const itemId of container.contents) { const item = draft.items[itemId]; item.current_holder = container.current_holder; item.current_location = container.current_location; if (action === "LOSE_CONTAINER") item.condition = item.condition === "destroyed" ? "destroyed" : "lost"; if (action === "RECOVER_CONTAINER" && item.condition === "lost") item.condition = "operational"; item.last_confirmed_custody = { holder: item.current_holder, container: container.id, location: item.current_location ?? container.last_confirmed_location, at }; }
  container.history.push({ sequence: container.history.length + 1, action, actor, location: container.current_location, at }); rebuildContents(draft); try { validateState(draft); } catch (error) { return unavailable("LOGISTICS_TRANSACTION_INVALID", error.message); }
  draft.revision += 1; const transaction = { id: `logistics-${digest([draft.worldpack_id, draft.revision, action, container.id, at])}`, sequence: draft.transaction_history.length + 1, action, container_id: container.id, actor, at, summary }; draft.transaction_history.push(transaction); expedition.logistics = draft; attach(expedition); return { ok: true, transaction: clone(transaction), container: clone(container), public_reason: summary };
}
function reconcile(expedition, definition, context = {}) { const state = migrate(expedition, definition, context); const results = []; for (const item of Object.values(state.items).filter((entry) => state.required.includes(entry.id) || state.selected_optional.includes(entry.id))) results.push(transact(expedition, definition, { action: "RECONCILE", item_id: item.id, actor: context.actor }, context)); return results; }
function availableActions(expedition, definition, itemId, actor, context = {}) {
  const state = migrate(expedition, definition, context); const item = resolveItem(state, itemId); if (!item) return [];
  const possessed = item.current_holder === actor; const usable = ["operational", "serviceable"].includes(item.condition) && (item.charges === null || item.charges > 0) && item.quantity > 0; const location = actorLocation(context, actor); const targetHolder = (context.team ?? []).map(memberId).find((id) => id !== actor && sameLocation(context, actor, id)); const targetContainer = Object.values(state.containers).find((entry) => entry.id !== item.current_container && containerAccess(state, entry, actor, context) && (entry.allowed_categories.includes("*") || entry.allowed_categories.includes(item.category)) && capacityUsed(state, entry.id, item.id) + item.capacity_contribution * item.quantity <= entry.capacity); const source = item.current_container ? state.containers[item.current_container] : null; const replenishment = Object.values(state.items).find((entry) => entry.current_holder === actor && entry.consumable && entry.quantity > 0 && entry.replenishes_definitions.includes(item.definition_id)); const restricted = state.optional.includes(item.id) && !state.selected_optional.includes(item.id) && (context.restrictions ?? []).includes("optional-stores");
  const rules = {
    INSPECT: [true, null], VERIFY: [possessed || item.current_location === location, "Reach the item before verifying it."], EQUIP: [possessed && usable && !item.equipped, possessed ? "The item cannot be equipped in its current condition." : "The item must be in your custody first."], UNEQUIP: [possessed && item.equipped, "The item is not equipped."], USE: [possessed && usable, possessed ? "The item is unavailable or depleted." : "The item must be in your custody first."], ACTIVATE: [possessed && usable && !item.active, "The item cannot be activated now."], DEACTIVATE: [possessed && item.active, "The item is not active."], CONSUME: [possessed && usable && item.consumable, "A usable carried consumable is required."], REPLENISH: [possessed && Boolean(replenishment) && item.maximum_charges !== null, "A compatible carried supply is required."], HAND_OVER: [possessed && Boolean(targetHolder), possessed ? "No teammate is in confirmed physical range." : "The item must be in your custody first."], RECEIVE: [Boolean(targetHolder) && item.current_holder === targetHolder, "A nearby teammate must currently hold the item."], ASSIGN: [possessed && Boolean(targetHolder), "A nearby teammate is required for assignment."], STORE: [possessed && Boolean(targetContainer), possessed ? "No accessible compatible container has capacity." : "The item must be in your custody first."], PLACE: [possessed && Boolean(targetContainer), possessed ? "No accessible compatible container has capacity." : "The item must be in your custody first."], RETRIEVE: [!possessed && ((source && containerAccess(state, source, actor, context)) || (!source && item.current_location === location)), "Reach the accessible item before retrieving it."], CARRY: [!possessed && ((source && containerAccess(state, source, actor, context)) || (!source && item.current_location === location)), "Reach the accessible item before carrying it."], DROP: [possessed, "Only the current holder can drop the item."], LOSE: [possessed, "Only a carried item can be recorded lost."], ABANDON: [possessed, "Only a carried item can be abandoned here."], RECOVER: [["dropped", "lost", "abandoned"].includes(item.condition) && item.recoverability !== "irrecoverable" && (item.current_location ?? item.last_confirmed_custody?.location) === location, "Reach the recoverable item at its confirmed location."], RECONCILE: [["RETURN", "DEBRIEF"].includes(context.phase), "Reconciliation occurs during return or debrief."]
  };
  return Object.entries(rules).map(([action, [available, reason]]) => { const holder = ["HAND_OVER", "ASSIGN"].includes(action) ? targetHolder : action === "RECEIVE" ? item.current_holder : null; return { action, available: Boolean(available) && !(restricted && !["INSPECT", "VERIFY"].includes(action)), unavailable_reason: restricted && !["INSPECT", "VERIFY"].includes(action) ? "Standard has restricted optional stores pending review." : available ? null : reason, target_holder: holder ? (holder === actor ? "You" : context.names?.[holder] ?? "Assigned teammate") : null, target_container: ["STORE", "PLACE"].includes(action) ? targetContainer?.id ?? null : null, source_item_id: action === "REPLENISH" ? replenishment?.id ?? null : null }; });
}
function availableContainerActions(expedition, definition, containerId, actor, context = {}) { const state = migrate(expedition, definition, context); const container = state.containers[containerId]; if (!container) return []; const reachable = containerReachable(state, container, actor, context); return [{ action: "INSPECT_CONTAINER", available: reachable }, { action: "OPEN_CONTAINER", available: reachable && !container.open, unavailable_reason: !reachable ? "Reach the container first." : "The container is already open." }, { action: "CLOSE_CONTAINER", available: reachable && container.open, unavailable_reason: !reachable ? "Reach the container first." : "The container is already closed." }, { action: "DROP_CONTAINER", available: container.current_holder === actor, unavailable_reason: "Only the current holder can place it down." }, { action: "LOSE_CONTAINER", available: container.current_holder === actor, unavailable_reason: "Only the current holder can record it lost." }, { action: "RECOVER_CONTAINER", available: container.lost && container.last_confirmed_location === actorLocation(context, actor), unavailable_reason: "Reach its last confirmed location first." }, { action: "VERIFY_CONTAINER", available: reachable, unavailable_reason: "Reach the container first." }, { action: "RECONCILE_CONTAINER", available: ["RETURN", "DEBRIEF"].includes(context.phase), unavailable_reason: "Reconciliation occurs during return or debrief." }]; }
function project(expedition, definition, observer, context = {}) {
  const state = migrate(expedition, definition, context); const containers = Object.values(state.containers).map((container) => ({ id: container.id, name: container.display_name, kind: container.kind, capacity: container.capacity, used: capacityUsed(state, container.id), open: container.open, accessible: containerAccess(state, container, observer, context), holder: container.current_holder === observer ? "You" : context.names?.[container.current_holder] ?? container.current_holder, location: container.current_location, contents: containerAccess(state, container, observer, context) ? container.contents.map((id) => state.items[id].display_name) : [], lost: container.lost, actions: availableContainerActions(expedition, definition, container.id, observer, context) }));
  const items = Object.values(state.items).map((item) => { const local = item.current_holder === observer || (item.current_holder && sameLocation(context, observer, item.current_holder)) || item.current_location === actorLocation(context, observer); const known = local || item.last_confirmed_custody; const optional = state.optional.includes(item.id); return { id: item.id, label: item.display_name, category: item.category, capabilities: clone(item.capabilities), loadout_status: state.required.includes(item.id) ? "required" : optional && state.selected_optional.includes(item.id) ? "selected optional" : optional ? "available optional" : "issued", holder: item.current_holder === observer ? "You" : context.names?.[item.current_holder] ?? (item.current_holder === "institutional-stores" ? "Team stores" : item.current_holder ? "Assigned teammate" : "No confirmed holder"), container: local ? state.containers[item.current_container]?.display_name ?? null : item.last_confirmed_custody?.container ? "Last confirmed container" : null, condition: local ? item.condition : known ? item.known_condition : "unknown", charges: local ? item.charges : null, quantity: local ? item.quantity : null, equipped: local ? item.equipped : false, location: local ? item.current_location : item.last_confirmed_custody?.location ?? "unknown", accessibility: item.current_holder === observer || local ? "accessible" : "last-known", institutional_restriction: optional && !state.selected_optional.includes(item.id) && context.restrictions?.includes("optional-stores") ? "Optional stores restricted by Standard" : null, actions: availableActions(expedition, definition, item.id, observer, context) }; });
  const active = items.filter((item) => state.required.includes(item.id)); const missing = active.filter((item) => !["operational", "serviceable"].includes(item.condition)); return { version: "yellow-beast-logistics-projection@v1", revision: state.revision, items, containers, loadout: { required: clone(state.required), optional: clone(state.optional), selected_optional: clone(state.selected_optional), ready: missing.length === 0, missing: missing.map((item) => item.label), restrictions: clone(context.restrictions ?? []), recommendations: clone(definition.loadout.public_recommendations ?? []), waiver_allowed: definition.loadout.waiver_allowed === true }, recent_transactions: state.transaction_history.slice(-5).map(({ action, summary, at }) => ({ action, summary, at })) };
}

module.exports = { DEFINITION_VERSION, STATE_VERSION, ACTIONS, CONTAINER_ACTIONS, validateDefinition, validateState, createState, migrate, attach, syncSpatial, transact, transactContainer, reconcile, availableActions, availableContainerActions, project, resolveItem };
