"use strict";
const history = require("./world-history"); const procedural = require("./procedural-complex"); const proceduralV2 = require("./procedural-complex-v2"); const crypto = require("node:crypto"); const clone = (x) => structuredClone(x); const digest = (x) => crypto.createHash("sha256").update(JSON.stringify(x)).digest("hex"); const OBSERVER = "yb-lost-player"; const generatorFor=(state)=>state.version===proceduralV2.VERSION?proceduralV2:procedural;
function start(world, seed, { region_id = null } = {}) { history.assertWorld(world); const run_id = history.beginRun(world, { profile: "lost", scenario: "lost-no-known-route", seed }); const generated = region_id ? world.regions[region_id]?.state : proceduralV2.initialize({ seed: `lost:${world.seed}:${seed}`, observer: OBSERVER, policy: "deep" }); if (!generated) throw Object.assign(new Error("unknown region"), { code: "REGION_UNKNOWN" }); if (region_id) { generated.discovery[OBSERVER] = { spaces: [], edges: [], features: [], landmarks: [], objects: [] }; generated.current[OBSERVER] = Object.keys(generated.nodes)[0]; } const actual_region_id = region_id ?? history.promoteRegion(world, run_id, generated); const resources = Number.parseInt(digest([seed,"loadout"]).slice(0,2),16)%2 ? ["personal-light","camera"] : ["personal-light"]; const exit_possible = Number.parseInt(digest([seed,"exit"]).slice(0,2),16)%2 === 0; const run = { version:"yellow-beast-lost@v1", run_id, seed, region_id:actual_region_id, state:generated, carried:resources, charge:2, notes:[], outcome:null, exit_possible }; history.event(world,run_id,"lost.started",{region_id:actual_region_id,resources,exit_possible},"pack-original-lost-simulation"); return run; }
function projection(run) { const generator=generatorFor(run.state), view=generator.visible(run.state,OBSERVER); const local=generator.VERSION===proceduralV2.VERSION?generator.observe(run.state,OBSERVER,"lost"):null; return { status:{carried:clone(run.carried),light_charge:run.charge,outcome:run.outcome},surroundings:{location:view.location,exits:view.exits.map(({alias})=>({alias})),features:view.features.map(({alias})=>({alias})),landmark:local?.landmark??null,environment:local?.environment??null,objects:local?.objects??[]},known_routes:generator.map(run.state,OBSERVER),run_notes:clone(run.notes) }; }
function move(world,run,alias) { if(run.outcome) return {ok:false,code:"RUN_TERMINAL"}; if(run.charge<1)return {ok:false,code:"DARKNESS"}; const generator=generatorFor(run.state); const result=generator.move(run.state,OBSERVER,alias); if(!result.ok)return result; if(generator.VERSION===proceduralV2.VERSION)generator.observe(run.state,OBSERVER,"lost"); run.charge-=1; history.event(world,run.run_id,"lost.explored",{region_id:run.region_id},"pack-original-lost-simulation"); return {ok:true}; }
function drop(world,run,item){const space_id=run.state.current[OBSERVER]; if(!run.carried.includes(item))return {ok:false}; const left=history.leaveRemnant(world,{run_id:run.run_id,region_id:run.region_id,space_id,type:item,provenance:"lost-run-remnant"}); run.carried=run.carried.filter(x=>x!==item); history.event(world,run.run_id,"lost.dropped",{artifact_id:left.artifact_id},"pack-original-lost-simulation"); return {ok:true,artifact_id:left.artifact_id};}
function escape(world,run){if(!run.exit_possible || Object.keys(run.state.nodes).length<2)return {ok:false,code:"NO_KNOWN_EXIT"};run.outcome="escaped";history.event(world,run.run_id,"lost.escaped",{region_id:run.region_id},"pack-original-lost-simulation");return {ok:true};}
function strand(world,run){if(run.outcome)return {ok:false};run.outcome="stranded";for(const item of [...run.carried])drop(world,run,item);history.event(world,run.run_id,"lost.stranded",{region_id:run.region_id},"pack-original-lost-simulation");return {ok:true};}
module.exports={start,projection,move,drop,escape,strand};
