"use strict";

// Presentation-only Q4 visual vocabulary. These functions accept safe
// projections and return labels/classes; they never mutate canonical state.
const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const registry = JSON.parse(fs.readFileSync(path.join(__dirname, "../data/visual-asset-provenance.json"), "utf8"));
const VERSION = "yellow-beast-q4-visuals@v1";
const STATUS = Object.freeze(["active", "local", "nearby", "separated", "remote", "contact-lost", "missing", "deceased", "portrait-unavailable", "restricted"]);
const EQUIPMENT = Object.freeze({ "battery-lamp":"lamp", "35mm-camera":"camera", "portable-survey-instrument":"instrument", "field-radio":"radio", "field-notebook":"notebook", "35mm-film":"film" });
const MEDIA = Object.freeze(["photograph", "film-frame", "video-frame", "audio-only", "damaged-film", "damaged-tape", "unrecovered", "restricted", "visual-unavailable", "render-pending", "render-failed", "schematic-fallback"]);
const RADIO = Object.freeze(["idle", "transmitting", "received", "awaiting-acknowledgement", "degraded", "unreadable", "contact-lost"]);
const MAP = Object.freeze(["no-record", "prior-record-loaded", "active-survey", "current-confirmed-layout", "reported-unverified-layout", "unresolved-conflict", "inaccessible-continuation", "incomplete-record"]);
const DOCUMENTS = Object.freeze(["assignment", "amended-assignment", "staging-manifest", "equipment-issue", "personnel-roster", "communications-log", "field-annotation", "evidence-index", "return-accountability", "provisional-review", "final-review", "follow-up-recommendation", "unresolved-notice"]);
const clone = (value) => structuredClone(value);
function digest(value) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function portrait(person = {}) { const identity = person.identity ?? person.personnel_id ?? person.id ?? "unknown-person"; const seed = digest({ identity, portrait_revision: 1 }); return { asset_id: `portrait-${seed.slice(0, 16)}`, identity, class_name: "badge-portrait-fallback", seed, source: "deterministic-local-fallback", archival: true, live_condition: false, provenance: "personnel-record-fallback" }; }
function personnelVisual(person = {}) { const status = String(person.status ?? person.contact_category ?? "active").toLowerCase().replace(/\s+/g, "-"); return { portrait: portrait(person), status: STATUS.includes(status) ? status : "restricted", state_asset: `personnel-${STATUS.includes(status) ? status : "restricted"}`, historical: ["deceased", "missing", "contact-lost"].includes(status), active: !["deceased", "missing"].includes(status) }; }
function equipmentVisual(item = {}) { const category = EQUIPMENT[item.category ?? item.type] ?? "equipment"; const state = String(item.state ?? item.known_condition ?? "unknown").toLowerCase().replace(/\s+/g, "-"); return { asset_id: `equipment-${category}`, category, state_asset: `equipment-${state}`, label: item.label ?? "Field equipment", provenance: "local-procedural-glyph" }; }
function mediaVisual(item = {}) { const type = String(item.type ?? "visual-unavailable").toLowerCase().replace(/\s+/g, "-"); const render = item.render?.status ?? (item.visual ? "ready" : "fallback"); const media = MEDIA.includes(type) ? type : (type.includes("audio") ? "audio-only" : "visual-unavailable"); return { asset_id: `evidence-${media}`, media, render_state: render, frame_class: render === "failed" ? "media-render-failed" : render === "pending" ? "media-render-pending" : "media-frame", unavailable: ["unrecovered", "restricted", "visual-unavailable"].includes(media), provenance: item.provenance ?? "canonical-evidence-record" }; }
function radioVisual(state = "idle") { const key = String(state).toLowerCase().replace(/\s+/g, "-"); return { asset_id: `radio-${RADIO.includes(key) ? key : "idle"}`, state: RADIO.includes(key) ? key : "idle", provenance: "local-procedural-glyph" }; }
function mapVisual(state = "no-record") { const key = String(state).toLowerCase().replace(/\s+/g, "-"); return { asset_id: `map-${MAP.includes(key) ? key : "incomplete-record"}`, state: MAP.includes(key) ? key : "incomplete-record", provenance: "local-procedural-symbol" }; }
function documentVisual(type = "assignment") { const key = String(type).toLowerCase().replace(/\s+/g, "-"); return { asset_id: `document-${DOCUMENTS.includes(key) ? key : "assignment"}`, type: DOCUMENTS.includes(key) ? key : "assignment", provenance: "local-document-template" }; }
function captureFacts(item = {}) { return { visible_scene: item.visible_scene ?? item.target_observation ?? "recorded field observation", visible_personnel: clone(item.visible_personnel ?? []), visible_objects: clone(item.visible_objects ?? (item.target_alias ? [item.target_alias] : [])), camera_angle: item.camera_angle ?? "field record", device: item.device ?? "recording-device", media: item.media ?? "field record", lighting: item.lighting ?? "observed lighting", capture_state: item.capture_state ?? "recorded" }; }
function renderSpec(item = {}) { const facts = captureFacts(item); const text = JSON.stringify(facts); if (/hidden_trajectory|latent_condition|future escalation|unrevealed|objective hidden|make it scary|narrator theory/i.test(text)) throw Object.assign(new Error("hidden state is not renderable"), { code: "VISUAL_HIDDEN_STATE" }); return { version: VERSION, evidence_id: item.id ?? null, immutable_capture_facts: facts, media_treatment: { device: facts.device, media: facts.media, capture_state: facts.capture_state }, stable_anchors: { mission_id: item.mission_id ?? null, location: item.location ?? null, personnel: facts.visible_personnel, objects: facts.visible_objects }, implementation: "observer-safe structured render", source_fact_digest: digest(facts) }; }
function registryReport() { return { version: registry.version, assets: registry.assets.map((asset) => ({ id: asset.id, class: asset.asset_class, rights: asset.rights_status, checksum: asset.checksum ?? digest(asset), locations: asset.locations })), prohibited: clone(registry.prohibited) }; }
function projection(q4 = {}) { return { personnel: (q4.team ?? []).map(personnelVisual), equipment: [...(q4.equipment?.required ?? []), ...(q4.equipment?.optional ?? [])].map(equipmentVisual), evidence: (q4.evidence ?? []).map(mediaVisual), radio: radioVisual(q4.channels?.standard?.available ? "idle" : "contact-lost"), map: mapVisual(q4.layout?.observed_spaces?.length ? "current-confirmed-layout" : "no-record"), documents: { mission: documentVisual("assignment"), manifest: documentVisual("staging-manifest"), review: documentVisual(q4.review ? "final-review" : "provisional-review") } }; }
module.exports = { VERSION, STATUS, EQUIPMENT, MEDIA, RADIO, MAP, DOCUMENTS, digest, portrait, personnelVisual, equipmentVisual, mediaVisual, radioVisual, mapVisual, documentVisual, captureFacts, renderSpec, registryReport, projection };
