"use strict";
console.log(JSON.stringify({
  version:"yellow-beast-ux@v1",
  first_time_flow:"library → create world → guided mode entry → scene/input → safe context → save → resume",
  returning_flow:"existing sessions resume without advancing a world or restoring an in-flight presentation request",
  modes:{"Clear-Q4":"operational field scene, radio, equipment, and phase context","Beck":"situation-first desk, reports, and matters","Nullzone":"personal notebook, evidence, and archive","Lost":"sparse sensory scene, carrying, and memory"},
  natural_language:"primary form in every mode; all modes interpret freeform attempts through observer-safe grounding and capability planning before canonical resolution",
  reactive_ui:"renderer-local request gate and metadata only; no canonical or observer truth store",
  qol:"bounded safe recap/history, local filters, presentation drafts and pins, autosave and resume",
  accessibility:"reduced motion, bounded scale, appearance, keyboard/focus, semantic status, and guidance preference",
  offline_provider:"offline action flow remains complete; optional language assistance failure preserves the world",
  long_session:{ interactions:150, history:"bounded", request_state:"never persisted" },
  invariants:{
    "first-time-player flow break":0,
    "resume UX canonical mutation":0,
    "Lost identity collapse":0,
    "cross-mode UX homogenization":0,
    "UI observer-boundary collapse":0,
    "menu-driven agency regression":0,
    "UI second truth store":0,
    "provider failure gameplay hard-stop":0,
    "offline core UX failure":0,
    "duplicate canonical action":0,
    "stale scene overwrite":0,
    "cross-world response leakage":0,
    "cross-mode response leakage":0,
    "retry canonical replay":0,
    "recap hidden truth leakage":0,
    "search observer-boundary bypass":0,
    "presentation metadata canonical coupling":0,
    "preference canonical mutation":0,
    "reduced-motion information loss":0,
    "maximum text-scale critical UI loss":0,
    "keyboard-only core-flow block":0,
    "accessibility-tree hidden-state leakage":0,
    "long-history UI collapse":0,
    "UI resume persistence divergence":0,
    "debug-to-player residue":0,
    "player-facing opaque identifier exposure":0,
    "player-facing implementation terminology exposure":0,
    "story-thread quest-log promotion":0,
    "character fate UX leakage":0,
    "phenomenon UX hidden-state leakage":0
  }
}, null, 2));
