"use strict";
const crypto = require("node:crypto"); const fs = require("node:fs"); const path = require("node:path");
const VERSION = "yellow-beast-world-history@v1"; const clone = (value) => structuredClone(value); const digest = (value) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
const GENERATOR_V1 = "yellow-beast-complex-generator@v1";
const GENERATOR_V2 = "yellow-beast-complex-generator@v2";
const SUPPORTED_GENERATORS = new Set([GENERATOR_V1, GENERATOR_V2]);
function generatorVersion(region) {
  const version = region?.generator_version ?? (region?.state?.version === GENERATOR_V1 ? GENERATOR_V1 : null);
  if (!SUPPORTED_GENERATORS.has(version)) throw Object.assign(new Error(`unsupported generator version: ${version ?? "missing"}`), { code: "GENERATOR_VERSION_UNSUPPORTED" });
  return version;
}
function assertRegion(region) {
  const version = generatorVersion(region);
  if (!region?.id || !region?.region_seed || !region?.state?.nodes || !region?.state?.edges) throw Object.assign(new Error("invalid persistent region"), { code: "REGION_STATE_INVALID" });
  for (const edge of Object.values(region.state.edges)) if (!region.state.nodes[edge.from] || (edge.to && !region.state.nodes[edge.to])) throw Object.assign(new Error("persistent edge references missing node"), { code: "REGION_GRAPH_INVALID" });
  if (version === GENERATOR_V2 && region.state.version !== GENERATOR_V2) throw Object.assign(new Error("v2 region state/version mismatch"), { code: "REGION_VERSION_MISMATCH" });
  return version;
}
function createWorld({ id = null, seed = "yellow-beast-world" } = {}) { const world_id = id ?? `world-${digest(["world", seed]).slice(0, 12)}`; return { version: VERSION, world_id, seed, next_run: 1, event_sequence: 0, runs: {}, regions: {}, evidence: {}, artifacts: {}, characters: {}, phenomena: {}, events: [], knowledge: { institutional: { records: {} }, civilian: { records: {} } } }; }
function assertWorld(world) { if (!world || world.version !== VERSION || !world.world_id) throw Object.assign(new Error("unsupported world history"), { code: "WORLD_VERSION_UNSUPPORTED" }); return world; }
function event(world, run_id, type, payload, authority = "pack-original-world-history") { const sequence = ++world.event_sequence; const id = `history-${digest([world.world_id, sequence, run_id, type, payload]).slice(0, 16)}`; const record = { id, world_id: world.world_id, run_id, sequence, type, payload: clone(payload), authority, provenance: "yellow-beast-structured-result" }; world.events.push(record); return record; }
function beginRun(world, { profile, scenario, seed }) { assertWorld(world); const ordinal = world.next_run++; const run_id = `run-${digest([world.world_id, ordinal, profile, scenario, seed]).slice(0, 16)}`; world.runs[run_id] = { id: run_id, world_id: world.world_id, ordinal, profile, scenario, seed, status: "active", history_ingested: false }; event(world, run_id, "run.started", { profile, scenario, seed }); return run_id; }
function regionId(state) { return `region-${digest([state.version, state.region_seed]).slice(0, 16)}`; }
function promoteRegion(world, run_id, state) { if (!state) return null; if (!SUPPORTED_GENERATORS.has(state.version)) throw Object.assign(new Error("unsupported generator version"), { code: "GENERATOR_VERSION_UNSUPPORTED" }); const id = regionId(state); const existing = world.regions[id]; if (existing && (existing.generator_version !== state.version || existing.region_seed !== state.region_seed)) throw Object.assign(new Error("conflicting region materialization"), { code: "REGION_CONFLICT" }); if (!existing) { world.regions[id] = { id, generator_version: state.version, region_seed: state.region_seed, first_materialized_by: run_id, baseline_state: clone(state), state: clone(state), discovery: [], provenance: { grammar_rule_ids: Object.values(state.nodes).map((node) => node.grammar_rule_id).sort(), authorities: [...new Set(Object.values(state.nodes).map((node) => node.authority))] } }; event(world, run_id, "region.materialized", { region_id: id, generator_version: state.version }); }
  const region = world.regions[id]; const observer = Object.keys(state.discovery)[0]; const discovered = state.discovery[observer]?.spaces ?? []; for (const space_id of discovered) if (!region.discovery.some((entry) => entry.run_id === run_id && entry.space_id === space_id)) { region.discovery.push({ run_id, space_id, domain: "observer-local" }); event(world, run_id, "region.discovered", { region_id: id, space_id }, "scenario-optional"); } return id; }
function recordInstitutional(world, run_id, id, payload) { if (world.knowledge.institutional.records[id]) return; world.knowledge.institutional.records[id] = { id, source_run: run_id, status: "archived-operational", payload: clone(payload) }; event(world, run_id, "institutional.record.archived", { record_id: id }); }
function recordInstitutionalRegionSummary(world, run_id, region_id, summary) { assertWorld(world); if (!world.regions[region_id]) return { ok: false, code: "REGION_UNKNOWN" }; const safe = { observed_architecture: clone(summary.observed_architecture ?? []), landmarks: clone(summary.landmarks ?? []), known_connections: summary.known_connections ?? 0, observed_environment: clone(summary.observed_environment ?? []), unresolved_frontier: summary.unresolved_frontier ?? 0, routes: clone(summary.routes ?? []) }; const id = `institutional-region-summary-${region_id}`; recordInstitutional(world, run_id, id, { region_id, summary: safe }); return { ok: true, record_id: id }; }
function ingestRun(world, run) { assertWorld(world); const run_id = run.run_id; const record = world.runs[run_id]; if (!record) throw Object.assign(new Error("unknown run"), { code: "RUN_UNKNOWN" }); if (record.history_ingested) return { ok: true, idempotent: true, run_id, region_id: record.region_id ?? null }; const region_id = promoteRegion(world, run_id, run.procedural); const expedition = run.expedition?.result; record.status = run.lifecycle; record.region_id = region_id; record.expedition_result = expedition ? clone(expedition) : null; record.history_ingested = true; event(world, run_id, "run.finalized", { lifecycle: run.lifecycle, outcome: expedition?.outcome ?? null, region_id });
  if (expedition) { const expedition_id = `expedition-${digest([world.world_id, run_id, expedition.mission_id]).slice(0, 16)}`; record.expedition_id = expedition_id; event(world, run_id, "expedition.ingested", { expedition_id, outcome: expedition.outcome }); for (const item of expedition.evidence ?? []) { const evidence_id = `evidence-${digest([world.world_id, run_id, item.id]).slice(0, 16)}`; if (!world.evidence[evidence_id]) { world.evidence[evidence_id] = { id: evidence_id, origin_run: run_id, type: item.type, creator: item.creator, custody: [{ holder: item.custodian, event: "created" }], source_location: item.location, provenance: item.provenance, availability: "archived" }; event(world, run_id, "evidence.promoted", { evidence_id, region_id }); } }
    const submitted = (expedition.messages ?? []).some((message) => message.intended_recipient === "Standard" && message.delivery_status === "delivered"); if (submitted) { if (region_id) recordInstitutional(world, run_id, `institutional-region-${region_id}`, { region_id, expedition_id }); for (const evidence_id of Object.keys(world.evidence).filter((id) => world.evidence[id].origin_run === run_id)) recordInstitutional(world, run_id, `institutional-evidence-${evidence_id}`, { evidence_id, expedition_id }); }
  }
  return { ok: true, idempotent: false, run_id, region_id };
}
function leaveRemnant(world, { run_id, region_id, space_id, type = "field-bag", provenance = "pack-original-remnant-fixture" }) { assertWorld(world); const id = `artifact-${digest([world.world_id, run_id, region_id, space_id, type]).slice(0, 16)}`; if (world.artifacts[id]) return { ok: true, idempotent: true, artifact_id: id }; world.artifacts[id] = { id, type, origin_run: run_id, region_id, space_id, state: "at-location", custody: [], recoverable: true, provenance, visibility: "location-local" }; event(world, run_id, "remnant.left", { artifact_id: id, region_id, space_id }); return { ok: true, artifact_id: id, idempotent: false }; }
function visibleArtifacts(world, { region_id, space_id }) { return Object.values(world.artifacts).filter((item) => item.region_id === region_id && item.space_id === space_id && item.state === "at-location" && item.visibility === "location-local").map((item) => ({ id: item.id, type: item.type })); }
function mutationEvents(world, region_id) { return world.events.filter((entry) => entry.type === "region.mutated" && entry.payload.region_id === region_id).sort((a, b) => a.sequence - b.sequence || a.id.localeCompare(b.id)); }
function applyMutation(state, mutation) { const next = clone(state); if (!next.nodes[mutation.space_id]) throw Object.assign(new Error("mutation target node missing"), { code: "MUTATION_TARGET_MISSING" }); next.mutations ??= []; if (next.mutations.some((entry) => entry.id === mutation.id)) return next;
  if (mutation.target_type === "object") { next.objects ??= {}; const objects = next.objects[mutation.space_id] ?? (next.objects[mutation.space_id] = []); if (mutation.operation === "remove") { const index = objects.findIndex((object) => object.id === mutation.target); if (index < 0) throw Object.assign(new Error("mutation object target missing"), { code: "MUTATION_TARGET_MISSING" }); objects.splice(index, 1); } else if (mutation.operation === "add") { if (!mutation.value?.id) throw Object.assign(new Error("mutation object add missing identity"), { code: "MUTATION_TARGET_MISSING" }); if (!objects.some((object) => object.id === mutation.value.id)) objects.push(clone(mutation.value)); } else throw Object.assign(new Error("unsupported object mutation"), { code: "MUTATION_OPERATION_UNSUPPORTED" });
  } else if (mutation.target_type === "node-property") { next.nodes[mutation.space_id].persistent ??= {}; next.nodes[mutation.space_id].persistent[mutation.target] = clone(mutation.value); } else if (mutation.target_type === "edge") { const edge = next.edges[mutation.target]; if (!edge) throw Object.assign(new Error("mutation edge target missing"), { code: "MUTATION_TARGET_MISSING" }); edge.persistent_state = clone(mutation.value); } else throw Object.assign(new Error("unsupported mutation target"), { code: "MUTATION_TARGET_UNSUPPORTED" });
  next.mutations.push(clone(mutation)); return next;
}
function rebuildRegion(world, region_id) { assertWorld(world); const region = world.regions[region_id]; if (!region) throw Object.assign(new Error("unknown persistent region"), { code: "REGION_UNKNOWN" }); const version = assertRegion(region); if (version !== GENERATOR_V2) return clone(region.state); const baseline = clone(region.baseline_state ?? region.state); if (baseline.version !== GENERATOR_V2) throw Object.assign(new Error("v2 region baseline/version mismatch"), { code: "REGION_VERSION_MISMATCH" }); let state = baseline; for (const entry of mutationEvents(world, region_id)) state = applyMutation(state, entry.payload.mutation); return state; }
function restoreRegion(world, region_id) { const region = world.regions[region_id]; const version = assertRegion(region); const state = version === GENERATOR_V2 ? rebuildRegion(world, region_id) : clone(region.state); return { generator_version: version, state }; }
function mutateRegion(world,{run_id,region_id,space_id,target_type="node-property",target,value,operation="set",provenance="pack-original-v2-mutation",authority="scenario-optional"}) { assertWorld(world); const region=world.regions[region_id]; if(!region || generatorVersion(region)!==GENERATOR_V2) return {ok:false,code:"REGION_VERSION_UNSUPPORTED"}; if (!region.state.nodes[space_id]) return {ok:false,code:"MUTATION_TARGET_MISSING"}; const mutation={id:`history-mutation-${digest([world.world_id,run_id,region_id,space_id,target_type,target,operation,value]).slice(0,16)}`,run_id,space_id,target_type,target,value:clone(value),operation,provenance,authority}; const existing = mutationEvents(world, region_id).find((entry) => entry.payload.mutation.id === mutation.id); if (existing) return {ok:true,idempotent:true,mutation:clone(existing.payload.mutation)}; const candidate = applyMutation(region.state, mutation); const record = event(world,run_id,"region.mutated",{region_id,space_id,target_type,target,operation,value:clone(value),provenance,authority,mutation}); region.state = candidate; return {ok:true,idempotent:false,mutation, event_id:record.id}; }
function recoverArtifact(world, { run_id, artifact_id, holder }) { const item = world.artifacts[artifact_id]; if (!item || item.state !== "at-location") return { ok: false, public_reason: "target unavailable" }; item.state = "recovered"; item.custody.push({ holder, event: "recovered", run_id }); event(world, run_id, "artifact.recovered", { artifact_id, holder }); return { ok: true, artifact: clone(item) }; }
// Character records are canonical world state plus append-only history events.
// The object index is a cacheable current-state view: it can be rebuilt from
// character.* events and is never an observer knowledge ledger or role table.
function characterState(world) { assertWorld(world); world.characters ??= {}; return world.characters; }
function character(world, identity) { return characterState(world)[identity] ?? null; }
function canInstantiateCharacter(world, identity) { return !character(world, identity); }
function instantiateCharacter(world, { run_id, identity, display_name, role = null, classification = "named-character", provenance = "pack-original-character-fixture", authority = "scenario-optional", source_claim_ids = [] }) {
  if (!identity || !display_name || !canInstantiateCharacter(world, identity)) return { ok: false, code: "CHARACTER_IDENTITY_UNAVAILABLE" };
  const record = { identity, display_name, role, classification, status: "active", provenance, authority, source_claim_ids: clone(source_claim_ids), instantiated_by: run_id, death: null };
  characterState(world)[identity] = record; event(world, run_id, "character.instantiated", { identity, display_name, role, classification, provenance, authority, source_claim_ids: clone(source_claim_ids) }, authority);
  return { ok: true, character: clone(record) };
}
function setCharacterStatus(world, { run_id, identity, status, reason = null }) {
  const record = character(world, identity); if (!record) return { ok: false, code: "CHARACTER_UNKNOWN" };
  if (record.status === "dead" && status !== "dead") return { ok: false, code: "CHARACTER_DEATH_IRREVERSIBLE" };
  if (!["active", "unavailable", "missing", "unknown", "retired", "removed", "dead"].includes(status)) return { ok: false, code: "CHARACTER_STATUS_INVALID" };
  record.status = status;
  if (status === "dead") { record.death ??= { run_id, reason }; event(world, run_id, "character.died", { identity, reason }, record.authority); }
  else event(world, run_id, "character.status.changed", { identity, status, reason }, record.authority);
  return { ok: true, character: clone(record) };
}
function rebuildCharacters(world) {
  assertWorld(world); const rebuilt = {};
  for (const entry of world.events.filter((item) => item.type === "character.instantiated" || item.type === "character.died" || item.type === "character.status.changed").sort((a, b) => a.sequence - b.sequence)) {
    const payload = entry.payload ?? {};
    if (entry.type === "character.instantiated" && !rebuilt[payload.identity]) rebuilt[payload.identity] = { identity: payload.identity, display_name: payload.display_name, role: payload.role ?? null, classification: payload.classification, status: "active", provenance: payload.provenance, authority: payload.authority, source_claim_ids: clone(payload.source_claim_ids ?? []), instantiated_by: entry.run_id, death: null };
    if (entry.type === "character.died" && rebuilt[payload.identity]) { rebuilt[payload.identity].status = "dead"; rebuilt[payload.identity].death = { run_id: entry.run_id, reason: payload.reason ?? null }; }
    if (entry.type === "character.status.changed" && rebuilt[payload.identity] && rebuilt[payload.identity].status !== "dead") rebuilt[payload.identity].status = payload.status;
  }
  return rebuilt;
}
function knownRegions(world, profile) { assertWorld(world); if (profile !== "field-researcher" && profile !== "async-command") return []; return Object.values(world.knowledge.institutional.records).filter((record) => record.id.startsWith("institutional-region-")).map((record) => ({ record_id: record.id, region_id: record.payload.region_id })); }
function summary(world, profile) { assertWorld(world); return { world_id: world.world_id, version: world.version, completed_runs: Object.values(world.runs).filter((run) => run.history_ingested).length, institutional_regions: knownRegions(world, profile).length, archived_expeditions: Object.values(world.runs).filter((run) => run.expedition_id).length }; }
function saveWorld(file, world) { assertWorld(world); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, `${JSON.stringify(world, null, 2)}\n`); }
function loadWorld(file) { const world = assertWorld(JSON.parse(fs.readFileSync(file, "utf8"))); const rebuiltCharacters = rebuildCharacters(world); if (Object.keys(rebuiltCharacters).length) world.characters = rebuiltCharacters; else world.characters ??= {}; for (const region of Object.values(world.regions)) { if (!region.generator_version && region.state?.version === GENERATOR_V1) region.generator_version = GENERATOR_V1; assertRegion(region); if (region.generator_version === GENERATOR_V2) region.state = rebuildRegion(world, region.id); } return world; }
module.exports = { VERSION, GENERATOR_V1, GENERATOR_V2, SUPPORTED_GENERATORS, createWorld, assertWorld, event, beginRun, ingestRun, promoteRegion, regionId, generatorVersion, restoreRegion, rebuildRegion, leaveRemnant, visibleArtifacts, mutateRegion, recoverArtifact, characterState, character, canInstantiateCharacter, instantiateCharacter, setCharacterStatus, rebuildCharacters, recordInstitutionalRegionSummary, knownRegions, summary, saveWorld, loadWorld };
