"use strict";
const crypto = require("node:crypto"); const fs = require("node:fs"); const path = require("node:path");
const VERSION = "yellow-beast-world-history@v1"; const clone = (value) => structuredClone(value); const digest = (value) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
function createWorld({ id = null, seed = "yellow-beast-world" } = {}) { const world_id = id ?? `world-${digest(["world", seed]).slice(0, 12)}`; return { version: VERSION, world_id, seed, next_run: 1, event_sequence: 0, runs: {}, regions: {}, evidence: {}, artifacts: {}, events: [], knowledge: { institutional: { records: {} }, civilian: { records: {} } } }; }
function assertWorld(world) { if (!world || world.version !== VERSION || !world.world_id) throw Object.assign(new Error("unsupported world history"), { code: "WORLD_VERSION_UNSUPPORTED" }); return world; }
function event(world, run_id, type, payload, authority = "pack-original-world-history") { const sequence = ++world.event_sequence; const id = `history-${digest([world.world_id, sequence, run_id, type, payload]).slice(0, 16)}`; const record = { id, world_id: world.world_id, run_id, sequence, type, payload: clone(payload), authority, provenance: "yellow-beast-structured-result" }; world.events.push(record); return record; }
function beginRun(world, { profile, scenario, seed }) { assertWorld(world); const ordinal = world.next_run++; const run_id = `run-${digest([world.world_id, ordinal, profile, scenario, seed]).slice(0, 16)}`; world.runs[run_id] = { id: run_id, world_id: world.world_id, ordinal, profile, scenario, seed, status: "active", history_ingested: false }; event(world, run_id, "run.started", { profile, scenario, seed }); return run_id; }
function regionId(state) { return `region-${digest([state.version, state.region_seed]).slice(0, 16)}`; }
function promoteRegion(world, run_id, state) { if (!state) return null; const id = regionId(state); const existing = world.regions[id]; if (existing && (existing.generator_version !== state.version || existing.region_seed !== state.region_seed)) throw Object.assign(new Error("conflicting region materialization"), { code: "REGION_CONFLICT" }); if (!existing) { world.regions[id] = { id, generator_version: state.version, region_seed: state.region_seed, first_materialized_by: run_id, state: clone(state), discovery: [], provenance: { grammar_rule_ids: Object.values(state.nodes).map((node) => node.grammar_rule_id).sort(), authorities: [...new Set(Object.values(state.nodes).map((node) => node.authority))] } }; event(world, run_id, "region.materialized", { region_id: id, generator_version: state.version }); }
  const region = world.regions[id]; const observer = Object.keys(state.discovery)[0]; const discovered = state.discovery[observer]?.spaces ?? []; for (const space_id of discovered) if (!region.discovery.some((entry) => entry.run_id === run_id && entry.space_id === space_id)) { region.discovery.push({ run_id, space_id, domain: "observer-local" }); event(world, run_id, "region.discovered", { region_id: id, space_id }, "scenario-optional"); } return id; }
function recordInstitutional(world, run_id, id, payload) { if (world.knowledge.institutional.records[id]) return; world.knowledge.institutional.records[id] = { id, source_run: run_id, status: "archived-operational", payload: clone(payload) }; event(world, run_id, "institutional.record.archived", { record_id: id }); }
function ingestRun(world, run) { assertWorld(world); const run_id = run.run_id; const record = world.runs[run_id]; if (!record) throw Object.assign(new Error("unknown run"), { code: "RUN_UNKNOWN" }); if (record.history_ingested) return { ok: true, idempotent: true, run_id, region_id: record.region_id ?? null }; const region_id = promoteRegion(world, run_id, run.procedural); const expedition = run.expedition?.result; record.status = run.lifecycle; record.region_id = region_id; record.expedition_result = expedition ? clone(expedition) : null; record.history_ingested = true; event(world, run_id, "run.finalized", { lifecycle: run.lifecycle, outcome: expedition?.outcome ?? null, region_id });
  if (expedition) { const expedition_id = `expedition-${digest([world.world_id, run_id, expedition.mission_id]).slice(0, 16)}`; record.expedition_id = expedition_id; event(world, run_id, "expedition.ingested", { expedition_id, outcome: expedition.outcome }); for (const item of expedition.evidence ?? []) { const evidence_id = `evidence-${digest([world.world_id, run_id, item.id]).slice(0, 16)}`; if (!world.evidence[evidence_id]) { world.evidence[evidence_id] = { id: evidence_id, origin_run: run_id, type: item.type, creator: item.creator, custody: [{ holder: item.custodian, event: "created" }], source_location: item.location, provenance: item.provenance, availability: "archived" }; event(world, run_id, "evidence.promoted", { evidence_id, region_id }); } }
    const submitted = (expedition.messages ?? []).some((message) => message.intended_recipient === "Standard" && message.delivery_status === "delivered"); if (submitted) { if (region_id) recordInstitutional(world, run_id, `institutional-region-${region_id}`, { region_id, expedition_id }); for (const evidence_id of Object.keys(world.evidence).filter((id) => world.evidence[id].origin_run === run_id)) recordInstitutional(world, run_id, `institutional-evidence-${evidence_id}`, { evidence_id, expedition_id }); }
  }
  return { ok: true, idempotent: false, run_id, region_id };
}
function leaveRemnant(world, { run_id, region_id, space_id, type = "field-bag", provenance = "pack-original-remnant-fixture" }) { assertWorld(world); const id = `artifact-${digest([world.world_id, run_id, region_id, space_id, type]).slice(0, 16)}`; if (world.artifacts[id]) return { ok: true, idempotent: true, artifact_id: id }; world.artifacts[id] = { id, type, origin_run: run_id, region_id, space_id, state: "at-location", custody: [], recoverable: true, provenance, visibility: "location-local" }; event(world, run_id, "remnant.left", { artifact_id: id, region_id, space_id }); return { ok: true, artifact_id: id, idempotent: false }; }
function visibleArtifacts(world, { region_id, space_id }) { return Object.values(world.artifacts).filter((item) => item.region_id === region_id && item.space_id === space_id && item.state === "at-location" && item.visibility === "location-local").map((item) => ({ id: item.id, type: item.type })); }
function recoverArtifact(world, { run_id, artifact_id, holder }) { const item = world.artifacts[artifact_id]; if (!item || item.state !== "at-location") return { ok: false, public_reason: "target unavailable" }; item.state = "recovered"; item.custody.push({ holder, event: "recovered", run_id }); event(world, run_id, "artifact.recovered", { artifact_id, holder }); return { ok: true, artifact: clone(item) }; }
function knownRegions(world, profile) { assertWorld(world); if (profile !== "field-researcher" && profile !== "async-command") return []; return Object.values(world.knowledge.institutional.records).filter((record) => record.id.startsWith("institutional-region-")).map((record) => ({ record_id: record.id, region_id: record.payload.region_id })); }
function summary(world, profile) { assertWorld(world); return { world_id: world.world_id, version: world.version, completed_runs: Object.values(world.runs).filter((run) => run.history_ingested).length, institutional_regions: knownRegions(world, profile).length, archived_expeditions: Object.values(world.runs).filter((run) => run.expedition_id).length }; }
function saveWorld(file, world) { assertWorld(world); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, `${JSON.stringify(world, null, 2)}\n`); }
function loadWorld(file) { return assertWorld(JSON.parse(fs.readFileSync(file, "utf8"))); }
module.exports = { VERSION, createWorld, assertWorld, beginRun, ingestRun, promoteRegion, regionId, leaveRemnant, visibleArtifacts, recoverArtifact, knownRegions, summary, saveWorld, loadWorld };
