"use strict";
const path = require("node:path");
const fs = require("node:fs");
const { app, BrowserWindow, ipcMain, dialog, shell } = require("electron");
const { DesktopService } = require("./service");
const { CredentialStore } = require("./credentials");
const profiles = require("./profile-resolver");

let windowRef; let service;
const testMode = process.argv.some((argument) => ["--desktop-smoke", "--renderer-smoke", "--first-run-smoke", "--hosted-ai-smoke"].includes(argument));
const applicationProfile = profiles.resolveApplicationProfile({ argv: process.argv, testMode, productionUserDataRoot: app.getPath("userData") });
if (applicationProfile.test) app.setPath("userData", applicationProfile.paths.userDataRoot);
function logger(message) { const log = path.join(applicationProfile.paths.logs, "desktop.log"); fs.mkdirSync(path.dirname(log), { recursive: true }); fs.appendFileSync(log, `${new Date().toISOString()} ${message}\n`); }
const handlers = ["getAppInfo", "listModes", "listWorlds", "createWorld", "loadWorld", "saveWorld", "deleteWorld", "exportWorld", "importWorld", "renameWorld", "restoreBackup", "exportBrokenWorld", "getSettings", "updateSettings", "getProviderStatus", "configureOpenAI", "removeOpenAIKey", "configureProvider", "removeProviderKey", "testProvider", "getDiagnostics", "exportTesterReport", "getDeveloperSnapshot", "getInterpretationProvenance", "traceDeveloperIntent", "controlQ4PhenomenonFixture", "getQ4PersonnelStatus", "createQ4Personnel", "confirmQ4Personnel", "startSession", "resumeSession", "getGameplayProjection", "getInstitutionProjection", "getAvailableActions", "submitAction", "submitNatural", "submitQ4Communication", "retryQ4Communication", "cancelQ4Communication", "submitQ4Handoff", "submitQ4Logistics", "selectQ4OptionalStore", "renderEvidence"];
function createWindow({ hidden = false } = {}) { windowRef = new BrowserWindow({ width: 1920, height: 1080, minWidth: 820, minHeight: 600, show: false, icon: path.join(__dirname, "assets", "async-icon-master.png"), webPreferences: { preload: path.join(__dirname, "preload.js"), contextIsolation: true, nodeIntegration: false, sandbox: true } }); if (!hidden) windowRef.once("ready-to-show", () => windowRef.show()); windowRef.loadFile(path.join(__dirname, "renderer", "index.html")); }
function desktopSmoke() { const root = applicationProfile.paths.root; const smoke = new DesktopService({ appDataPath: root }); if (smoke.listWorlds().worlds.length !== 0) throw new Error("packaged desktop smoke profile was not empty"); const world = smoke.createWorld({ name: "Packaged smoke", seed: "desktop-package" }).world; for (const mode of ["async-command", "field-researcher", "local-anomaly", "lost"]) { const started = smoke.startSession({ world_id: world.id, mode, seed: mode }); if (!started.ok) throw new Error(`unable to start ${mode}`); const action = started.projection.available_actions[0]; const result = smoke.submitAction({ world_id: world.id, mode, action: action.type, target: action.targets?.[0]?.ref ?? null }); if (!result.ok) throw new Error(`unable to act in ${mode}`); } smoke.shutdown(); const resumed = new DesktopService({ appDataPath: root }).resumeSession({ world_id: world.id, mode: "field-researcher" }); if (!resumed.ok) throw new Error("packaged session did not resume"); console.log(JSON.stringify({ desktop_smoke: "passed", world_id: world.id, offline: true, test_profile: applicationProfile.runId })); }
function registerHandlers() { for (const name of handlers) ipcMain.handle(`yellow-beast:${name}`, (_event, input = {}) => service[name](input)); ipcMain.handle("yellow-beast:chooseExportWorld", async (_event, { world_id }) => { const choice = await dialog.showSaveDialog({ defaultPath: `${world_id}.yellow-beast.json`, filters: [{ name: "Yellow Beast world", extensions: ["json"] }] }); return choice.canceled ? { ok: false, error: { code: "EXPORT_CANCELLED", message: "Export was cancelled." } } : service.exportWorld({ world_id, destination: choice.filePath }); }); ipcMain.handle("yellow-beast:chooseImportWorld", async () => { const choice = await dialog.showOpenDialog({ properties: ["openFile"], filters: [{ name: "Yellow Beast world", extensions: ["json"] }] }); return choice.canceled ? { ok: false, error: { code: "IMPORT_CANCELLED", message: "Import was cancelled." } } : service.importWorld({ source: choice.filePaths[0] }); }); ipcMain.handle("yellow-beast:openLogFolder", () => shell.openPath(service.paths.logs).then(() => ({ ok: true }))); }
app.whenReady().then(() => { const root = applicationProfile.paths.root; service = new DesktopService({ appDataPath: root, logger, credentials: new CredentialStore({ safeStorage: require("electron").safeStorage, file: path.join(applicationProfile.paths.credentials, "openai.bin") }), defaultQ4Scenario:process.argv.includes("--reference-expedition") ? "reference-expedition" : "procedural-survey" }); if (process.argv.includes("--desktop-smoke")) { try { desktopSmoke(); app.exit(0); } catch (error) { console.error(error.message); app.exit(1); } return; } registerHandlers(); if (process.argv.some((argument) => ["--renderer-smoke", "--first-run-smoke", "--hosted-ai-smoke"].includes(argument))) { createWindow({ hidden:true }); const harness = process.argv.includes("--first-run-smoke") ? "./first-run-smoke" : process.argv.includes("--hosted-ai-smoke") ? "./hosted-ai-smoke" : "./renderer-smoke"; require(harness).run(windowRef).catch((error) => { console.error(error.stack); app.exit(1); }); return; } createWindow(); app.on("activate", () => { if (BrowserWindow.getAllWindows().length === 0) createWindow(); }); });
app.on("before-quit", () => { try { service?.shutdown(); } catch (error) { logger(`shutdown failure: ${error.message}`); } });
